feat: restDocs 적용
woowacourse-teams/2022-nae-pyeon pull request #170
Opened 2022-07-22 01:53 UTC by Seungpang

restDocs를 빠르게 적용했습니다.
다만 리팩토링이 필요합니다..

close #162

2022-07-22 02:56 UTC, kth990303 approved these changes
restdocs 만들어주셔서 감사합니다~~

2022-07-22 02:56 UTC, kth990303 commented on backend/build.gradle
> +	}
상대경로 방법도 좋지만, `baseDirFollowsSourceFile()`를 이용하는 방법도 찾아보면 좋을 거 같아요. 이 명령어의 역할은 아래와 같습니다!

특정 파일에서 다른 .adoc 파일을 include하는 경우에, 이들을 동일 경로로 설정하게 해주는 역할을 해줘요. gradle 7부터는 이걸 추가하지 않으면 각각의 개별 경로로 .adoc 파일들을 인식하기 때문에, base 경로에선 .adoc 파일들을 인식하지 못해 api 자동 문서화된 index.html 파일이 생성되지 않게 돼요.

[오리의 학습로그](https://prolog.techcourse.co.kr/studylogs/2499)에도 적혀있으니 확인해보면 좋을 거 같네요

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/resources/json/teams/team-update.json
> +}
나중에 시간되면 Mocking 하는 방법을 이용해봐도 좋겠네요!

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/MessageControllerTest.java
> +                                .header("Authorization", "Bearer " + teamMemberAccessToken)
나중에 여력이 되면 이 부분을 꼭 test 토큰값을 주는 게 아닌, 아래처럼 변경해봐도 괜찮을 거 같아요

AS-IS
```
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjU4NDU3MjcwLCJleHAiOjE2NTg0NjA4NzB9.lcvMAger0l8oHgKS3ZYhFXsUdG1CU3tOtmSI7200i18
```
TO-DO
```
Authorization: Bearer Token XXX
```

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
> +                                                .attributes(field("length", "255자 이내"))
필드까진 안 줘도 될 것 같지만, 필드를 줘야 한다면 다른 api에도 attributes를 해주는 게 좋아보입니다!

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/RestDocsConfiguration.java
> +            Preprocessors.preprocessResponse(Preprocessors.prettyPrint())
`prettyPrint()` 적용 👍

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +    private ResourceLoader resourceLoader;
없어도 될 것 같아요!

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +            .build();
여기서 이미 mockMvc 세팅을 해주고 있기 때문에 `@AutoConfigureMockMvc`는 없어도 될 것 같아요. 두 가지 방법을 혼합해서 쓰고 있는 것 같아요! 크게 문제되진 않긴 합니다.

2022-07-22 02:56 UTC, kth990303 commented on backend/src/test/resources/schema.sql
> +create table member
test db 적용 감사합니다! 👍

2022-07-22 07:28 UTC, asebn1 commented
3차 스프린트 때 설명해주시면 감사하겠습니다! 다음에 같이 적용해보겠습니다 👍

2022-07-22 07:28 UTC, asebn1 approved these changes

2022-07-24 08:21 UTC, asebn1 approved these changes

2022-07-24 08:21 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/document/RestDocsConfiguration.java
> +            Preprocessors.preprocessResponse(Preprocessors.prettyPrint())
RestDocsConfiguration으로 따로 빼신 이유가 있으신가요?
TestSupport에서 같이 해줘도 될 것 같아서 질문드려봅니다!

2022-07-24 08:27 UTC, asebn1 approved these changes

2022-07-24 08:27 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
> +                                .content(readJson("/json/members/member-create.json"))
mocking 말고 직접 만들어주신 이유가 있으신가요?

2022-07-26 05:59 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
> +                                                .attributes(field("length", "255자 이내"))
실질적으로 request,response만 사용하고 있어서 필드주는 부분을 모두 제거했습니다.

2022-07-26 06:00 UTC, Seungpang commented on backend/build.gradle
> +	}
baseDirFollowsSourceFile()는 모르는 부분이였는데 하나 배워가네요!

2022-07-26 06:04 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +    private ResourceLoader resourceLoader;
다른걸 사용하다가 바꾸는 과정에서 제거하지 못했네요! 제거했습니다.

2022-07-26 06:05 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +            .build();
`@AutoConfigureMockMvc` 부분을 제거했습니다.

2022-07-26 06:16 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/MessageControllerTest.java
> +                                .header("Authorization", "Bearer " + teamMemberAccessToken)
그러면 테스트 방식이 변경되어야 할 거 같습니다. SpringBootTest에서 WebMvcTest로 변경되어야 할 거 같습니다.

2022-07-26 06:18 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
> +                                .content(readJson("/json/members/member-create.json"))
현재까지 저희 팀에서 가져가는 테스트 방식이 단위테스트 목적으로 따로 repository 테스트나 service테스트를 작성하지 않고
모두다 SpringBootTest를 적용하고 있고 mocking을 할 경우 오히려 코드가 더 복잡해질 우려가 있어서 이런 방식을 사용했습니다.

2022-07-26 06:19 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/document/RestDocsConfiguration.java
> +            Preprocessors.preprocessResponse(Preprocessors.prettyPrint())
bean으로 등록해서 사용하는 이유가 컸습니다. 다순하게 TestSupport에서도 
정적팩토리 메서드로 정의해도 코드는 문제없이 동작할 것 같네요!

2022-07-27 09:29 UTC, kth990303 requested changes
테스트가 실패해서 레닥이 안켜져요 ㅜㅜ

2022-07-27 09:29 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +        messageService.saveMessage("많은 가르침 받았습니다.", memberId2, rollingpaperId2);
#187 PR이 머지되면 색상이 추가되므로 해당 부분이 충돌이 날 것 같아요! restDocs를 먼저 머지하거나, 색상을 추가해서 진행하거나 둘 중 하나를 택해야될 것 같네요 😅

2022-07-27 09:29 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/MemberControllerTest.java
> +class MemberControllerTest extends TestSupport {
테스트가 실패해서 `./gradlew clean bootJar` 명령어 실행이 안되네요 😢 
확인 부탁드립니다!
<img width="671" alt="image" src="https://user-images.githubusercontent.com/57135043/181212639-0bbdafb6-b59d-44bc-bc11-e6eb9de5ad95.png">
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/57135043/181212683-f1fdde61-d86a-4047-a8fa-c6d01e6b2286.png">

2022-07-29 06:55 UTC, kth990303 approved these changes
👍

2022-08-04 07:14 UTC, merged