feat: mypage UI를 구현한다
woowacourse-teams/2022-nae-pyeon pull request #186
Opened 2022-07-26 12:53 UTC by prefer2

## 구현 사항
- UserProfile 컴포넌트 구현
- 사용자가 받은 롤링페이퍼 보여주는 카드 컴포넌트 구현
- 사용자가 작성한 메시지 카드 컴포넌트 구현
- 페이징 컴포넌트 구현

2022-07-27 01:52 UTC, soyi47 requested changes
도리~ 마이페이지 구현하느라 고생했어요!

코멘트 남겨봤으니 확인해보고 궁금한 점 말씀해주세요~ 🥰

2022-07-27 01:52 UTC, soyi47 commented on frontend/src/components/CounterWithText.tsx
> +};
`CounterWithText`라는 이름만 봐서는 어떤 역할을 하는지 잘 와닿지 않네요 ㅠㅠ 
1. 확인해보니 마이페이지의 Tab 역할을 하고 있고
2. 마이페이지 외에 재사용될 일은 없을 것 같은데

`MyPageTab` 같은 이름은 어떤가요?

2022-07-27 01:52 UTC, soyi47 commented on frontend/src/components/Paging.tsx
> +        </StyledPageButtons>
중복이 많아서 줄여볼 수 있을 것 같은데, 방법 한번 고민해봅시당..!

당장 생각나는 방식은 `[currentPage - 2, currentPage - 1, currentPage, currentPage + 1, currentPage + 2]`와 같은 배열을 한 번 정리해서 map으로 렌더링 로직으로 작성하면 어떨까 싶어요.

2022-07-27 01:52 UTC, soyi47 commented on frontend/src/components/Paging.tsx
> +          ))}
요기 삼항 연산자가 연속 되어서 알아보기가 힘들어요 ㅠㅠ
조건문과 사용되는 배열들이 어떤 배열인지 더 알아보기 쉽게 표현하면 좋겠습니다!

2022-07-27 01:52 UTC, soyi47 commented on frontend/src/pages/MyPage.tsx
> +      )}
렌더 로직이 좀 많이 길어지네요. 여기 영역을 다른 컴포넌트로 분리해보면 어떨까요?

2022-07-27 06:24 UTC, prefer2 commented on frontend/src/components/Paging.tsx
> +        </StyledPageButtons>
요부분 수정해서 올려놓았슴당 [baa2c6a](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/baa2c6a778cd7870d8c9bb12efab7377700bd00c)

2022-07-27 06:56 UTC, prefer2 commented on frontend/src/components/UserProfile.tsx
> +  const [mode, setMode] = useState("normal");
아 맞다 타입스크립트! 이런 리뷰 너무 좋네요 [ed5597a](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/ed5597a9a7dae498764537c90e8f9fc62e70c004)

상수로 지정한 값들을 type으로 다시 사용하기 위해서 ValueOf를 추가해보았어요. 소피아의 의견이 궁금합니당 [3f81abe](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/3f81abed85b1d5b97059bef2fb1ed11b4de5d58e)

2022-07-27 06:57 UTC, prefer2 commented on frontend/src/components/UserProfile.tsx
> +  };
오 맞네요. 두 로직은 항상 같이 움직이는 로직이라 묶어줘도 될 것 같아요. 이건 같이 리팩토링 해보는걸로 ❤️

2022-07-27 07:12 UTC, prefer2 commented on frontend/src/pages/MyPage.tsx
> +  const [tab, setTab] = useState("rolling");
수정 완료! [30dec80](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/30dec80f954d401a0a791a3371e72c623082666c)

2022-07-28 01:52 UTC, soyi47 commented on frontend/src/components/UserProfile.tsx
> +  const [mode, setMode] = useState("normal");
오 `ValueOf`가 있군요. 배워갑니다! 좋아요! 👍

2022-07-28 02:09 UTC, soyi47 requested changes
수정한 부분들 잘 확인했어요~
새로운 코멘트 남겨봤습니다!

한번 확인해보시고, 오늘 중에 반영할 수 있는 것들만 빠르게 반영해주세요. 
다음 기능 작업은 바꿔서 진행하기로 했으니, 제가 또 고민해서 수정해볼게요! 
수정 후 말씀해주시면 확인 후 merge 하겠습니다. 🥰

2022-07-28 02:09 UTC, soyi47 commented on frontend/src/pages/MyPage.tsx
> +      )}
MyPage에 Tab이 하나 더 늘어난다면(물론 지금은 두 개뿐이지만..!) 상당히 길어질 로직 같은데, MyPageContent 같은 이름으로 컴포넌트를 분리하면 어떨까요?
tab 상태를 prop으로 내려 받아 조건에 따라 렌더링이 달라지도록 만들어볼 수 있을 것 같아요.

메인 컨텐츠가 바로 페이지 컴포넌트에서 보이는 게 낫다고 생각한다면 불필요한 분리일 수도 있을 것 같아요. 도리 의견은 어떤가요~?

2022-07-28 02:09 UTC, soyi47 commented on frontend/src/pages/MyPage.tsx
> +      </StyledCounters>
MyPageTab을 감싸는데 이름이 StyledCounters 군요! 수정이 필요해보입니다. 🧐

2022-07-28 02:09 UTC, soyi47 commented on frontend/src/components/Paging.tsx
> +        </StyledPageButtons>
로직이 확 줄었네요! 조금 이해하는데 어려움이 있었지만...! 
더 가독성 좋게 작성할 수 없을지 저도 같이 고민해보죠 🤔

2022-07-28 02:21 UTC, prefer2 commented on frontend/src/components/MyPageTab.tsx
> +  onClick: () => void;
타스까지 잘하는 당신....멋져
적용완 [26dcc9b](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/26dcc9bf95b78574d20edb330c59030a579a2e41)

2022-07-28 02:23 UTC, prefer2 commented on frontend/src/pages/MyPage.tsx
> +  SEND_MESSAGE: "send_message",
영어까지 잘하네 [a5ca8e7](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/a5ca8e775fa924023f078ffc03a6600da26ef1a2)

2022-07-28 04:15 UTC, prefer2 commented on frontend/src/pages/MyPage.tsx
> +      )}
고민고민 끝에 각 List들 안에 페이징을 추가하는 것으로 바꿔보았습니다
[46928db](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/46928db6a6c80a315670f1ba7bbc777406353e4d)

2022-07-28 04:17 UTC, prefer2 commented on frontend/src/pages/MyPage.tsx
> +      </StyledCounters>
맞네요 맞네요 [91e0a1f](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/186/commits/91e0a1f75d72b5e5fe1f23234111399e17416a2c)

2022-07-28 11:36 UTC, soyi47 approved these changes
도리~ 수정하느라 고생했습니다. 💕

다음 작업을 위해 바로 approve merge 할게요!
코멘트 하나 남겼는데, 확인하고 의견 주세요.
해당 코멘트 관련해서 수정이 필요하면 제가 다음 작업 진행하면서 같이 해도 될 것 같아요!

2022-07-28 11:36 UTC, soyi47 commented on frontend/src/components/MyPageRollingpaperListPaging.tsx
> +};
요기 컴포넌트 전체가 Paging은 아닌 것 같은데 컴포넌트 이름을 이렇게 지은 이유가 있나요?
제가 느끼기엔 List 안에 Paging이 포함된 구조라, MyPageRollingpaperList도 충분한 것 같아서요!

2022-07-28 11:36 UTC, merged