feat: 메시지 색상 변경 기능을 추가한다.
woowacourse-teams/2022-nae-pyeon pull request #187
Opened 2022-07-26 13:32 UTC by kth990303

close #185 

## 구현 내용
- 메시지 색상 변경 기능 추가에 따른 리팩터링
- 메시지 인수테스트에서 수정 시에 `제대로 수정됐는지 확인하지 않고, 상태코드만 확인하던 테스트`를 `제대로 수정됐는지 확인`하도록 변경

## 논의하고 싶은 내용
- 도메인의 색상이 null이어도 상관없을까? 우선은 `nullable=false`는 넣지 않았다.

2022-07-27 04:54 UTC, asebn1 approved these changes
잘 구현해주셨네요! 수고하셨습니다. 코멘트만 확인 부탁드려요~

2022-07-27 04:54 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/MessageController.java
> +        );
```suggestion
        messageService.updateMessage(
                messageId, 
                messageUpdateContentRequest.getContent(),
                messageUpdateContentRequest.getColor(), 
                loginMemberRequest.getId()
        );
```
가 더 나아보여요!

2022-07-27 04:54 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/JpaMessageRepository.java
>      }
👍

2022-07-27 05:30 UTC, Seungpang approved these changes
케이 구현해주신 내용 잘봤습니다! 👍 
메시지 색깔의 같은 경우 default값을 정하는게 더 좋을 것 같아요!
프론트와 상의해서 default 값을 정해보는 건 어떨까요?

2022-07-27 07:41 UTC, yxxnghwan approved these changes
안녕하세요 케이! 기능 구현 수고하셨습니다!
너무 잘 해주셨고,
테스트 코드에서 사소한 고칠점 발견해서 코멘트 남겼으니 고치고 머지 바로 하면 될 것 같아요!
approve 해둘게용❤️

2022-07-27 07:41 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
> +        );
꼼꼼한 검증👍

2022-07-27 07:41 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
>                  .getId();
color를 변수로 뽑았으니까 MessageRequest를 생성할 때 뽑은 변수를 쓰면 좋을 것 같아요!

2022-07-27 07:53 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
>                  .getId();
command + F6으로 파라미터 순서 변경 단축키 썼더니 놓쳐버렸네요ㅋㅋ
수정했습니다.

2022-07-28 02:14 UTC, asebn1 requested changes
flyway, REST Docs 적용 후 머지하겠습니다!

2022-07-29 10:28 UTC, asebn1 approved these changes
수고하셨습니다!

2022-07-29 10:34 UTC, merged