feat: 전체 모임 조회 시, 페이징 기법을 추가한다.
woowacourse-teams/2022-nae-pyeon pull request #195
Opened 2022-07-27 14:00 UTC by kth990303

close #192 

혹시 몰라서 키워드 및 페이징 기법이 포함되지 않은 `findAll` 전체조회 메서드도 일단은 삭제하지 않았습니다.
페이징 기법 처음으로 시도해봐서 서툰 부분이 있을 수 있으니 꼼꼼히 리뷰 부탁드립니다~!

2022-07-28 13:12 UTC, Seungpang approved these changes
케이 구현해주신 내용 잘봤습니다! 덕분에 페이징 기법에 대해서 공부했어요
일단은 큰 문제가 없어보여서 approve 드리겠습니다. 
코멘트 남겼으니 확인해보세요! 😄

2022-07-29 01:47 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
>      public ResponseEntity<TeamsResponseDto> getAllTeams(
좋네요! 수정했습니다.

2022-07-29 01:59 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/TeamAcceptanceTest.java
> +                모든_모임_조회(tokenResponseDto, pageSizeRequest, 0, "내편");
두 가지 사항 모두 수정했습니다!
페이지 시작을 1-index base로 하는 부분은 아래와 같이 수정했는데 괜찮은지 모르겠네요.
```java
final int currentPage = page - 1;
final PageRequest pageRequest = PageRequest.of(currentPage, pageSizeRequest.getSize());
return ResponseEntity.ok(
        teamService.findTeamsByContainingTeamName(keyword, loginMemberRequest.getId(), pageRequest)
);
```

2022-07-29 07:27 UTC, yxxnghwan requested changes
안녕하세요 케이!
페이징 잘 구현해주셨네요! Spring Data JPA에서 제공하는 기능들을 잘 활용해주신 것 같아요!
다만 프로젝트 초기에 Service에서 Spring Data JPA에 대한 직접적인 의존을 피하려고 저희의 Repository계층을 추상화해서 적용시키고 JpaRepository들을 구현체로 만드는 컨벤션을 정의했었는데요!
페이징을 구현하면서 의존이 생겼네요! Repository계층 안에서 의존을 끊고 서비스로 데이터를 넘겨줄 방법을 고민해보면 좋을 것 같아요!

2022-07-29 07:27 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
> +            @RequestBody final PageSizeRequest pageSizeRequest) {
`GET`메서드에 body로 pageSize 정보를 받고 있네요..! GET 메서드에서는 body를 가지지 않게 하는게 권장되는 걸로 알고 있어요! API명세 보니까 body로 받게 되어있긴 한데 다같이 명세를 수정하는 게 좋을 것 같습니다!

2022-07-29 07:27 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
> +        final Page<Team> teams = teamRepository.findTeamsByContainingTeamName(keyword, pageRequest);
Spring Data JPA에 의존적인 타입들을 Service에서 사용하고 있는 것 같아요.
의존을 끊어내기 위해 정의했던 Repository 계층에서 끊고 나오는 것은 어떨까요?

2022-07-29 07:27 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/repository/TeamRepositoryTest.java
> +        final Team team1 = new Team("woowacourse", "it's a.", "testEmoji", "#123456");
테스트 👍

2022-07-30 08:13 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
> +            @RequestBody final PageSizeRequest pageSizeRequest) {
수정된 명세 (모두 queryParam) 반영했습니다!

2022-07-30 08:20 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
> +        final Page<Team> teams = teamRepository.findTeamsByContainingTeamName(keyword, pageRequest);
타입이 `Page`인 점을 지적해주신 게 맞을까요? `Page`는 하나의 도메인으로써, teams에 대한 정보들을 가지고 있어 응답 DTO에 데이터의 전체 개수, 페이지 정보 등을 담기 위해 필요한 부분이라 위와 같이 적용했습니다. `Page`가 아닌 요청에서 요구한 만큼의 사이즈의`List`를 반환한다면 전체 데이터 개수 및 페이징 정보를 DTO에 담을 수 없을 것 같아요.

혹시 제가 코멘트를 잘못 이해한거라면 추가 코멘트 부탁드릴게요!

2022-08-01 04:48 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/TeamService.java
> +        final Page<Team> teams = teamRepository.findTeamsByContainingTeamName(keyword, pageRequest);
응답 타입이 Page인 것과 Service에서 Pageable을 파라미터로 받고 있어요! 해당 타입들이 인프라스트럭쳐 계층의 타입들이기 때문에 응용 서비스 계층과 표현 계층에 들어와있는 구조가 초기 계층간 의존을 끊기로 해서 Repository계층을 새로 정의한 것과 반대되고 있는 것 같아요! 응용 서비스 계층에서 쓰이는 DTO를 정의해서 Repository에서 해당 DTO로 반환하는 건 어떨까요?

2022-08-01 04:56 UTC, yxxnghwan approved these changes
수고하셨습니다 케이!
일단은 프로젝트를 진행시켜야 하니 머지하고 계층간 의존에 대해선 디스커션을 남겼으니 의논 후 같이 코드 변경해보기로 해요! #233

2022-08-01 04:57 UTC, kth990303 commented
이슈 #192  #36도 같이 참고하시면 좋을 거 같습니다!

2022-08-01 05:28 UTC, asebn1 approved these changes
페이징 공부를 이번기회에 할 수 있었네요! Pageable 인터페이스와 PageRequest구현체, PageRequest를 스프링 데이터 레포에 같이 넣어주면 Page로 반환해주는것까지 많이 배울 수 있었습니다!

2022-08-01 05:28 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
> +        final Pageable pageRequest = PageRequest.of(currentPage, count);
바로 PageRequest로 받는 방법으로 진행하는 건 어떤가요?
https://galid1.tistory.com/769

2022-08-01 05:28 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
> +
쿼리안에 pageRequest에 관한 정보가 사용되지 않아도 반영이되나요? 궁금하네요!

2022-08-01 11:09 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/TeamParticipationJpaDao.java
> +
통과하는 걸 확인했습니다!
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/57135043/182135506-a70fdecd-cb15-42e6-a5a9-98e62d14686c.png">

2022-08-01 11:10 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/TeamController.java
> +        final Pageable pageRequest = PageRequest.of(currentPage, count);
현재 `currentPage = page - 1`의 요청값 처리 로직이 들어가야 해서, `PageRequest`로 요청을 받고, 다시 값을 꺼낸 다음에 다시 `PageRequest`로 넣을 필요가 없다고 생각해서 패스하려고 합니다!

2022-08-02 01:13 UTC, Seungpang commented
Can one of the admins verify this patch?

2022-08-02 06:11 UTC, merged