feat: 전체 팀 검색 기능 구현
woowacourse-teams/2022-nae-pyeon pull request #218
Opened 2022-07-30 10:03 UTC by prefer2

## 구현 사항
- 초기 진입시 전체 모임 무한 스크롤 가능하도록 구현
- 검색어 입력 시 검색 결과 무한 스크롤로 보여주기

closed #199

2022-07-30 13:52 UTC, soyi47 requested changes
useInfiniteQuery와 IntersectionObserver 둘다 아번 프로젝트에서 처음 써보는데, 
맡아서 적용한다고 고생했습니다! 덕분에 어떤 친구들인지 훑어볼 수 있었어요~👍
코멘트 확인하고 의견 주세요!

2022-07-30 13:52 UTC, soyi47 commented on frontend/src/pages/TeamSearchPage.tsx
> +  );
intersectionObserver를 이번에 처음 써보게 되어서 잘 모르겠는 부분들이 있어요~

options로 들어온 조건에 해당하면 useIntersect의 callback이 실행되는 것으로 이해했는데요!
1. callback 안에서 첫 번째 인자인 onIntersect를 실행시키네요. onIntersect 내에서 `observer.unobserve(entry.target)`는 왜 필요한가요?
2. unobserver 후에 fetchNextPage가 호출되고 나면, 다시 observer.observe()가 호출되어야 infinite scroll이 잘 동작할 것 같아요. useIntersect 내의 useEffect에서 observer.observe()가 호출되고 있는데, 어떤 시점에 useEffect가 실행되는지 설명해줄 수 있나요? fetchNextPage 호출 후에 useIntersect 내의 useEffect의 의존성 배열의 값이 영향을 받는 상황이 언제 왜 생기는지 궁금합니다. - 요건 저도 조금 더 고민하면서 뜯어볼게요.

2022-07-30 13:52 UTC, soyi47 commented on frontend/src/pages/TeamSearchPage.tsx
> +      }
다음 페이지가 없을 때 `undefined`를 반환해주면 좋겠어요~
[useInfiniteQuery 문서](https://tanstack.com/query/v4/docs/reference/useInfiniteQuery?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/useInfiniteQuery)에서, 유효한 다음 페이지가 없는 경우 `undefined`를 반환하라고 하네요.

2022-07-30 13:52 UTC, soyi47 commented on frontend/src/pages/TeamSearchPage.tsx
> +        {totalTeamResponse.pages.map((group, i) =>
두번째 i는 사용하지 않는군요! 지워줍시다~

2022-07-30 13:52 UTC, soyi47 commented on frontend/src/pages/TeamSearchPage.tsx
> +          group.teams.map((team: Team) => (
group 표현보다는,,, pages 배열 내의 하나의 요소, 페이지 단위로 가져온 데이터니까 page라는 이름은 어떤가요?
다른 표현이더라도 페이지 단위로 가져온 데이터라는 의미가 더 잘 드러나면 좋을 것 같아요.

2022-07-30 13:54 UTC, prefer2 commented on frontend/src/hooks/useIntersect.tsx
> +) => {
교차함에 따라 함수 실행을 하는 훅이라 intersect(교차하다)로 지었습니다... 홀홀

2022-07-31 03:45 UTC, prefer2 commented on frontend/src/pages/TeamSearchPage.tsx
> +      }
오 그렇군요 꼼꼼한 리뷰 감사합니다

2022-07-31 05:23 UTC, soyi47 commented
고생했어요~ useIntersect에 대한 코멘트만 남겨주세요~ 일정 상 머지합니다!

2022-07-31 05:23 UTC, merged

2022-07-31 16:03 UTC, prefer2 commented on frontend/src/pages/TeamSearchPage.tsx
> +  );
![infinteQuery](https://user-images.githubusercontent.com/67692759/182035104-09d095b4-ecc3-4c4a-8c65-fc2b3b64f48b.png)