feat: 팀 상세보기 페이지 더보기 구현
woowacourse-teams/2022-nae-pyeon pull request #236
Opened 2022-08-01 07:57 UTC by prefer2

## 구현 사항
- 더보기 버튼 + dropdown 컴포넌트 구현
- 닉네임 수정 로직 추가

refetch의 사용법을 알게 되어 리프레쉬 없이 값을 다시 가져오는 방법을 사용해보았습니다. UI만 하려고 했는데 하다보니 로직까지 다 추가해서 구현하게 되었습니다. TeamJoinModal 부분이 많이 부족할 것 같아 이 점 유의해서 리뷰해주시면 좋을 것 같습니다.

2022-08-01 13:52 UTC, soyi47 requested changes
도리~ 모달을 portal로 잘 옮겨줬네요. 고생했습니다! 👍

몇 가지 에러와 수정 필요한 부분들 발견해서 코멘트 남겼습니다.


1. TeamNicknameModalForm에서 모임 가입과 닉네임 수정을 모두 담당하고 있는데요.
TeamProfileEditForm과 TeamJoinForm 컴포넌트를 분리하면 어떨까요?
mode라는 prop으로 submit 로직과 렌더링 로직에서 분기하는 것보다, 두 컴포넌트를 분리하는 게 코드 읽기가 더 수월할 것 같습니다. 도리 의견 궁금해요~
2. 모임 추가 설정 메뉴 버튼 위치 조금만 더 위로 옮기면 좋을 것 같아요!
3. 모달 우측 상단 x 버튼에 닫기 이벤트가 실행이 안 됩니다. 이건 코멘트로 잘못된 코드 위치 찾아서 남겨뒀어요.
4. 모임 가입 모달 또는 닉네임 모달에서 input에 autofocus 주면 좋을 것 같습니다!
5. dropdown 메뉴 hover 스타일링 있으면 좋겠어요~


<img src="https://user-images.githubusercontent.com/71116429/182162812-3df0af8f-9771-4276-af3d-698a757ae617.png" width="300px"/>

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx
> +        queryClient.refetchQueries(["rollingpaperList"]);
develop 브랜치에 query key 업데이트가 있어서, 여기서 주는 query key 배열에도 수정이 필요할 것으로 보여요. develop branch rebase 받아서 한번 확인해주세요!

예) 지금 develop 브랜치의 TeamDetailPage에서는 `["team", teamId]`를 query key 배열로 주고 있어요!

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/components/MoreDropdown.tsx
> +      </IconButton>
요 부분만 컴포넌트로 작게 분리한다면? 아래 링크를 참고해서 네이밍 할 수 있을 것 같아요. 🧐
꼭 분리하라는 건 아니고,,, 참고자료로 남깁니다!

https://uxplanet.org/choose-correct-menu-icon-for-your-navigation-7ffc22df80ac

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/RollingpaperList.stories.jsx
> +import RollingpaperList from "@/pages/TeamDetailPage/components/RollingpaperList";
👍

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/App.tsx
> +export const queryClient = new QueryClient();
이 친구를 App에서 바로 export 하기보다는, 다른 파일에서 선언하고 export하는 게 좋겠어요.

1. queryClient를 `api/index.ts`로 옮기고, 
2. `api/index.ts`에서 선언해서 쓰는 axios instance인 appClient를 axiosInstance라는 이름으로 바꾸면 어떨까요?

네이밍이나 선언 위치에 대해서 의견 있으면 제안해주세요~ 😄

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/components/MoreDropdown.tsx
> +};
MoreDropdown이라는 이름에서 More이란 표현을 빼고 DropDown이라고만 해도 될 것 같은데, More을 넣어준 이유가 있나요? MoreDropdown이라는 표현이 좀 어색하게 느껴져서요!

내부에서 StyledDropDown이 있어서 DropDown이라는 표현을 중복해서 쓰기가 불편했다면,
1. 해당 컴포넌트를 DropDown이라고 네이밍하고,
2. 내부의 StyledDropdown -> StyledDropdownMenu
3. 내부의 StyledOption -> StyledOption or StyledDropdownItem (이건 StyledOption도 괜찮은 듯?)

위와 같이 수정해봐도 좋을 것 같아요.

bootstrap에서는 클래스 네이밍을 위와 같은 방식으로 했네요.
https://getbootstrap.com/docs/4.0/components/dropdowns/

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx
> +    },
useMutation에 들어갈 api 요청 로직을 api 폴더 하위에 분리해볼까요~?
아래에 editTeamNickname도 마찬가지~

2022-08-01 13:52 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/TeamNicknameModalForm.tsx
> +    <Modal onClickCloseButton={() => onClickCloseButton}>
모달 우측 상단 x 버튼 클릭 이벤트가 안 되네요. 코드가 잘못 작성되었어요~

2022-08-02 01:21 UTC, Seungpang commented
Can one of the admins verify this patch?

2022-08-02 01:31 UTC, prefer2 commented on frontend/src/components/MoreDropdown.tsx
> +};
특정한 버튼(more)버튼을 누를때만 사용되는 컴포넌트라 이렇게 이름을 지었네요. 그냥 드롭다운으로 네이밍을 하려면 button 컴포넌트도 따로 받아야 할 것 같아요.

2022-08-02 04:07 UTC, prefer2 commented on frontend/src/components/MoreDropdown.tsx
> +      </IconButton>
햄버거... 케밥... 미트볼... 이름 다 귀엽네요

2022-08-02 05:34 UTC, soyi47 requested changes
일정상 api 요청 로직 분리는 다른 이슈에서 진행해봅시다.

컴포넌트 이름 수정이랑 export 방식 변경 관련해서 코멘트 추가로 남겼어요.
수정하고 말씀해주시면 바로 merge 하겠습니다~!

2022-08-02 05:34 UTC, soyi47 commented on frontend/src/api/index.ts
>  export default appClient;
appClient를 default로 export 할 이유가 없다면 둘 다 그냥 export 하는 게 좋을 것 같아요.

2022-08-02 05:34 UTC, soyi47 commented on frontend/src/components/Dropdown.tsx
> +const MoreDropdown = ({ DropdownButton, optionList }: MoreDropdownProp) => {
1. 파일명은 Dropdown으로 변경되었는데 컴포넌트 이름은 MoreDropdown이네요. 확인 부탁해요~
2. DropdownButton prop 이름은 같이 조금 더 고민해봅시다... ㅠㅠ

2022-08-02 06:12 UTC, prefer2 commented on frontend/src/api/index.ts
>  export default appClient;
소피아와 상의가 필요한 부분인 것 같아 우선은 넘어갔습니다. 수정하는 김에 다 수정해서 올리겠습니다.

2022-08-02 08:17 UTC, merged