feat: oauth 회원가입 로그인 구현 및 api 변경
woowacourse-teams/2022-nae-pyeon pull request #240
Opened 2022-08-01 14:27 UTC by yxxnghwan

회원가입 로그인 바꾸니까 테스트도 다 바꿔야했네요 ㅠ
변경한 부분이 많으니 꼼꼼히 리뷰 부탁드려요!🥔

close #201

2022-08-01 14:27 UTC, Seungpang commented
Can one of the admins verify this patch?

2022-08-02 01:14 UTC, kth990303 commented
fork한 레포로 PR을 올려서 테스트나 실행을 해보기 어렵다는 단점이 있네요 ㅜㅜ

2022-08-02 01:29 UTC, kth990303 requested changes
알렉스 정말 고생하셨습니다!
전체적인 AcceptanceFixture 쪽 회원가입 및 로그인을 수정해주셨기 때문에 이 PR을 최우선으로 머지하는 것이 좋을 것 같긴 하네요.
회원 쪽 도메인 필드 검증 쪽에 몇 가지 코멘트 달았는데 확인 부탁드립니다!

2022-08-02 01:29 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
>      public static final int MIN_USERNAME_LENGTH = 2;
유저네임이 1~20자로 변경된 것으로 아는데, 이 부분 변경이 없네요!

2022-08-02 01:29 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
> +    private Long platformId;
`nullable=false`가 없어도 괜찮을까요?

2022-08-02 01:29 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
>      private static final Pattern USER_PATTERN = Pattern.compile("^[가-힣a-zA-Z0-9]+$");
유저명 이제 영어, 한글, 숫자 외에 다른 문자도 가능하게 할 것 같아서 REGEX가 필요없을 것 같아요!
추가로 3005번 에러코드 삭제 및 그 외 회원 관련 에러명세도 바뀌어야 될 것 같아요.

2022-08-02 01:29 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/LoginAcceptanceTest.java
>      @DisplayName("로그인에 성공하면 토큰을 발급한다.")
개인적으로는 로그인에 실패하는 경우도 있으면 좋을 것 같은데 어떻게 생각하시나요?

2022-08-02 01:29 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/domain/MemberTest.java
>      }
이 부분도 없어도 될 것 같아요!

2022-08-02 01:29 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/repository/MessageRepositoryTest.java
> +    private static final String content = "안녕하세요😁";
이모지 추가해서 꼼꼼한 테스트가 됐네요! 👍

2022-08-02 01:29 UTC, kth990303 commented on backend/src/main/resources/application-localh2.yml
> +    baseline-on-migrate: true
로컬에서는 flyway를 해제한 이유가 무엇인지 궁금해요! 로컬에서 테스트가 돌아가야 실제 배포 환경에서도 제대로 돌아가는지 테스트가 되지 않을까 싶어서 해제하지 않는 게 좋아보이는데, 이유가 있을 것 같아 질문드립니다!

2022-08-02 01:29 UTC, kth990303 commented on backend/src/main/resources/application.yml
> +#    driver-class-name: com.mysql.cj.jdbc.Driver
로컬 mysql을 사용하지 않고 도커를 사용하기 위해 설정해주신 건가요?

2022-08-02 02:04 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
>      public static final int MIN_USERNAME_LENGTH = 2;
유저네임 규칙 변경된걸 코드에 반영 안시켰네요! 다시 반영해서 올렸습니다!

2022-08-02 02:23 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
> +    private Long platformId;
넵! null 막아야할 것 같아서 수정했습니다!

2022-08-02 02:27 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/LoginAcceptanceTest.java
>      @DisplayName("로그인에 성공하면 토큰을 발급한다.")
oauth 인증 후에 얻은 사용자 요청 정보로 로그인을 요청하는데 해당 계정이 접근한 적이 있는 경우 바로 그 계정으로 매핑해서 로그인시켜주고, 접근한 적이 없는 경우는 자동으로 회원가입 이후에 매핑해서 로그인시켜주기 때문에 로그인 실패에 대한 시나리오를 작성하기가 애매한 것 같아요! oauth인증이 성공했다면 반드시 성공하는 기능이라 테스트 작성이 애매해서 일단은 빼고 작성했습니다!

2022-08-02 02:29 UTC, yxxnghwan commented on backend/src/main/resources/application-localh2.yml
> +    baseline-on-migrate: true
로컬에서는 컬럼의 변경이 자주 일어나기 때문에 jpa의 `ddl-auto: create`기능을 이용하는게 생산성에서 큰 장점을 가진다고 생각했어요!
플라이웨이는 해당 옵션과 같이 사용할 수 없어서 로컬 개발단계에서는 false설정이 좋을 것 같습니다!
이후 운영 환경에 배포시에만 플라이웨이 테스트를 위해서 켜두고 실행시켜본 이후에 main브랜치에 머지시키는 방식으로 하면 개발 생산성 저하도 최소화하면서 플라이웨이의 DB 변경 관리 장점도 가져갈 수 있을 것 같아요!

2022-08-02 02:30 UTC, yxxnghwan commented on backend/src/main/resources/application.yml
> +#    driver-class-name: com.mysql.cj.jdbc.Driver
로컬에선 개발 편의성을 위해 h2 인메모리DB를 사용합니다!

2022-08-02 04:36 UTC, kth990303 requested changes
조금 더 코멘트남겼어요!

2022-08-02 04:36 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
> +    private Platform platform;
`username` 의 `@Column` 어노테이션에 길이가 20으로 돼있어요! 64로 바꿔줘야될 것 같네요

2022-08-02 04:36 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidLoginException.java
> +                "존재하지 않는 유저의 토큰입니다. 다시 로그인해주세요.",
토큰이라는 말이 사용자 입장에서 친화적인지 의문이 드네요. `아이디 또는 비밀번호를 확인해주세요!` 도 괜찮지 않을까 싶은데 어떤가요?

2022-08-02 04:38 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
테스트가 존재하지 않는데 이 테스트 클래스를 남겨둔 이유는 무엇인가요?
스프린트4 때 ADMIN이 추가될 때를 대비해서 남겨둔게 맞을까요?

2022-08-02 04:39 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
> +    private Platform platform;
수정했습니다!

2022-08-02 04:39 UTC, kth990303 approved these changes
잘못된 부분은 전부 수정된 것 같네요 정말 수고하셨습니다 😄 
approve 하겠습니다!

2022-08-02 04:41 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/exception/InvalidLoginException.java
> +                "존재하지 않는 유저의 토큰입니다. 다시 로그인해주세요.",
해당 예외가 발생하는 케이스가 프론트엔드에서 잘못된 JWT를 넘겨줬을 시에만 발생하기 때문에 토큰 관련 예외라고 생각했어요! 아이디와 비밀번호를 받지 않도록 변경되면서 제대로 로그인된 토큰인지 아닌지만 생각하면 된다고 생각합니다!

2022-08-02 05:00 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
테스트 작성 했습니다!

2022-08-02 05:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        ));
`TokenRequestDto` 필드에 대한 검증이 없다면, 악의적인 목적으로 postman을 통해 데이터를 넣어줄 때 바로 가입이 되지 않을까 싶네요 😢

2022-08-02 05:14 UTC, asebn1 approved these changes
수고하셨습니다~ 코멘트 확인 부탁드려요

2022-08-02 05:14 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        return new TokenResponseDto(accessToken, memberId);
검증 추가해야 할 것 같아요

2022-08-02 05:14 UTC, asebn1 commented on backend/src/main/resources/application-localh2.yml
> +    baseline-on-migrate: true
이걸 기본 application.yml로 해도 될 것 같아요!

2022-08-02 05:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        ));
그러게요.. 프론트에서 인가코드를 받아서 백엔드에서 사용자 정보를 요청하는 방식으로 변경해야겠네요..😢

2022-08-02 05:15 UTC, Seungpang approved these changes
앞서 케이가 리뷰한 내용은 따로 달지 않았습니다.
로그인이 변경되어서 많은 테스트코드가 변경 되었을 것 같은데
고생하셨습니다 👍
approve 하겠습니다.

2022-08-02 05:15 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +                Platform.valueOf(tokenRequestDto.getPlatformType()),
Platform에 없는 값으로 요청할 경우 그냥 자바 표준 예외인 IllegalArgumenException이 발생하는데 Platform에서 예외 검증을 위임 해볼 수 있을까요?

2022-08-02 05:16 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Member.java
> +    private String platformId;
겹칠 수 있을 거 같아서 `unique` 없이 지금처럼 하는 것이 좋을 거 같아요

2022-08-02 05:18 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +                Platform.valueOf(tokenRequestDto.getPlatformType()),
플랫폼마다 API 따로 요청하도록 바꿔야 할 것 같은데 그때 해결할 수 있을 것 같네요!

2022-08-02 05:19 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        return new TokenResponseDto(accessToken, memberId);
인가 코드를 받아서 직접 사용자 정보를 요청하는 방식으로 변경되면 검증없이 될 것 같네요!

2022-08-02 05:19 UTC, merged