feat: 메인 페이지에 Infinte scroll을 추가한다
woowacourse-teams/2022-nae-pyeon pull request #261
Opened 2022-08-02 12:07 UTC by prefer2

## 구현 사항
- 명세에 맞도록 내 모임 가져오기 mocking 수정
- 메인 페이지에 infinte scroll 추가

closed #258

2022-08-02 12:07 UTC, Seungpang commented
Can one of the admins verify this patch?

2022-08-02 13:26 UTC, soyi47 requested changes
도리~ 
API mocking을 잘 해주어서 더미 데이터 추가하면서 테스트해보기 편했어요! 🥰

소소한 코멘트 남겼으니 확인하고 답변 남겨주세요!

2022-08-02 13:26 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +  };
1. GET 요청이니, getMyTeams 라는 이름으로 변경하면 어떨까요?
2. api 폴더로 파일 분리해도 좋을 것 같아요. 그렇게 되면 count도 인자로 받도록 수정해야 할 것 같네요.

2022-08-02 13:26 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +  } = useInfiniteQuery(["projects"], fetchMyTeams, {
query key 배열에 "projects"라는 값을 준 이유가 있나요~?

2022-08-02 13:26 UTC, soyi47 commented on frontend/src/mocks/handlers/teamHandlers.js
>      };
꼼꼼한 mocking 👍

2022-08-03 04:48 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +  };
1. 엇 기존에도 이렇게 작성하고 있어서(searchTeams) 이런식으로 작성했네요. 기존 파일과 함께 수정할께요
2. 분리했습니당

2022-08-03 04:49 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +  } = useInfiniteQuery(["projects"], fetchMyTeams, {
이런걸 잘 확인해야하는데 꼼꼼하지 못했네요. my-teams로 변경했습니다

2022-08-03 05:21 UTC, soyi47 approved these changes
수정 확인했습니다~ 👍

2022-08-03 05:34 UTC, merged