feat: 메인 페이지의 가입한 모임 목록 empty state UI 추가
woowacourse-teams/2022-nae-pyeon pull request #265
Opened 2022-08-02 13:54 UTC by prefer2

## 구현 사항
- 참가한 모임이 없을 시 empty state UI를 보여준다

![스크린샷 2022-08-02 오후 10 52 55](https://user-images.githubusercontent.com/67692759/182391764-4ba1a62d-80a8-425b-b19f-8f9a57112bc2.png)

close #228

2022-08-02 13:54 UTC, Seungpang commented
Can one of the admins verify this patch?

2022-08-02 13:55 UTC, soyi47 requested changes
1. 어디 empty state UI인지 PR 제목 명시해주시고
2. PR 메시지에 closed 이슈 번호 추가해주세요!

코드는 곧 보겠습니당.

2022-08-03 04:49 UTC, soyi47 requested changes
도리~ 가입한 모임 목록 empty state UI 너무 귀엽네요! 최고최고 🤗

새 모임 만들기 버튼 이벤트에 오류가 있어서 코멘트 남겨뒀습니다. 수정 부탁해요!
나머지 코멘트는 소소합니다~ 확인해주세요! 🥰

2022-08-03 04:49 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      <StyledFirstTeam>
StyledFirstTeam의 FirstTeam이 어떤 의미인지 설명해주실 수 있나요~?

2022-08-03 04:49 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +        </LineButton>
모임 만들기 페이지가 아니라 모임 검색 페이지로 이동하네요! 수정 부탁해요~

2022-08-03 04:49 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +    );
1. EmptyMyTeamList 같은 이름으로 컴포넌트와 파일 분리해줘도 좋을 것 같아요.
2. StyledMain이 지금 전체 페이지 껍데기 역할이라면, empty state ui도 StyledMain 안에 작성되는 게 더 일관성 있겠다는 생각도 드네요. 
혹은 empty state ui가 꼭 StyledMain으로 감싸져있지 않더라도, main 태그로 감싸주는 정도의 일관성만 있어도 좋을 것 같아요. 그러려면 StyledFirstTeam을 main 태그로 바꾸면 충분할 것으로 보입니다. 도리 생각은 어떤가요~?

2022-08-03 04:51 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +      <StyledFirstTeam>
초기 팀을 가입시키는것을 도와준다... 라는 의미해서 네이밍했는데 애매한 것 같네요.

2022-08-03 05:02 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +    );
1. EmpytMyTeamList는 뭔가 아쉬워서 EmptyState 컴포넌트 작성했습니다
2. 그렇네요. 네이밍 변경하고 tag main으로 변경했습니다

2022-08-03 05:32 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +    );
컴포넌트 이름에 '무엇이' 빈 값인지에 대한 정보가 없어도 괜찮을까요?
저는 '무엇이' 빈 값일 때 보여줄 컴포넌트인지, 이름에서부터 알려주는 게 더 친절하다고 생각합니다.
어떤 점에서 EmptyMyTeamList가 아쉽다고 느껴졌는지 자세히 이야기해줄 수 있을까요? 

지금 MainPage에서는 내 모임 목록만 보여주는 상황이고, 
그 상황이 쉽게 파악되기 때문에 MainPage 내의 EmptyState라고만 네이밍해도 충분하다는 의견이라면 거기에도 공감하고요!

이름을 꼭 'EmptyMyTeamList'로 수정하자는 것은 아니에요~
도리 의견이 궁금합니당!

2022-08-03 05:50 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +    );
저는 이미 메인 페이지에 있기 때문에 우선은 emptyState로만 넣었어요. 페이지에서 보여줄 것이 없는 경우에만 보여주는 경우이라서요. 다시 보니 emptyTeamList도 좋은 네이밍인 것 같네요. 사실 처응에 봤을 때 무슨 컴포넌트인지 저는 잘 모르겠어서 애매하다고 했어요( 컴포넌트만 보고 생각했는데 코드로 .legth === 0일때 실행하는 코드이니 알아보기 좋은 것 같네요) 제가 네이밍을 너무 신경을 안쓰는 건가 싶네요 반성합니다.

2022-08-03 06:01 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +    );
구구절절 설명을 더했을 때, 명료함이 떨어지게 되고 가독성을 해칠 수도 있다는 의견에 공감합니다. 💕
그런 점에서 저도 이름이 너무 길어지는 건 싫지만! 
긴 네이밍의 단점보다 의미가 더 잘 전달되는 장점이 크다면 이름이 좀 길어도 감수하는 편이에요..!
앞으로 좋은 네이밍에 대해 계속 같이 고민해봐요 🥰

2022-08-03 06:42 UTC, merged