feat: MessageForm 컴포넌트의 작성 취소 아이콘을 변경하고 수정시 글자수가 나오도록 수정
woowacourse-teams/2022-nae-pyeon pull request #268
Opened 2022-08-03 05:44 UTC by prefer2

## 구현 사항
- 메시지 작성 취소 아이콘은 x로 변경한다
- 작성하는 글자수가 보일 수 있도록 한다

2022-08-03 11:22 UTC, soyi47 approved these changes
도리 의견 궁금한 부분 코멘트 남깁니다!

수정 요청은 없어요. Approve 합니다. 답변 남겨주시면 merge 할게요~

2022-08-03 11:33 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
toString을 하지 않으면 textArea의 타입을 가져와 쓰다보니 (parameter) value: string | number | readonly string[] | undefined 타입이라 toString을 붙여주었어요. string이라는 것이 확실하다보니 따로 에러 처리는 없어도 되지 않을까 싶어요.

2022-08-03 11:39 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
제가 이야기한 부분은 지금 `value?` optional chaining 부분인데요!
value가 undefined인 경우  `value?.toString()`이 undefined가 되기 때문에, `value?.toString().length`는 undefined | number 타입일 것으로 파악했어요. 제가 잘못 파악한 걸까요? 🤔

2022-08-03 11:49 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
저는 이 부분을 막고 싶다면 오히려 textArea의 prop을 그대로 가져다 쓰는 것이 아니라 vlaue의 값을 string으로 정해주는 것이 맞지 않을까 생각합니다. 윗단에서 string으로 이미 지정했는데 아래쪽에서 오히려 너무 다양한 값을 받아들일 수 있어서 발생하는 문제라고 생각하거든요.

2022-08-03 11:57 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
컴포넌트를 독립적으로 생각한다면 사실 방어를 여기서 해주는 것이 맞을 것 같네요.

2022-08-03 11:57 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
그렇다면 TextArea 컴포넌트에서 받는 value prop의 타입을 string으로 정해주는 방향으로 수정해볼까요~?

2022-08-04 03:08 UTC, soyi47 requested changes
타입 추가 확인했습니다. 👍
수정 제안 코멘트 하나 있으니 확인해주세요!

2022-08-04 03:08 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +  value: string;
수정 확인! 👍

2022-08-04 03:08 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value?.toString().length}/500</StyledTextLength>
상단에서 타입을 string으로 줬으니 `{value.length}`로 수정하면 어떨까요?

```suggestion
      <StyledTextLength>{value.length}/500</StyledTextLength>
```

2022-08-04 03:12 UTC, soyi47 approved these changes
고생했어요! 머지하겠습니다! 🥰

2022-08-04 03:12 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageTextArea.tsx
> +      <StyledTextLength>{value.length}/500</StyledTextLength>
확인 완료! 👍

2022-08-04 03:13 UTC, merged