feat: 초대 링크 리다이렉트 페이지와 비공개 모임 추가 UI를 구현
woowacourse-teams/2022-nae-pyeon pull request #325
Opened 2022-08-10 04:03 UTC by prefer2

## 구현 사항
- 모임 생성 시 비공개 모임 선택 토글 추가
- 초대링크를 통해 들어올 시 redirect할 페이지 추가

### 의논할 사항
- 컴포넌트의 비즈니스 로직을 최대한 다 훅으로 빼고 싶어 이번에 컴포넌트를 만들때도 훅으로 빼 보았습니다. 앞으로 이렇게 훅으로 빼는건 어떨지 소피아의 의견이 궁금해요
- 리다이렉트 페이지가 조금 심심한 것 같기도 하고 수정할만한 사항 있으면 알려주시와요

![ezgif com-gif-maker](https://user-images.githubusercontent.com/67692759/183809890-fc38f1d2-0de8-4e3c-b63c-19ab209edc62.gif)
![스크린샷 2022-08-10 오후 12 59 04](https://user-images.githubusercontent.com/67692759/183809946-d0c5fe9c-f666-418e-a4c9-55c727dc1c11.png)

closed #322

2022-08-10 05:57 UTC, soyi47 requested changes
도리~ 잘 해줬네요~ 👍👍👍

지금 UI에 대한 제 의견과 같이 논의해보면 좋을 부분들 코멘트로 남겼으니 확인하시고 답변 달아주세요~


**1. 브라우저에서 봤을 때, 비공개로 만들기 안내 문구가 많이 작아보여요.** 
지금 각 라벨이 14px, 비공개로 만들기 안내 문구가 12px인데 태블릿, 브라우저 사이즈에서는 2px씩 키우는 건 어떤가요?
<image src="https://user-images.githubusercontent.com/71116429/183825719-1f8723b2-c822-475f-9c21-430c0c9f01b0.png" width="500px" />

**2. 설명 박스 상단에 여백이 조금 더 있으면 좋겠어요. (모바일이랑 브라우저 사이즈 둘 다!)**
<img width="328" alt="캡처1" src="https://user-images.githubusercontent.com/71116429/183825970-f16a0ba6-f301-44eb-aadc-3920b1834983.PNG">

2022-08-10 05:57 UTC, soyi47 commented on frontend/src/App.tsx
> +            <Route path="invite" element={<InvitePage />} />
지금 RequireLogout 안에 InvitePage가 들어있는데, 다음과 같은 사용자 흐름이 필요할 것 같아요.

- 로그인한 유저가 초대 링크 접근 시, 
-> 바로 InvitePage 접근 가능

- 로그인 안 한 유저가 초대 링크 접근 시, 
-> 로그인 페이지 보여주기 -> 로그인 성공 후 -> InvitePage로 이동

<br >

초대 링크에 접근했을 때 어떤 사용자 플로우가 있으면 좋을지 도리 의견 궁금합니다.

_이 부분은 이번에 꼭 수정, 반영이 필요하다는 건 아니고요._
UI의 범위에 페이지 이동까지 포함된다고 생각하면,,, 이번 PR에서 반영해봐도 좋을 것 같고, 
다른 이슈로 나눠서 작업해도 좋을 것 같아요!

2022-08-10 05:57 UTC, soyi47 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
1. TeamDetailPage의 TeamDescriptBox랑 다른 컴포넌트 구조로 작성되었는데 이유가 있나요?
이전에는 StyledEmoji, StyledTitle, StyledDescription으로 나누지 않고 그냥 h3, p 태그를 안에 포함시켰거든요.
사용되는 상황이 다르니 지금처럼 두 컴포넌트가 분리되는 건 필요할 것 같아요.
다만 스타일이 거의 똑같은 상황이라 지금 작성해준 컴포넌트 분리 방식으로 TeamDetailPage의 TeamDescriptBox를 수정하면 일관성있고 더 깔끔할 것 같다는 생각이 드네요.

2. TeamDescription이랑 TeamDescriptionBox랑 어떤 이름이 더 나을까요?

2022-08-10 05:57 UTC, soyi47 commented on frontend/src/pages/TeamCreationPage/components/LabeledToggle.stories.jsx
> +};
스토리북까지 잘 챙겨줬네요 👍👍👍

2022-08-10 05:57 UTC, soyi47 commented on frontend/src/pages/TeamCreationPage/components/LabeledToggle.tsx
> +      </StyledMessage>
밖에서 StyledMessage로 감싸고 있는데, 
'이 작업은 실행 취소할 수 없습니다.' 문장을 StyledMessage로 한번 더 감싸고 있네요. 이 태그는 지워도 될 것 같아요.

2022-08-10 05:57 UTC, soyi47 commented on frontend/src/pages/TeamCreationPage/index.tsx
> +          onClickToggle={handleToggleClick}
이미 Toggle 이라는 표현이 컴포넌트 이름에 들어있으니, onClick이라고만 해도 충분할 것 같아요!

2022-08-10 06:15 UTC, prefer2 commented on frontend/src/pages/TeamCreationPage/components/LabeledToggle.tsx
> +      </StyledMessage>
두 문장 사이에 띄어쓰기를 주고 싶어서 넣었어요. 우선 백틱을 사용해서 띄어쓰기를 넣어보았습니다 [8087317](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/808731785c2490e61c1b7be86ed1db100ef13468) 혹시 다른 더 좋은 방법을 안다면 제안해주세요.

2022-08-10 06:16 UTC, prefer2 commented on frontend/src/pages/TeamCreationPage/index.tsx
> +          onClickToggle={handleToggleClick}
변경 완료 [6fdd262](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/6fdd262ef981a087e8650186e89a5504ac3892a5)

2022-08-10 06:24 UTC, prefer2 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
1. 이부분은 디자인적으로 논의해보고 싶었어요. 까먹고 pr에 안적었네요. 랜덤한 사용자에게 사용해보라고 제안했을때 아래 사진처럼 애매하게 띄어지는 것보다 이모지는 따로하는 것이 좋을 것 같다는 의견을 들었어요. 따로 띄어서 두는 것이 좋을지, 아니면 기존의 방법을 지킬지에 대한 소피아의 의견이 궁금하네요. 
<img width="330" alt="스크린샷 2022-08-10 오후 3 18 35" src="https://user-images.githubusercontent.com/67692759/183829245-c32aa20f-87e4-42d4-ae90-0c2d9fbfb6fd.png">

2. 기존에는 Box를 넣었더라고요. 일관성 지켜주기 위해 이름 변경했습니다 d0a4e8e

2022-08-10 06:30 UTC, prefer2 commented on frontend/src/App.tsx
> +            <Route path="invite" element={<InvitePage />} />
이번에는 로직을 최대한 고민하지 않고 UI구현에만 집중했어요. 이 부분을 고민하려면 사실 로그인 안한 유저가 눌렀을때는 login페이지로 먼저 이동 -> invitePage로 이동해야 하기 때문에 소피아와의 상의가 필요하다고 생각했거든요. 
이걸 결정하려면 초대링크를 어떻게 생성할 것인지도 알아야하기도 하고요. 아직 초대링크 관련해서는 백분들이 말해주신 것도 없기도 하고, `링크`를 어떤 형식으로 만들지에 대한 상의가 전혀 없었기 때문에 지금 단계에서는 불가능하다고 생각합니다. 
우선은 UI확인을 위한 라우팅이라고 생각해주면 좋을 것 같아요.

2022-08-10 06:43 UTC, prefer2 commented
> 지금 각 라벨이 14px, 비공개로 만들기 안내 문구가 12px인데 태블릿, 브라우저 사이즈에서는 2px씩 키우는 건 어떤가요?
이 부분은 수정하고자 하면 팀 생성 페이지 뿐만 아니라 롤링페이퍼 생성 페이지도 수정해야한다고 생각하는데요 어떻게 생각하나요?
2. [7838530](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/783853099500dd8388eb0abce726a5d7bfe0885b)

2022-08-11 09:07 UTC, soyi47 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
1. 따로 띄워주는 것도 괜찮아보입니다. 그렇게 통일할까요?

2022-08-11 09:16 UTC, soyi47 commented on frontend/src/pages/TeamCreationPage/components/LabeledToggle.tsx
> +      </StyledMessage>
그런 이유가 있었군요. 백틱을 사용한 줄바꿈이 되는 줄 몰랐네요. 
StyeldMessage라는 컴포넌트에서 줄 바꿈을 인식하도록 css를 주거나... 
StyeldMessage 컴포넌트 말고 다른 컴포넌트를 정의해서 줄바꿈을 주는 방법도 있을 것 같아요. 
백틱을 넣은 상황을 유지해도 좋고, 다시 수정해봐도 좋을 것 같습니다.

2022-08-11 09:20 UTC, soyi47 commented on frontend/src/App.tsx
> +            <Route path="invite" element={<InvitePage />} />
좋아요. 기능 구현 전에 링크 형식과 라우팅 케이스(로그인 상태에 따라, 모임 가입 여부에 따라) 논의해봅시다. 👍

2022-08-11 09:22 UTC, soyi47 commented
> > 지금 각 라벨이 14px, 비공개로 만들기 안내 문구가 12px인데 태블릿, 브라우저 사이즈에서는 2px씩 키우는 건 어떤가요?
> 이 부분은 수정하고자 하면 팀 생성 페이지 뿐만 아니라 롤링페이퍼 생성 페이지도 수정해야한다고 생각하는데요 어떻게 생각하나요?

네~ 같이 수정되면 좋겠습니다~

2022-08-11 11:12 UTC, prefer2 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
<img width="569" alt="스크린샷 2022-08-11 오후 8 12 25" src="https://user-images.githubusercontent.com/67692759/184121008-62176f27-95f6-416e-afdb-617be12a9540.png">
해보니 별로네요. invatePage의 설명박스를 수정하는걸로 하겠습니다

2022-08-11 11:15 UTC, prefer2 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
한줄로 오도록 변경했습니다 [5c86f2f](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/5c86f2f4643021a40c37fef5d633eec974f46abb)
<img width="569" alt="스크린샷 2022-08-11 오후 8 14 51" src="https://user-images.githubusercontent.com/67692759/184121409-dd4ab27f-fca8-40be-9fa7-1d24f9012499.png">

2022-08-11 11:17 UTC, soyi47 commented on frontend/src/pages/InvitePage/components/TeamDescription.tsx
> +const StyledDescription = styled.div``;
zzzzㅋㅋㅋ귀여워ㅋㅋㅋ 좋습니다 👍

2022-08-11 11:21 UTC, prefer2 commented
[6873d74](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/6873d747fd12d05f90a4f295d68f18ee6b57a220) 수정 완료

> > > 지금 각 라벨이 14px, 비공개로 만들기 안내 문구가 12px인데 태블릿, 브라우저 사이즈에서는 2px씩 키우는 건 어떤가요?
> 
> > 이 부분은 수정하고자 하면 팀 생성 페이지 뿐만 아니라 롤링페이퍼 생성 페이지도 수정해야한다고 생각하는데요 어떻게 생각하나요?
> 
> 네~ 같이 수정되면 좋겠습니다~

2022-08-11 11:57 UTC, soyi47 approved these changes
기존에 없던 반응형 사이즈 분기가 추가되었네요!
이 부분 한번 의견 재점검만 할게요.
문제는 없어 보여서 Approve 합니다. 코멘트 주세요~

2022-08-11 11:57 UTC, soyi47 commented on frontend/src/components/AutoCompleteInput.tsx
> +  }
앗 기존에는 600px 이하를 모바일 사이즈로 관리했고, 400px 분기는 없었는데요.
이제 400px도 분기하는 건가요?!
순간 모바일이랑 태블릿 브라우저 전부 사이즈 커진 줄....!

개인적으론 400px 분기 한번 더 해도 좋을 것 같습니다. 
괜찮으시면 이렇게 가시죠 👍

2022-08-11 12:02 UTC, prefer2 commented on frontend/src/components/AutoCompleteInput.tsx
> +  }
분명히 복붙해서 쓴 것 같은데 왜 400px로 주었을까요,,,,???
컨벤션 맞추러 600px로 후딱 수정했습니다 [7dcc3a8](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/325/commits/7dcc3a8d3ce5869ea2424af45988673f3a6a271f)

2022-08-11 12:06 UTC, merged