feat: 컴포넌트의 비즈니스 로직을 커스텀훅으로 분리한다
woowacourse-teams/2022-nae-pyeon pull request #328
Opened 2022-08-10 05:17 UTC by prefer2

## 구현 사항
- useAutoCompleteInput
  - 아이템 클릭 시 리스트 창이 닫히도록 변경
  - rest 사용으로 컴포넌트 단순하게 변경
- useInput
  - rest 사용으로 컴포넌트 단순하게 변경
- useDropdown
- useModal
- 팀 내 닉네임 설정(가입)/수정 폼 분리

### 의논 사항
- 최대한 비즈니스 로직을 hook으로 분리하는 것을 선호하는 편이라 리펙토링 하면서 커스텀 훅으로 분리할만한 것들을 분리해보았습니다. input같은 경우에 set~ 을 사용하여 아쉬웠던 점이 있는데 훅으로 분리하여 on~ 함수들로 조금은 깔끔해진 것 같습니다. 이런 훅들에 대한 소피아의 의견 궁금합니다

closed #326

2022-08-10 07:28 UTC, soyi47 requested changes
도리~ 변경 사항이 많았네요. 고생했습니다. ❤
훅으로 분리한 덕분에 코드 상에서 역할 분리가 명확해졌네요. 아주 좋아요! 👍

네이밍이나 컨벤션 관련해서, 
같이 기준 논의가 필요한 부분들 위주로 코멘트 남겼습니다. 


1. PR 제목을 '공통 컴포넌트'의 비즈니스 로직을 분리한다고 수정하는 건 어떨까요? 모든 컴포넌트의 로직을 커스텀훅으로 분리한 건 아니니 공통 컴포넌트라고 표현하면 좋겠습니다.
2. Paging 같은 경우는, page 상태처럼 handle 로직도 Paging 컴포넌트 외부에서 정의하여 prop으로 주도록 수정하고, 이후에 page 상태와 handle 로직을 만들어주는 커스텀 훅을 작성해보면 덜 복잡하게 작업할 수 있을 것 같아요.
3. `UnderlineInput`도 스타일만 다르고 LabeledInput과 같은 로직인 걸로 알고 있는데요. 이 친구는 수정이 안 된 것 같습니다. 수정이 필요한 게 맞다면 이번에 같이 수정되면 좋겠어요!
4. 이번에 `NicknameEditModalForm`, `NicknameCreateModalForm` 분리도 같이 진행된 것 같네요. 커스텀훅 작성과는 상관없는 분리인 걸로 보이는데, 이번처럼 변경사항이 많은 경우에는 다른 이슈에서 진행되었으면 좋았을 것 같습니다. ㅠㅠ 볼 파일들이 많아지니 초큼,, 정신이 없군요...
5. 커스텀 훅에서 반환하는 로직들은 onChange, onClick 같은 이름의 prop에 값으로 주어질 '핸들러 함수'라고 생각하는데요. 지금 이 로직들이 onChange, onClick 같은 표현이나 handle...change 같은 표현으로 혼용되어 작성된 것 같아요. 
**커스텀 훅에서 반환하는 로직의 이름은 `handle...click`, 이를 받아 쓰는 prop의 이름은 `onClick...`과 같은 방식으로 네이밍하면 어떨지 제안해봅니다.** 관련 코멘트 있으니 확인해주세요!

천천히 확인해주세요~ 👍

2022-08-10 07:38 UTC, prefer2 commented on frontend/src/components/AutoCompleteInput.tsx
>    height: 48px;
이건 왜 사라졌는지 모르겠네요...?!?!?!? 무서운 점은 제 코드에는 코드 공백이 살아 있다는 점....

2022-08-10 07:46 UTC, prefer2 commented on frontend/src/hooks/useAutoCompleteInput.tsx
> +
저 스스로도 이건 혼란했는지 뒤죽박죽으로 적었네요. type이 handler니 handle prefix붙이자는 의견 좋은 것 같아요!

2022-08-10 08:02 UTC, prefer2 commented on frontend/src/hooks/useAutoCompleteInput.tsx
> +
변경 완료! [c3c97d9](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/328/commits/c3c97d918d210d1ee4758e0b97b53e117fc72e4d)

2022-08-10 08:14 UTC, prefer2 commented on frontend/src/components/AutoCompleteInput.tsx
> +              onClick={onClick}
`onClick={onClick}` 맞춰주느라 typescript로 고생했는데 오히려좋아. 훨 명시적이고 좋은 것 같네요

2022-08-10 08:17 UTC, soyi47 commented on frontend/src/hooks/useAutoCompleteInput.tsx
> +  };
추가 설명
setValue에 들어갈 값을 innerText에 접근해서 받지 말구, 핸들러 함수가 setValue할 value값을 인자로 받도록, 고차 함수로 작성하면 어떻겠냐는 이야기입니다. 
1. 직접 innerText에 접근해야하는 점이 아쉽기도 하고, 
2. view로 보여주는 innerText 값과 로직에 값으로 사용할 value 값이 다를 수도 있기 때문에..!
```
(newValue) => (e) => { setValue(newValue); } 
```
이런 식으로!

2022-08-10 10:32 UTC, prefer2 commented
1. UnderlineInput은 빼먹고 적용하지 않았는데 덕분에 찾아가네요! 반영했습니다 [64fb8b4](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/328/commits/64fb8b4cee312405683f880671e1841eeede431a)
2. form분리하는건 의식의 흐름대로 하다보니... 다음부터는 이러지 않는걸루
3. 요 코멘트 관련해서는 다시 한 번 봐주세요! https://github.com/woowacourse-teams/2022-nae-pyeon/pull/328#discussion_r942065764

2022-08-10 11:36 UTC, prefer2 commented
usePaging 구현해서 적용해놓았습니다! [e48236c](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/328/commits/e48236c0974f763cb900248e9b2808755e992955)

2022-08-11 09:38 UTC, soyi47 commented
피드백 대부분 다 잘 적용해주신 것 같아요. 고생하셨습니다 👍

1. 
> 현재는 모든 훅을 다 객체{} 형태로 return하고 있는데요, 이런 스타일은 어떤지 소피아의 생각이 궁금하네요(배열 형태로 하면 지금처럼 이름 바꾸기를 안해도 되니)
- 저는 상황에 따라 다른 게 좋다고 생각하는데, 기본적으로는 객체 형태로 반환하고, 하나씩 이름 바꾸는 게 낫다고 생각합니다. 배열이면 직접 훅을 까보고 어느 순서로 뭘 반환하는지 확인해야 하는 불편함이 있잖아요. 그래서 반환할 것들이 많아지면 객체가 나은 것 같고, 반환하는 것들이 단순하면서 서로 밀접하고(예를 들면 useState의 state와 setState 수준으로 밀접한..!), 개수 자체가 얼마 안 되면 배열도 괜찮다고 생각합니다.

2. 한번 실행시켜보고 오류 없으면 오늘 중을 머지할게요!

2022-08-11 11:24 UTC, prefer2 commented
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/328#discussion_r942058220
> 아 이걸 맞춰주었던게 rest 사용을 위한 거였네요. onFocus, onChange처럼요. 이러면 맨 아래 코드들이 훨 깔끔해지는 느낌이라서요. onClick~로 명시적으로 알려주기 vs rest파라미터를 사용해서 아랫단에서는 이와 관련된거 모르게하기

요 코멘트만 다시 한 번 확인해주세요!

2022-08-11 11:28 UTC, soyi47 commented on frontend/src/pages/MyPage/index.tsx
> +        <MessageList maxPage={responseSentMessages.totalCount} />
🚨 삐뽀삐뽀 오류 발견

컨텐츠가 160갠데 마지막 페이지 번호도 160?!
마지막 페이지 계산 로직 추가 필요합니다!
그리고... 생각해보니 maxPage는 최대로 가질 수 있는 페이지 수, lastPage는 마지막 페이지 수... 라면 `maxPage` 보다는 `lastPage`가 더 적절한 것 같은데 어떤가요?


<img src="https://user-images.githubusercontent.com/71116429/184123304-b66e3755-eb02-4ba7-9320-d9e071088008.png" width="300px" />

2022-08-11 11:32 UTC, prefer2 reviewed
아핫^^

2022-08-11 11:33 UTC, soyi47 commented on frontend/src/hooks/useAutoCompleteInput.tsx
> +  };
잘 싸웠다... 멋져...

2022-08-11 11:44 UTC, prefer2 commented
> 1. 🚨 삐뽀삐뽀 오류 발견
> 
> 컨텐츠가 160갠데 마지막 페이지 번호도 160?! 마지막 페이지 계산 로직 추가 필요합니다! 그리고... 생각해보니 maxPage는 최대로 가질 수 있는 페이지 수, lastPage는 마지막 페이지 수... 라면 `maxPage` 보다는 `lastPage`가 더 적절한 것 같은데 어떤가요?
> 
> <img alt="" width="300px" src="https://user-images.githubusercontent.com/71116429/184123304-b66e3755-eb02-4ba7-9320-d9e071088008.png">
> 

이런 엄청난 오류를 왜 지금까지 몰랐을까요...? 변경 완료. 변수명도 lastPage로 바꿨습니다 33bd36e

2022-08-11 11:46 UTC, prefer2 commented on frontend/src/components/AutoCompleteInput.tsx
> +  onClick: React.MouseEventHandler<HTMLElement>;
예스 예스 이럴 경우에만 따로 지정하고 아니면 명시하기? 혹은 다 onSubmit뭐시기, onClick뭐시기로 하기로 할까요?

2022-08-11 11:50 UTC, prefer2 commented
2. onClick => onClickListItem으로 변경 0597856

2022-08-11 11:51 UTC, soyi47 commented on frontend/src/components/AutoCompleteInput.tsx
> +  onClick: React.MouseEventHandler<HTMLElement>;
음 지금 상황을 예로 들면 
AutoComplete의 props에서
1. AutoCompleteInput의 click handler를 받는 prop은 onClick,
2. AutoCompleteInput 내의 listItem의 click handler를 받는 prop은 onClickListItem 

이라고 생각합니다.

onClick은 기존에 InputAttributes에 있던 타입 고대로 가져가고, 
onClickListItem은 새로 추가하는 prop이니 지금처럼 타입을 따로 추가해주어야겠네요.

2022-08-11 12:03 UTC, soyi47 approved these changes
확인 완료! 머지하겠습니다.

2022-08-11 12:03 UTC, soyi47 commented on frontend/src/components/AutoCompleteInput.tsx
> +          {autoCompleteList.map((autocompleteListItem) => (
오~ 오타까지 잘 찾았군... 센스 👍

2022-08-11 12:47 UTC, merged