feat: 모임 롤링페이퍼 작성에 대한 API를 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #332
Opened 2022-08-10 10:58 UTC by asebn1

close #323

2022-08-11 07:15 UTC, yxxnghwan approved these changes
고생하셨습니다 제로! 사소한 코멘트 몇 개 남겼으니 확인해주세요!

2022-08-11 07:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Classification.java
> +public enum Classification {
롤링페이퍼의 구분을 위해 정의한 enum인데 패키지 이름과 클래스 이름만 가지고 해당 정보를 확인할 수 없을 것 같아요!
rollingpaper 도메인에 관련된 패키지를 만들어 응집시키면 어떨까요?

2022-08-11 07:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +                .orElseThrow((() -> new NotFoundTeamException(teamId)));
final 키워드가 빠진 것 같네요!

2022-08-11 07:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +        Rollingpaper rollingpaper = new Rollingpaper(title, Classification.TEAM, team, null);
여기도 final 키워드가 없네요!

2022-08-11 07:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +    }
inline으로 리턴할 수 있지 않을까요?

2022-08-11 07:15 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +                )
👍

2022-08-12 01:13 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +    public Long createTeamRollingpaper(String title, Long teamId, Long loginMemberId) {
파라미터에도 final을 붙여주면 좋을 듯해요

2022-08-12 01:20 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
> +    private static RollingpaperPreviewResponseDto getRollingpaperPreviewResponseDto(Rollingpaper rollingpaper, String to) {
`RollingpaperPreviewResponseDto` 클래스를 이용해서 다른 dto 생성에 간편하게 해주셨네요!
다만, `RollingpaperPreviewResponseDto` 클래스가 Controller에서 사용되는 곳이 없는데 지워도 괜찮지 않을까요?

2022-08-12 01:22 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
> -    }
회원에게 롤링페이퍼를 작성하는 인수테스트를 없앤 이유가 있을까요?

2022-08-12 01:24 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
> -    @DisplayName("특정 회원에게 롤링페이퍼를 생성하고 조회한다.")
모임에게 롤링페이퍼를 작성하는 인수테스트가 빠져있는 이유가 있을까요? 추가로, 존재하지 않는 모임에게 롤링페이퍼 작성 시 예외 케이스, 모임에 속하지 않은 사람이 해당 모임에게 롤링페이퍼를 작성할 시 예외 케이스도 추가되면 좋을 거 같아요!

2022-08-12 01:28 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
> +import static com.woowacourse.naepyeon.domain.Classification.MEMBER;
`Classification.MEMBER`를 위로 빼서 MEMBER만 파라미터에 넘기는 것도 좋고, 아예 아규먼트 인자로 Classfication을 명시해주어 가독성을 높이는 것도 좋다고 생각되는데요! 제로는 어떤게 더 좋아보이나요? (전 둘 다 상관없습니다)

2022-08-12 04:44 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/Classification.java
> +public enum Classification {
그게 좋겠네요!

2022-08-12 04:52 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +    private Rollingpaper checkCanCreateRollingpaper(Long rollingpaperId, Long teamId, Long loginMemberId) {
preview는 rollingpaper를 받아온 뒤 변경되어서 `checkCreatableRollingpaper`로 변경해보겠습니다!

2022-08-12 05:00 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
> +    private static RollingpaperPreviewResponseDto getRollingpaperPreviewResponseDto(Rollingpaper rollingpaper, String to) {
service에서 공통적으로 사용되어서 존재하는게 좋다고 생각하는데 없어도 될 이유라고 생각하신 이유가 Controller에서 사용하지 않기 때문인가요?
만약 지운다면 기존 로직변경을 어떻게 변경하는 것으로 생각하신지 궁금합니다!
`RollingpaperPreviewResponseDto`를 protected로 빼는 방향도 생각해보았는데 그럼 테스트코드에서 해당 dto를 만들 수 없어서 테스트가 불가능해요

2022-08-12 05:17 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
> -    }
나의 롤링페이퍼 조회로 검증하도록 변경하겠습니다~

2022-08-12 05:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
> +    private static RollingpaperPreviewResponseDto getRollingpaperPreviewResponseDto(Rollingpaper rollingpaper, String to) {
생각해보니까 api 명세에서 롤링페이퍼 내부로 해당 dto 응답값대로 요구하네요! 이 코멘트는 무시해줘도 될 것 같아요

2022-08-12 05:35 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
> +import static com.woowacourse.naepyeon.domain.Classification.MEMBER;
저도 둘 다 상관없어서 아무거나 써도 됩니다 :)

2022-08-12 06:00 UTC, kth990303 requested changes
잘해주셨어요 제로! 추가로 코멘트 남겼으니 확인부탁드립니다!

2022-08-12 06:00 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/RollingpaperAcceptanceTest.java
> +    @DisplayName("존재하지 않는 모임에게 롤링페이퍼를 생성하는 경우 예외를 발생시킨다.")
해당 로직 서비스테스트도 있으면 좋을 것 같네요! (어떠한 예외 클래스가 발생하는지)

2022-08-12 06:01 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
> +import static com.woowacourse.naepyeon.domain.Classification.MEMBER;
지금 이 방식대로 가도 될거같네요! 아니면 승팡의 의견도 들어보죠! @Seungpang

2022-08-12 06:25 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/domain/MessageTest.java
> +import static com.woowacourse.naepyeon.domain.Classification.MEMBER;
저도 상관은 없는데
새로운 개발자가 우리 프로젝트에 들어온다면 `Classification.MEMBER`가 코드를 파악하기 좋을 것 같고, 코드를 예쁘게 남기고 싶다면 정적 임포트가 좋을 것 같네요.

2022-08-12 06:27 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Classification.java
> +    TEAM
저는 해당 이넘의 네이밍은 현재로 유지하고 Rollingpaper에서 변수명을 `수신타입` 이런 식으로 줘도 좋을 것 같아요

2022-08-12 06:27 UTC, Seungpang approved these changes
제로! 구현하시느라 고생하셨습니다 👍 
코멘트 몇개 남겼습니다.
그 이외에는 문제가 없는 것 같아서 일단 approve 드리겠습니다.

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/jpa/MessageJpaDao.java
> +            + "else '' end) "
query가 많이 복잡했을텐데 고생하셨네요! 👍

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +    private Rollingpaper checkCreatableRollingpaper(final Long rollingpaperId, final Long teamId, final Long loginMemberId) {
해당 라인이 120자가 넘네요!

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/RollingpaperService.java
> +        }
rollingpaper.getMember()가 null이라는 의미는 모임 롤링페이퍼라는 의미가 될 것 같은데 rollingpaper에게 메시지를 던져 보는건 어떨까요?

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
> +        if (rollingpaper.getClassification().equals(TEAM)) {
해당 부분도 rollingpaper에 메시지를 던져 볼 수 있을 것 같아요!

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperPreviewResponseDto.java
> +            return getRollingpaperPreviewResponseDto(rollingpaper, rollingpaper.getTeam().getName());
get().get()을 바꿀 수 없을까요?

2022-08-12 06:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/service/dto/RollingpaperResponseDto.java
> +    public static RollingpaperResponseDto of(final RollingpaperPreviewResponseDto rollingpaperPreviewResponseDto, final List<MessageResponseDto> messages) {
해당 라인이 120자가 넘어가네요

2022-08-12 07:15 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Classification.java
> +    TEAM
Classification을 Recipient로 변경해보겠습니다

2022-08-12 08:42 UTC, kth990303 approved these changes
잘 변경해주셨네요! 수고하셨어요 😄

2022-08-12 11:27 UTC, merged