feat: API 관련 코드를 분리
woowacourse-teams/2022-nae-pyeon pull request #335
Opened 2022-08-11 06:32 UTC by prefer2

## 구현 사항
- appClient를 사용하는 API 관련 코드를 분리한다

closed #333

2022-08-11 17:38 UTC, soyi47 requested changes
API 요청 로직을 분리해줘서 컴포넌트 단에서 전보다 코드가 깔끔해졌네요. 👍👍👍

대부분 깔끔하게 잘 해주신 것 같고, 몇 가지 리뷰 남겼습니다.
크게 아래와 같아요.
1. 메서드 이름 오타
2. type을 어떻게 잘 재사용할 수 있도록 작성할 수 있을까?에 대한 고민

확인 부탁드려요~

2022-08-11 17:38 UTC, soyi47 commented on frontend/src/api/member.ts
> +
오타가 있어요! 사용하는 메소드가 put이네요.
postMyNickname -> putMyNickname

2022-08-11 17:38 UTC, soyi47 commented on frontend/src/api/message.ts
> +
당장 수정 필요하다는 거 아니고, 같이 고민해보면 좋겠다는 내용의 코멘트입니다.

여기도 그렇고, 다른 api 파일도 그렇고 인자로 사용되고 정의된 타입들이,,, 대체로 기존에 존재하는 Rollingpaper, Message 같은 타입들을 확장하거나 뽑아내서 사용할 수 있을 것 같아요.
반복해서 사용되는 타입을 잘 짜두면, 지금처럼 각 파일에서 함수마다 인자 타입을 따로 정의 안 하고도 이미 존재하는 타입을 잘 가져다 쓸 수 있을 것 같아요. 어떻게 타입을 다시 정리해보면 좋을지 한번 고민해보고 또 의견 공유할게요!

2022-08-11 17:38 UTC, soyi47 commented on frontend/src/api/message.ts
> +  editMessageId,
put의 대상이 되는 message의 id는 editMessageId 말고 그냥 id여도 될 것 같아요.

2022-08-11 17:38 UTC, soyi47 commented on frontend/src/api/message.ts
> +const deleteMessage = ({ rollingpaperId, messageId }: DeleteMessageArgs) =>
여기도 위 코멘트와 마찬가지로, delete의 대상이 되는 message의 id는 그냥 'id'여도 괜찮을 것 같아요.
음.. rollingpaperId가 있어서 헷갈리려나 싶기도 한데, 도리 의견은 어떤가요? rollingpaperId와 확실한 구분을 위해 messageId 혹은 editMessageId 같이 표현하는 게 더 낫다고 생각하시나요?

2022-08-11 17:38 UTC, soyi47 commented on frontend/src/api/team.ts
> +}
type 폴더 하위로 옮기고, 모임 관련 페이지에서 유사한 타입이 사용되지 않는지, 관련해서 리팩토링할 수 없을지 찾아보면 좋을 것 같습니다.

2022-08-12 01:04 UTC, prefer2 commented on frontend/src/hooks/useParamValidate.tsx
> +  }
저는 우선 ErrorBoundary를 사용하는게 좋지 않을까 했어요. 이걸 페이지 단 마다 처리해주기는 너무 공통적인 에러인 것 같거든요. param값이 undefined이 되는 경우는 큰 오류라고 생각이 들어서 앱 단에서 이를 처리해주는 것이 좋지 않을까 싶습니다

2022-08-12 01:06 UTC, prefer2 commented on frontend/src/api/member.ts
> +
굿굿 수정 완료! [03f2a9d](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/335/commits/03f2a9d0eaf960317b4333cdcde91fab9fed637b)

2022-08-12 01:08 UTC, prefer2 commented on frontend/src/api/message.ts
> +
저도 이부분을 코드를 짜면서 많이 아쉽더라고요. 각 API마다 사용하는 값이 다르다보니 type을 무작정 많이 선언하게 된 것 같아요. 큰 단위의 type을 지정한 뒤 뽑아쓰는 것이 좋을지 한번 다 모아놓고 생각을 해봐야 할 것 같아요.

2022-08-12 01:13 UTC, prefer2 commented on frontend/src/api/message.ts
> +const deleteMessage = ({ rollingpaperId, messageId }: DeleteMessageArgs) =>
이번에는 그냥 있는 값을 복붙해서 썼는데요, api로 분리하게되면 대상이 되는 id는 명시하지 않고 그냥 id로 해도 될 것 같기도 하네요.

2022-08-12 01:17 UTC, prefer2 commented on frontend/src/api/message.ts
> +const deleteMessage = ({ rollingpaperId, messageId }: DeleteMessageArgs) =>
위 코멘트와 함께 수정했습니다 [ce00039](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/335/commits/ce000395764c2b8d0501665c6fbe8a40ea48d782)

2022-08-12 01:20 UTC, prefer2 commented on frontend/src/api/team.ts
> +}
team type은 분리하는 것이 좋을 것 같아 분리했습니다! 2dc0dca

2022-08-12 01:49 UTC, Seungpang commented
빌드시 에러가 뜨는 것 같아서
확인 부탁드려요

```shell
ERROR in /var/lib/jenkins/workspace/frontend-pr-build/frontend/src/pages/TeamCreationPage/index.tsx
./src/pages/TeamCreationPage/index.tsx 50:22-75
[tsl] ERROR in /var/lib/jenkins/workspace/frontend-pr-build/frontend/src/pages/TeamCreationPage/index.tsx(50,23)
      TS2345: Argument of type '{ teamName: string; teamDescription: string; emoji: string; color: string; nickname: string; }' is not assignable to parameter of type 'Team'.
  Property 'id' is missing in type '{ teamName: string; teamDescription: string; emoji: string; color: string; nickname: string; }' but required in type 'Team'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/App.tsx 25:41-76
 @ ./src/index.tsx 25:28-44
```

2022-08-12 04:33 UTC, soyi47 commented on frontend/src/hooks/useParamValidate.tsx
> +  }
예를 들어 모임의 롤링페이퍼 페이지에서 롤링페이퍼 id가 undefined인 경우 모임 페이지로 이동하고, 모임 id부터 undefined인 경우, 메인 페이지로 이동하도록 에러 처리하는 상황이라고 가정해봅시다.
그럼 정의할 ErrorBoundary가 상황에 따라 어떤 페이지로 이동할지 알아야 할 것 같아요. 어떤 식으로 정보를 넘겨주는 게 좋을까요?

제가 당장에 생각해본 방법은, Error를 던질 때 이동할 페이지 정보를 넘겨주는 방법이 있을 것 같아요. 아래와 같은 방식인데 괜찮은 방법인지는 잘 모르겠습니다.
1. useParamValidate가 이 에러 처리에 관한 정보(이동할 페이지 정보)를 받아서 Error를 만들어야 하고,
2. Error는 에러 처리 방식에 대한 정보를 들게 될 것 같아요.

위 방식처럼 에러 처리에 관한 로직을 곳곳에 주지 않으려면,,,?
커스텀훅이니, 꼭 에러를 던지지 않더라고 에러 상태를 정의하는 방법(isError)도 있을 것 같아요. 그럼 페이지 컴포넌트에서 에러를 처리하게 될 것 같은데, 페이지마다 해당 에러에 대한 처리 방식이 다르다면 오히려 페이지에서 바로 처리해버리는 게 코드를 더 이해하기가 쉬울 것도 같아요.

2022-08-12 05:54 UTC, soyi47 requested changes
분리한 api 함수를 사용하지 않는 코드가 보여서 수정 요청합니다!

2022-08-12 05:54 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
>      },
여기 putTeamNickname을 가져다 써야겠네요!

2022-08-12 05:54 UTC, soyi47 commented on frontend/src/api/team.ts
>        .get(`teams?keyword=${keyword}&page=${pageParam}&count=${count}`)
API 관련 로직들이니, Args보다, Request, Response 타입을 정의해서 여기와 리액트 쿼리를 사용하는 곳에서 같이 사용하도록 할 수 있을 것 같아요. 어떤 방식으로 정리할 수 있을지 생각해보고 다시 코멘트 할게요!

2022-08-12 06:09 UTC, prefer2 commented on frontend/src/hooks/useParamValidate.tsx
> +  }
어떤 경우에 param이 undefined가 되는가를 생각해보았을 때 사용자가 임의로 url 접근을 했는데 올바르지 않은 값을 입력했을 때만 있지 않을까 싶더라고요. 다음과 같이 말이죠 `www.naepyeon.site/teams//rollingpaper/1` 만약 사용자가 마이페이지에서 이 url을 쳐서 들어갔다면? 기존의 페이지로 돌려줄지, team페이지로 돌려줄 지 또는 메인페이지로 돌려줄 지 고민이 되더라고요. 

만약의 그 팀이 비밀모임이라면? 이라는 생각때문에 team페이지로 돌려주는 것은 적절하지 않다고 생각했습니다. 그래서 메인 또는 이전 페이지로 돌아가는 것이 좋을 것 같아요. 이런 방식이라면 오히려 페이지 단에서 처리하는 것 보다 errorBoundary로 공통되게 처리해주는 것이 좋지 않을까 싶기도 하고요....🤔

2022-08-12 06:12 UTC, prefer2 commented on frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
>      },
머지하면서 새로 생긴 친구군요... useParamValidate써서 수정 했습니다 [0f6656d](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/335/commits/0f6656d599101931cb28d32c3ae68e8f8ddd8bf6)

2022-08-12 06:13 UTC, prefer2 commented on frontend/src/api/team.ts
>        .get(`teams?keyword=${keyword}&page=${pageParam}&count=${count}`)
수정 완료 [e390c10](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/335/commits/e390c1053c6f16a6e2686a0b58322efbb22d8c87)

2022-08-12 06:20 UTC, soyi47 commented on frontend/src/api/team.ts
>        .get(`teams?keyword=${keyword}&page=${pageParam}&count=${count}`)
앗 지금 수정해달라는 건 아니었는데! 일단 오키

2022-08-12 06:42 UTC, soyi47 commented on frontend/src/hooks/useParamValidate.tsx
> +  }
> 만약의 그 팀이 비밀모임이라면? 이라는 생각때문에 team페이지로 돌려주는 것은 적절하지 않다고 생각했습니다. 그래서 메인 또는 이전 페이지로 돌아가는 것이 좋을 것 같아요. 이런 방식이라면 오히려 페이지 단에서 처리하는 것 보다 errorBoundary로 공통되게 처리해주는 것이 좋지 않을까 싶기도 하고요....🤔

음 비밀 모임이라고 하더라도? 모임에 가입된 사용자라면 모임 페이지로 줄 수도 있고, 아니면 메인 페이지로 이동시킬 수도 있겠죠..? 
항상 메인 또는 이전 페이지로 돌아가도록 처리할거면 상관 없지만 이런 여러가지 상황을 커스텀해줘야한다면 어떤 방법이 좋을지 고민이 필요하단 이야기였습니당..! 이건 일단 Error 던지는 걸로 하고 조금 더 생각해보죠!

2022-08-12 06:44 UTC, soyi47 commented on frontend/src/hooks/useParamValidate.tsx
> +  }
> 만약의 그 팀이 비밀모임이라면? 이라는 생각때문에 team페이지로 돌려주는 것은 적절하지 않다고 생각했습니다. 그래서 메인 또는 이전 페이지로 돌아가는 것이 좋을 것 같아요. 이런 방식이라면 오히려 페이지 단에서 처리하는 것 보다 errorBoundary로 공통되게 처리해주는 것이 좋지 않을까 싶기도 하고요....🤔

음 비밀 모임이라고 하더라도? 모임에 가입된 사용자라면 모임 페이지로 줄 수도 있고, 아니면 메인 페이지로 이동시킬 수도 있겠죠..? 
항상 메인 또는 이전 페이지로 돌아가도록 처리할거면 상관 없지만 이런 여러가지 상황을 커스텀해줘야한다면 어떤 방법이 좋을지 고민이 필요하단 이야기였습니당..! 이건 일단 Error 던지는 걸로 하고 조금 더 생각해보죠!

2022-08-12 06:44 UTC, soyi47 approved these changes
수정 확인했습니당! merge 할게요!

요 코멘트만 확인해주세요!
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/335#discussion_r944159716

2022-08-12 06:44 UTC, merged