feat: 메시지 작성 시 비밀글/익명을 선택할 수 있게 한다
woowacourse-teams/2022-nae-pyeon pull request #344
Opened 2022-08-13 06:36 UTC by prefer2

## 구현 사항
- 모킹 코드 변경 및 더미 데이터 추가
  - anonymous, secret 추가
- 비즈니스 로직 커스텀 훅으로 분리
  - useCreateMessage(API 관련) + useNewMaessage
  - useUpdateMessage(API 관련) + usePrevMessage
  - useDeleteMessage(API 관련)
  - useMessageTextArea
 - 익명이 아닌 비밀글에 닉네임 보이도록 UI 수정
<img width="352" alt="스크린샷 2022-08-13 오후 3 35 52" src="https://user-images.githubusercontent.com/67692759/184471993-e3737b74-f44c-411f-8040-51e4ad5a20ce.png">

### 논의할 사항
- state관련 훅을 useNewMessage, usePrevMessage라고 지었는데요, 혹시 더 좋은 네이밍이 생각나면 알려주세요
- api관련 훅과 컴포넌트 단의 훅이 혼재되어 있는데요, 이를 폴더로 분리하는 것이 좋을지 지금처럼 모두 hooks 폴더에 넣는 것이 좋을지 고민입니다. 우선은 훅이 몇개 없어 hooks 폴더에 모두 넣는 것도 괜찮은 것 같아요.

closed #341

2022-08-13 06:43 UTC, prefer2 commented
## UI 관련 수정해야 할 사항

### 수정 버튼 누르기 전
![스크린샷 2022-08-13 오후 3 41 41](https://user-images.githubusercontent.com/67692759/184472176-61c7521d-3188-4d28-9cfd-e3bac3667c8c.png)

### 수정 버튼 누른 후
![스크린샷 2022-08-13 오후 3 41 52](https://user-images.githubusercontent.com/67692759/184472178-9df3410e-4f6f-4135-931e-6b335680788c.png)

- 가로 스크롤바가 생김
- 버튼 영역만큼 편지지가 있거나 흰 부분이 보였으면 좋겠음

2022-08-13 06:46 UTC, prefer2 commented
## 비밀글 UI를 꼭 넣어야겠다고 생각이 든 이유
내가 쓴 익명글과 내가 쓴 익명 비밀글을 구분할 수 없음
<img width="329" alt="스크린샷 2022-08-13 오후 1 14 05" src="https://user-images.githubusercontent.com/67692759/184472293-18ffd60e-f5a6-4b32-bc74-719643d94353.png">
<img width="319" alt="133500" src="https://user-images.githubusercontent.com/67692759/184472296-685fd21c-8932-4b1e-87c1-67cf989dbb7d.png">

2022-08-13 08:03 UTC, soyi47 requested changes
돌이,, 많은 변경사항이 있었군요. 고생했습니다. 😥
리팩토링도 병행해서 코드가 훨씬 깔끔해졌네요. 좋아요. 👍

1. usePrevMessage, useNewMessage 관련해서는 코멘트 남겼으니 확인해주세요.
2. hook 폴더 정리 관련해서 당장 떠오르는 방법으로는,,, hooks/api 폴더를 만들어 api 관련 훅을 모아두고, 컴포넌트 단의 훅은 일단은 해당 컴포넌트를 사용하는 page 폴더의 hooks 폴더에 넣어두면 어떨까 싶습니다.
3. MessageForm 컴포넌트 전환 시 페이지 레이아웃이 깨지는 오류는 다른 작업이니 새로 이슈 파서 작업하면 좋을 것 같아요.
4. 비밀글 UI는 결국 내가 쓰든, 받았든, 익명이든 아니든 Form으로 전환하지 않고서는 비밀글인지 한눈에 알아보기 어려운 게 문제인 것 같아요. 어떤 방식으로 표현하면 이야기 나눠봐야 할 것 같네요. 정리해서 다른 이슈로 진행합시다.

2022-08-13 13:34 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/hooks/usePrevMessage.tsx
> +};
저도 작성하면서 음... 뭔가 그냥 복붙에 가까운데 싶었는데 이렇게 하면 되겠네요! 굿굿

2022-08-13 14:24 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
> +              return <SecretMessage key={message.id} author={message.from} />;
api에서 author로 내려오기도 하고 해서 우선 둘 다 author로 받는걸로 수정했습니다! [93e1e63](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/344/commits/93e1e63ce65f910a97683f8bc102245d71ae9ab0)

2022-08-14 04:12 UTC, soyi47 requested changes
조금 더 리팩토링 할 수 있는 부분들이 보여서 코멘트 남깁니다!
확인해보고 도리 의견 주세요~ 🐠🐠🐠

2022-08-14 04:12 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>                );
[여기 코멘트](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/344#discussion_r945108426)에서 이어지는 이야기입니당. 
API에서는 메시지 작성자 정보를 from으로 내려주고 있는 것 같아요..!
RollingpaperMessage 컴포넌트 prop들의 이름을 수정하면 prop을 하나하나 내려주지 않아도 될 것 같다는 이야기였습니당. 

RollingpaperMessage의 prop 중 author를 from으로, isVisible이 visible로 바뀌면 아래와 같이 바로 분해 할당할 수 있을 것 같아요.
제 생각에는 prop이, AP 응답으로 돌려받은 정보와 같아도 괜찮을 것 같아서 하는 제안입니다!
```suggestion
              return (
                <RollingpaperMessage
                  key={message.id}
                  {...message}
                />
              );
```

2022-08-15 05:14 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>                );
아하 이말이었군요. 좋습니당

2022-08-15 06:35 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/hooks/useMessage.tsx
> +  };
1. useMessageForm으로 관련 훅을 빼고, 이를 messageForm에서만 사용하니 한 결 보기 좋아졌네요. 다만 submit관련해서 분기 처리가 필요해 createMessageForm과 updateMessageForm으로 분리하였습니다.

훅으로 분리를 나누다보니 우리네의 LetterPaper가 드디어 보기 좀 좋아졌네요. 기쁩니다

2022-08-15 07:44 UTC, soyi47 requested changes
이전보다 많이 깔끔해졌네요. 고생했어요! 💕💕💕
조금 헷갈리거나 의견 나눠보면 좋을 부분들에 대해 리뷰 남겼습니다!

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>            </IconButton>
useMessage가 무슨 로직인지 열어봤더니 handleWriteButtonClick과 handleDeleteButtonClick을 다 반환하고 있네요. 그럼 MessageBox에서 사용될 로직으로 예상되고, useMessageBox라는 이름이 더 적합하다고 느껴지는데요.

IconButton의 로직은 새로운 메시지 추가에 대한 내용인데, 
이 useMessage에서 반환한 핸들러를 사용하는 게 흐름을 파악하기에 헷갈리는 포인트인 것 같아요. 🤔
유사한 로직이라 재사용도 좋기는 하지만,,, 따로 분리해주는 게 좋지 않을까 싶기도 하네요... 도리 생각은 어떤가요~?

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>              })}
깔꼼 👍

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageBox.stories.jsx
> +const Template = (args) => <MessageBox {...args}></MessageBox>;
스토리북도 잘 챙겼네요 👍

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageBox.tsx
> +}
type 폴더에 있는 Message 타입을 사용해봅시다!

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/hooks/useDeleteMessage.tsx
> +  );
mutate 함수인 deleteRollingpaperMessage에서 message id를 인자로 받는 건 굉장히 자연스러워서 좋은데,,,
useDeleteMessage인데 커스텀 훅의 인자로는 rollingpaperId가 들어가는 것이 헷갈리기 쉬울 것 같아요. ㅠㅠ 삭제 요청에 지금 rollingpaperId가 필요해서 어쩔 수 없기는 하네요... ㅜㅜ

임시로 커스텀 훅의 인자를 객체로 바꾸고 rollingpaperId를 명시해서 내려 받도록 하면 어떨까요..?

2022-08-15 07:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/hooks/useMessage.tsx
> +  };
이전보다 많이 깔끔해졌네요. 고생했어요! 👍

2번에 관하여 > 저는 지금 정도까진 괜찮은 것 같아요! 

추가로 고려해보면 좋겠다 싶은 부분은...
저는 setIsEdit을 직접 내려주는 걸 지양하는 편이라 setIsEditFalse 또는 onClickSubmit 같은 이름의 함수로 한번 감싸서 내려주면 어떨까 하는 생각이 드네요. 도리 의견은 어떤가요~?

2022-08-15 08:27 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>            </IconButton>
MessageBox로 수정만 하고 useMessageBox는 수정하지 않았네요 😅

저도 이거는 만들면서 좀 헷갈리더라고요. delete와 같은 로직들이 useMessageBox에 있다보니... useLetterPaper를 뽑아서 써볼까라는 생각도 드네요. 이렇게 뽑으면 updateSlicedMessageList까지 useLetterPaper훅에 옮길까 싶은데 어떤가요??

2022-08-15 11:17 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/hooks/useDeleteMessage.tsx
> +  );
저도 이게 조금 아쉽기는 하더라고요. deleteMessage인데 messageId가 아니라 rollingpaperId를 내려준다니ㅠ
저는 이 부분은 타입스크립트로 명시한다고 생각했어요(hover하면 어떤 인수를 받고 있는지 알려줌) 사용하는 곳에서 rollingpaperId로 값을 명시해 주고 있는데 객체로 변환한다고 크게 차이가 없어질 것 같다는 느낌입니다.
![스크린샷 2022-08-15 오후 8 16 12](https://user-images.githubusercontent.com/67692759/184625791-24064856-c797-43b4-96e3-3b534a773099.png)

2022-08-15 11:27 UTC, prefer2 commented
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/344#discussion_r945490660
왜인지는 모르겠지만 outdated되서 이렇게 답합니당
어떤 네이밍으로 할까 하다가 onEditEnd로 했어요. 훅에서도 우선 handler로 한 번 감싸주는게 좋을 것 같아 handleEditEnd로 감싸주었습니다! [4fbbbb6](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/344/commits/4fbbbb6a3620b1afa0e3358dd002d132496585ff)

2022-08-15 11:29 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/LetterPaper.tsx
>            </IconButton>
저는 컴포넌트 단위로 생각하기보다 기능 단위, 로직의 성격을 기준으로 나눠서 만들어보면 좋을 것 같아요.
먼저 새 메시지 생성에 관한 커스텀 훅과 메시지 정렬 계산 로직 커스텀 훅으로 나눠서 써보면 어떨까요?
그 다음, 이 로직들을 합치는 게 가독성이든 컴포넌트 측면에서든 의미가 있는지 한번 생각해봅시다.

2022-08-15 11:36 UTC, soyi47 requested changes
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/344#issuecomment-1214907541 
요 코멘트 잘 확인했습니다. 
관련해서 수정하면서 생긴 것으로 보이는 잘못 작성된 코드가 있어요. 수정요청합니다!

2022-08-15 11:36 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
>  };
이 친구 이제 setState 함수가 아니라 setState 함수를 호출하는 핸들러 함수를 받는 친구인 것 같은데, 타입이 잘못된 것 같아요.

2022-08-15 11:36 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageCreateForm.tsx
> +      onEditEnd(false);
onEditEnd에서 받은 함수는 useMessageBox에서 반환한 handleEditEnd인데요.
그럼 인자값으로 boolean을 받을 필요가 없어요. onEditEnd 전체적으로 한번 확인해주세요~

2022-08-15 11:36 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/components/MessageUpdateForm.tsx
> +  onEditEnd: React.Dispatch<SetStateAction<boolean>>;
MessageUpdateForm도 위와 마찬가지입니다. onEditEnd 한번씩 확인해주세요~

2022-08-15 11:57 UTC, prefer2 commented
집에 가야할 때가 된 걸지도...? createMessageForm, updateMessageForm 수정 했습니다!! e26e926

2022-08-15 12:11 UTC, prefer2 commented
useMessageWrite, useSliceMessageList로 분리해보았습니당! 8e48e9b 8493a37

2022-08-15 12:17 UTC, soyi47 approved these changes
마지막 수정까지 확인했습니다!

많은 리팩토링과 함께 진행해서 코드가 정말 많이 깔끔해졌네요. ㅜㅜ 너무 고생했어요! 🥰

2022-08-15 12:18 UTC, merged