feat: 모임/개인에게 롤링페이퍼 작성을 위한 UI를 구현
woowacourse-teams/2022-nae-pyeon pull request #350
Opened 2022-08-13 13:05 UTC by prefer2

## 구현 사항
- 모임, 개인을 선택해서 롤링페이퍼를 작성할 수 있도록 함
<img width="374" alt="스크린샷 2022-08-13 오후 10 01 07" src="https://user-images.githubusercontent.com/67692759/184495336-b66358ca-7cc8-4b31-8e57-e3715348d497.png">

![스크린샷 2022-08-13 오후 10 02 01](https://user-images.githubusercontent.com/67692759/184495358-fc24ff9b-3cec-443e-b251-0065bce97840.png)

![스크린샷 2022-08-13 오후 10 02 16](https://user-images.githubusercontent.com/67692759/184495364-d581db76-582e-4fbb-b77a-ec49afaaac31.png)

### 고민 거리
- RecipientType의 위치. 페이지 내에서만 사용되는 타입이라 이를 type폴더에 빼는 것이 맞을지 고민입니다. 오히려 RECIPIENT 상수와 같이 있는게 보기 더 편한 것 같기도 하고...??
- 모바일 위주로 구현하다보니 데스크탑 버전에서는 조금 공허함(단 이점은 기존에도 그랬어서 괜찮은 것 같기도 하구)
- 모임을 선택했다가 앗차 하고 뒤로 돌아갈 수 없음. 사용자가 뒤로가기를 눌렀을때 바로 팀 상세페이지로 가게 해도 괜찮을까에 대한 고민. 혹은 모임에 대한 롤링페이퍼를 작성중인지, 팀에 대한 롤링페이퍼를 작성중인지를 바로 알기 어려움. `회원가입`처럼 제목을 위에 써주는 것이 좋을까?

closed #345

2022-08-14 04:50 UTC, soyi47 requested changes
수정하거나 같이 의견 나눠볼 내용들 코멘트로 남겼습니다! 확인해주세요!

2022-08-14 04:50 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/index.tsx
> +export type RecipientType = ValueOf<typeof RECIPIENT>;
Type 떼고 그냥 Recipient여도 충분할 듯?

2022-08-14 04:50 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
> +};
여기서 type을 들고 RecipientBox에서 내려받는 onClick을 고차함수로 작성해서 RecipeintBox에서 인자값을 주는 방법도 생각해볼 수 있을 것 같아요..

```
// RecipientBox.tsx

const boxInput = {
  team: {
    type: RECIPIENT.TEAM,
    to: "모임",
    description: "모임을 대상으로 한 롤링페이퍼 작성하기",
  },
  member: {
    type: RECIPIENT.MEMBER,
    to: "개인",
    description: "모임 내의 멤버에게 롤링페이퍼 작성하기",
  },
};

// paperCreationPage.tsx
// handleTeamRollingpaperCreateClick, handleMemberRollingpaperCreateClick을 아래와 같이 하나로 만들어 RecipientBox의 onClick에 내려주기. RecipientBox에서 내려받은 onClick에 type 인자 주기

const handleRecipientBoxClick = (recipient: RecipientType) => () => {
  setRecipient(recipient);
}
```

2022-08-14 04:50 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
훅으로 분리할까요~?

2022-08-14 04:50 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +}
Response 값과 Request에 주는 값의 타입을 지정할 때 네이밍 컨벤션이 필요할 것 같아요.

```
ResponseTeamMemeber vs TeamMemeberResponse
Request...@#$ vs ...@#$Request
```

어떤 게 더 좋을까요? 개인적인 취향은 앞에 붙는 거..!

2022-08-14 04:55 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
> +};
member의 to는 "개인"보다는 "멤버"가 좋을 것 같아요!

2022-08-15 07:22 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
> +};
오 아주 좋은 아이디어네요! 굿굿굿 
수정했습니다 [e7448ee](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/350/commits/e7448eecb8abac26947adbfe31a9e7c3a8debb61)

2022-08-15 07:37 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
분리 완료! 4e56dd6
훅 이름을 지을때 고민이었는데요, 전반적으로 Create, Update를 사용하고 있는 것 같아 Read를 사용하였습니다

onSuccess일 때 닉네임을 세팅해주는 작업을 하고 있었는데 이를 훅 안에서 해 주는 것은 옳지 않은 것 같아 우선은 컴포넌트 단으로 빼주었어요. 차후에 로직이 추가되고 하면서 useMemberRollingpaperCreateForm으로 또 분리해주는 것도 좋을 것 같습니다.

2022-08-15 07:39 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +}
흠 뭔가 문법적으로는 2번(~Response)이 더 맘에 들기는 하는데 이게 Response type이다 딱 보여주는 것은 1번 인 것 같네요. 1번을 더 선호하는 이유가 있나요???

2022-08-15 07:48 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +}
저도 같은 이유입니다. 요청 응답에 대한 타입이라는 게 조금 더 빠르게 파악되는 느낌이라 1번을 선호해요.

2022-08-15 07:49 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
페이지 컴포넌트에서 isSuccess 상태를 if 문으로 체크해서 닉네임 리스트를 세팅해주는 것보다, useReadTeamMembers가 onSuccess 핸들러를 받도록 작성해보는 건 어떨까요?

2022-08-15 07:52 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
### 다시 수정

setKeywordList를 최대한 밖으로 빼고 싶었는데, 방법을 잘 모르겠네요. 혹시 더 좋은 방법 있다면 제안해 주시겠어요,,,,ㅠ
[89deb25](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/350/commits/89deb25f9889367c347a4e58c236f1888b637cba)

2022-08-15 11:25 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
아래와 같이 useReadTeamMemeber를 수정하고, 
```
  const { data: teamMemberResponse } = useReadTeamMembers(
    +teamId,
    onSuccess
  );
```

useReadTeamMembers에서는 useQuery option에 prop으로 받은 onSuccess를 넣도록 작성하면 될 것 같아요!
RollingpaperCreateForm에서 onSuccess에 내려줄 핸들러를 작성할 때 setKeywordList를 사용하는 방식으로 쓰면 좋겠어요.

2022-08-15 12:32 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  );
이런 좋은 방법이! 객체 형식으로 이렇게 전달하는군요...! 수정했습니다 2de58dc

2022-08-15 12:38 UTC, soyi47 approved these changes
마지막 수정사항 확인했어요!
문제 없이 동작하는 것도 확인했습니다.
요 페이지들 이제 기능 구현으로 넘어가면 되겠네요! 하하하
고생했습니다 🥰🥰🥰

2022-08-15 12:38 UTC, merged