feat: 모임 롤링페이퍼 추가 기능을 추가
woowacourse-teams/2022-nae-pyeon pull request #361
Opened 2022-08-16 10:15 UTC by prefer2

## 구현 사항
- 모임에게 롤링페이퍼 작성하기 기능 추가 (useCreateTeamRollingpaper)
- 멤베에게 롤링페이퍼 작성하기 기능 추가 (useCreateMemberRollingpaper)
- AutoCompleteInput 컴포넌트 수정
  - AutoCompleteList 위치 변경
  - useAutoCompleteList 수정 (e.preventDeault 제거)

closed #356

2022-08-16 16:28 UTC, soyi47 requested changes
도리~ 고생하셨습니다! 👍

컨벤션이나 확인 필요한 부분들 위주로 소소하게 남겼어요! 확인 부탁해요~

2022-08-16 16:28 UTC, soyi47 commented on frontend/src/api/rollingpaper.ts
> +}: Omit<PostRollingpaperRequest, "addresseeId">) =>
이전 이슈에서 논의하면서 `Response...`와 같은 형식으로 타입명을 수정했는데요. 
여기도 같은 컨벤션을 적용하면 어떨까요?

2022-08-16 16:28 UTC, soyi47 commented on frontend/src/components/AutoCompleteInput.tsx
> +      </StyledLabel>
도리를 애먹인... 그 친구군요. 해결하느라 고생했어요 😂😂👍👍

2022-08-16 16:28 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +import useCreateMemberRollingpaper from "@/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper";
바로 위 라인의 useReadTeamMembers를 분해해서 import 하고 있네요. defatul export가 아닌 걸까요?!
한번 확인 부탁해요~

2022-08-16 16:28 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  const createMemberRollingpaper = useCreateMemberRollingpaper(+teamId);
컴포넌트와 함께 사용되는 커스텀훅을 모아볼 수 있도록, 
useParamValidate를 맨 위로 보내고,
useInput과 useAutoComplete을 함께 작성해주는 순서면 좋을 것 같아요~

2022-08-17 01:58 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MemberRollingpaperCreateForm.tsx
> +  const createMemberRollingpaper = useCreateMemberRollingpaper(+teamId);
수정 완료! [4e9c5d7](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/361/commits/4e9c5d77369f9dad7d468fcf6bfdd127683ba37e)

2022-08-17 02:27 UTC, soyi47 requested changes
도리~ 수정 확인했습니다!

### 추가 수정 필요한 부분
- 모임 롤링페이퍼 생성 폼에서, 롤링페이퍼 제목 입력을 안 했는데 완료 버튼이 활성화되어 있어요! 입력을 해야 활성화되도록 하는 게 좋겠습니다.

<br >

### UI 개선 제안
UI 관련해서 개선하면 좋겠다 싶은 부분들이 보여서 같이 남겨둘게요~
아래 내용을 수정하게 된다면 다른 이슈에서 진행하면 좋을 것 같아요!

#### 1. 롤링페이퍼 생성 폼 입력란 하단 여백
- 입력란과 완료 버튼 사이에 여백이 조금 더 있으면 좋겠습니다.

<img src="https://user-images.githubusercontent.com/71116429/185020174-0118debd-78f0-4b1e-b4e4-44ac393d7d1a.png" width="300px" />
<img src="https://user-images.githubusercontent.com/71116429/185020258-f579b144-635b-4ab9-8949-9784e2b43673.png" width="300px" />

<br >

#### 2. 안내문구 수정
- 개발하는 입장에서는 용어로는 롤링페이퍼의 대상이 모임이라고 표현하는 게 맞을 것 같은데,  '모임을 대상으로 한 롤링페이퍼'라는 표현이 사용자들에게는 어색하게 느껴질 수 있을 것 같아요! '모임 멤버 모두가 공유하는 롤링페이퍼 쓰기' 이 정도로 수정해보면 어떨까요?
<img src="https://user-images.githubusercontent.com/71116429/185020587-ab0728bb-869c-427c-9ebc-3bf7979ec7cc.png" width="300px" />

2022-08-17 04:20 UTC, soyi47 requested changes
🚨 에러 메시지 추가가 필요합니다!

<img src="https://user-images.githubusercontent.com/71116429/185033911-63fa3c3f-d060-4d1e-b130-8eb99831b634.png" width="300px" />

2022-08-17 04:33 UTC, soyi47 approved these changes
고생하셨습니다!

2022-08-17 04:33 UTC, merged