feat: Naver OAuth 로그인을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #362
Opened 2022-08-16 12:53 UTC by prefer2

## 구현 사항
- Naver OAuth 로그인 구현

### 고민
- 우선은 kakao login과 동일하게 state를 통해 inviteToken을 전달하달하도록 구현하였습니다. 현재 inviteToken이 있다면 이 값을, 아니라면 난수를 생성하여 넘기고 있습니다. 다만 공식문서에서 state값을 다음의 이유로 사용한다고 나와 있어 inviteToken을 넘기는 것이 맞을지 고민이 됩니다.
https://developers.naver.com/docs/login/devguide/devguide.md#3-4-1-%EB%84%A4%EC%9D%B4%EB%B2%84-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%97%B0%EB%8F%99%EC%9D%84-%EA%B0%9C%EB%B0%9C%ED%95%98%EA%B8%B0%EC%97%90-%EC%95%9E%EC%84%9C
  > 사이트 간 요청 위조(cross-site request forgery) 공격을 방지하기 위해 애플리케이션에서 생성한 상태 토큰값으로 URL 인코딩을 적용한 값을 사용
- 백에게 보내는 state와 client단에서 사용하는 state가 동일해야 하는가?

closed #360

2022-08-16 14:09 UTC, kth990303 reviewed
naver OAuth 구경왔습니다 ㅎㅎ
state 관련해서 코멘트 남겨봤는데 확인해주시고, 만약 제가 잘못 이해한게 있다면 답글 남겨주세요!
내편 프론트 화이팅!

2022-08-16 14:09 UTC, kth990303 commented on frontend/src/constants/index.ts
> +    `https://nid.naver.com/oauth2.0/authorize?client_id=${process.env.NAVER_REST_API_KEY}&redirect_uri=${process.env.NAVER_REDIRECT_URL}&response_type=code&state=${inviteToken}`,
찾아보니까 NAVER에서의 state값은 임의의 값을 넣어도 된다고 하는 것 같긴 한데 token 안넘겨도 괜찮지 않을까 싶긴 해요

> 대부분 카카오 API와 같지만, 새로운 state 값이 있습니다. 해당 값은 사이트 간 요청 위조 공격을 방지하기 위한 값으로, 요청 시 입의의 값을 전달하면 응답시 동일한 값을 반환해 내가 작성한 요청에 대한 응답인지를 확인하기 위한 목적입니다. state는 임의의 값을 사용해도 됩니다. 샘플에서는 "abcdef" 값을 사용했습니다.(랜덤으로 문자열을 생성해서 사용해도 됩니다.)

출처:  https://blog.hjf.pe.kr/517 

이 말대로라면 응답으로 받은 state를 다시 보낼 때 사용되는 거기 때문에 state가 백 쪽으로 안와도 괜찮지 않을까요? 내편 서비스에서 받은 state를 그대로 넘겨주면 accessToken이 나올 것 같아서요!

아래 글은 혹시나 도움될까 싶어 남겨봅니다!

- https://devlopsquare.tistory.com/189 : 우아한테크코스 3기의 네이버 OAuth 포스팅

2022-08-17 02:10 UTC, soyi47 requested changes
도리 고생했습니다!

네이버 로그인을 적용할 수 있을지 불확실하니 우선은 너무 힘빼지 맙시다 하하
소소하게 리뷰 남겼어요!

2022-08-17 02:10 UTC, soyi47 commented on frontend/src/pages/NaverRedirectPage/index.tsx
> +      }),
프론트 쪽에서 필요한 URL 리다이렉트를 위해 주는 state와,
토큰 발급 요청에 사용하는 state가 같아야 하는 게 아니라면, 
post 요청에 state가 포함될 필요는 없을 것 같아요.

저도 공식 문서를 훑어봤는데, 꼭 같아야 한다는 이야기는 없는 것 같네요.

2022-08-17 02:10 UTC, soyi47 commented on frontend/src/types/oauth.ts
> +};
오타! t가 빠졌어요.

RequesNaverOauthBody -> RequestNaverOauthBody

2022-08-17 02:10 UTC, soyi47 commented on frontend/src/pages/LoginPage/index.tsx
> +    location.href = NAVER_OAUTH_URL.AUTHORIZE_CODE(inviteToken);
네이버 로그인에서 리다이렉트 URL로 돌아왔을 때 값을 유지하여 받는 방법을 제공하는지 찾아봤는데 안 보이네요. 😥

카카오와 같은 방식으로 state에 주는 것도 괜찮은 것 같은데,
꼭 랜덤하게 생성된 문자열이어야 한다면, 다음과 같이 inviteToken과 랜덤 생성한 값을 조합하는 방법도 있을 것 같아요..! 좋은 방법인지는 모르겠습니다... ㅠㅠ

```
const state= encodeURIComponent(
  `{inviteToken: ${inviteToken}, state:${Math.random()}}`
);
```

2022-10-18 15:10 UTC, closed without merging