refactor: Http 요청 로깅 위치를 preHandle로 변경
woowacourse-teams/2022-nae-pyeon pull request #412
Opened 2022-08-30 08:08 UTC by yxxnghwan

ㅈㄱㄴ

close #380

2022-08-30 09:43 UTC, kth990303 requested changes
수고하셨습니다~
로깅 관련해서 모르는 부분들이랑 yml에 충돌 기록 남아있는 점 때문에 RC로 했습니다!
추가로, fork한 레포에서 PR을 날려서 소나큐브가 실패하네요 😢

2022-08-30 09:43 UTC, kth990303 commented on backend/src/main/resources/application-flywayTest.yml
> +>>>>>>> origin/develop
이 부분 제거해줘야될 것 같아요!

2022-08-30 09:43 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +@AutoConfigureMockMvc
이 어노테이션을 별도로 추가해준 이유가 있을까요?

2022-08-30 09:43 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
로깅을 afterCompletion일 때가 아닌 preHandle에서 처리해주면 어떤 이점이 있나요?
궁금해서 질문드려요!

2022-08-30 09:43 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +                objectMapper.readTree(cachingRequest.getInputStream())
해당 부분은 어떠한 이유로 바뀌게 된건지 궁금합니다!

2022-08-30 09:43 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/CustomCachingRequestWrapper.java
> +public class CustomCachingRequestWrapper extends ContentCachingRequestWrapper {
커스터마이징한 이유가 궁금합니다!

2022-09-13 05:55 UTC, Seungpang requested changes
알렉스 수정하시느라 고생하셨습니다!
제가 남긴 코멘트 한번 확인해주세요.
일단 저 부분을 신경써야 할 것 같아서 request changes하겠습니다 ㅠㅠ

2022-09-13 05:55 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
```suggestion
        final CustomCachingRequestWrapper cachingRequest = WebUtils.getNativeRequest(request, ContentCachingRequestWrapper.class); 
        
        if (cachingRequest == null) {
            log.info("json형태의 데이터가 아닙니다");
            return;
        }
```

해당 CustomCachingRequestWrapper로 캐스팅하는 부분은 requset가 json데이터인걸 가정하고 하는 것 같습니다. 만약에 json데이터가 아니라면 ClassCastException이 발생할 것 같습니다. ex) MultipartFile이 담긴 form데이터 StandardMultipartHttpServletRequest나, restDocs에서 사용하고 있는 MockHttpServletRequest같은 데이터는 캐스팅 할 수 없습니다.

따라서 WebUtils를 활용해서 캐스팅할 수 있으면 해당 객체로 캐스팅하고 없다면 null을 반환시켜서 어떠한 후 작업을 처리해주는건 어떨까요?

2022-09-14 01:56 UTC, yxxnghwan commented on backend/src/main/resources/application-flywayTest.yml
> +>>>>>>> origin/develop
감사합니다! 👍

2022-09-14 02:25 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/document/TestSupport.java
> +@AutoConfigureMockMvc
MockMvc에서 리퀘스트 객체를 래핑하는 필터가 돌지 않아서 이런 저런 방법을 시도하던 중에 넣었던 코드인데 현재는 사용하지 않네요! 제거했습니다!

2022-09-14 02:28 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
핸들러 메서드를 실행하기 전에 요청정보를 찍히는게 더 자연스럽다고 생각했어요! 핸들러 메서드를 실행중에도 개발한 내용에 따라 여러 로그가 발생할 수 있는데, 요청정보 이후에 그 요청을 실행하다 찍히는 로그가 찍히는게 `이런 요청이 들어왔는데 이런게 발생했다.` 라는 식으로 읽힐 수 있는 것 같아서요! afterCompletion에서 찍게 되면 `이런게 발생했다. 이런이런 요청이 들어왔을 때` 이렇게 찍히는 것 같아서 부자연스럽다고 생각했었습니다. 타임라인상 요청을 먼저 찍는 게 좋아보입니다!

2022-09-14 02:31 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +                objectMapper.readTree(cachingRequest.getInputStream())
HttpServletRequest는 RequestBody를 인풋 스트림에서 읽어오도록 되어있어요! 스트림은 소모성이기 때문에 한번 읽고 나면 다시 읽을 수 없는데, 그 한번을 로깅에 써버리면 실제 핸들러메서드에서 바디를 읽을 수 없더라구요!
그래서 바디값을 한번 읽더라도 다시 읽을 수 있는 캐싱 래퍼를 사용해서 풀어내려 한건데, getContentAsByteArray()는 한번 사용된 바디를 캐싱해놓은걸 읽어오는 메서드입니다.
afterCompletion에서 찍을 때는 핸들러 메서드에서 바디를 사용하고 캐시된게 있으니까 잘 동작했지만, preHandle에서 찍을 땐 아직 바디를 사용하기 전이라 그냥 인풋 스트림을 사용하도록 바꾸었어요.

2022-09-14 02:33 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/CustomCachingRequestWrapper.java
> +public class CustomCachingRequestWrapper extends ContentCachingRequestWrapper {
위 코멘트의 답글에 이어지는 이유인데 getInputStream()을 사용해서 바디값을 읽고 나면 이후에 다시 사용했을 때 빈 인풋스트림을 읽게 됩니다. 그래서 첫 호출에서는 getInputStream()을 한 값을 캐싱한 후에 반환하고 두번 째 요청부터는 캐싱된 값으로 새 InputStream을 만들어 반환하도록 메서드 구현을 바꾸려고 커스텀 했습니다!

2022-09-14 02:35 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
문제 확인하고 코드 변경해봤는데 다시 한번 확인 부탁드려요!

2022-09-14 03:29 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
이해했습니다 감사합니다!
또 궁금한 점이 하나 있습니다.
ControllerAdvice에서 예외 관련 로깅을 띄우던데, 해당 로깅을 afterCompletion에서 대신 띄울 순 없는지 궁금해요.

추가로, ControllerAdvice에서 예외 관련 로깅을 호출한다면 ControllerAdvice에서 메서드 분리를 하는 것도 좋아보입니다! 로깅 관련 로직이 중복되는 것처럼 보여서요.

2022-09-14 03:58 UTC, asebn1 requested changes
코멘트 확인 부탁드려요

2022-09-14 03:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/LoggingInterceptor.java
> +        final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;
`final CustomCachingRequestWrapper cachingRequest = (CustomCachingRequestWrapper) request;` 코드에서 다른 타입으로 요청받을 경우 에러가 발생할 수 있지 않을까요?

2022-09-14 03:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/config/logging/CustomCachingRequestWrapper.java
> +    }
구조를 이렇게 가져간 이유가 있을까요?

2022-09-15 03:59 UTC, closed without merging