feat: 네이버 OAuth기능을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #433
Opened 2022-09-13 13:07 UTC by Seungpang

## 구현사항 
1. 네이버 Oauth 구현
+ 큰 흐름은 카카오 Oauth와 비슷합니다. 다만 조금씩 다른 부분들이 존재합니다. ex) state값이 필수인점 카카오는 필수가 아님

2. 기존 snake case -> `@JsonProperty`를 활용하여 camel case로 변경

3. 테스트 코드 추가 및 수정 

close #349

2022-09-14 07:21 UTC, kth990303 requested changes
수고하셨습니다!
제 컴퓨터가 이상한건지 시크릿창에서 localhost:8080 접속했을 때 네이버OAuth가 안뜨네요 😢 분명 index.adoc 미리보기에는 뜨는데 말이죠... 혹시 모르니 한번 확인 부탁드립니다.
몇 가지 코멘트 남겨드렸습니다. 확인 부탁드려요~

2022-09-14 07:21 UTC, kth990303 commented on backend/src/docs/asciidoc/auth.adoc
> +operation::auth-controller-test/naver-login[snippets='http-request,http-response']
`error.adoc`과 명세에 3016, 3017 에러로 네이버 OAuth 에러 명세도 추가해주면 좋을 것 같아요

2022-09-14 07:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +    public TokenResponseDto createTokenWithNaverOauth(final String authorizationCode, final String redirectUri,
해당 메서드가 `createToeknWithKakaoOauth` 밑에 있는 게 나아보입니다!
현재는 해당 메서드에서 사용되는 Private 메서드들이 해당 메서드보다 위에 있기도 하구요

2022-09-14 07:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        );
이건 사소하지만, kakao oauth 쪽에서는 DTO로 요청을 받고, naver oauth 쪽에서는 값들로 요청을 받고 있는데 통일되게 하는 건 어떤가요? 카카오를 바꾸든 네이버를 바꾸든 상관은 없어보입니다!

2022-09-14 07:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        return new TokenResponseDto(accessToken, memberId);
해당 메서드가 중복되는데 분리해볼 수 있을 듯하네요!

2022-09-14 07:21 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
> +        when(naverPlatformUserProvider.getPlatformUser(anyString(), anyString(), anyString())).thenReturn(platformUserDto);
라인이 넘어가네요. 개인적으론 `anyString()`이 아닌 `any()`로 넣어도 괜찮을 것 같은데 승팡 생각은 어떤가요?
```suggestion
        when(naverPlatformUserProvider.getPlatformUser(any(), any(), any())).thenReturn(platformUserDto);
```

2022-09-14 07:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/support/oauth/kakao/dto/KakaoUserResponse.java
> +        return kakaoAccount.getProfile()
👍

2022-10-02 08:42 UTC, asebn1 requested changes
컴플릿 나는 부분 해결하면 될 것 같습니다~

2022-10-02 08:42 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/exception/NaverAuthorizationException.java
> +    }
현재 구글 에러코드와 겹칠듯합니다! ㅎㅎㅎ

2022-10-20 07:01 UTC, closed without merging