[BE] queryDSL을 적용한다
woowacourse-teams/2022-nae-pyeon pull request #442
Opened 2022-09-16 12:12 UTC by kth990303

close #421 

이슈에 queryDSL 적용 구조, 트러블슈팅 및 쿼리 성능 개선 과정을 꼼꼼하게 적어놓았습니다.

노션에서 보시는 게 편하시다면 아래 링크를 클릭해주세요. 
https://clean-nutria-44b.notion.site/queryDSL-7c8bceed08564a3bb566578c2061488c

2022-09-20 05:58 UTC, asebn1 requested changes
고생 많으셨습니다! 코멘트 답 달아주시면 확인할게요!

2022-09-20 05:58 UTC, asebn1 commented on backend/build.gradle
> +//querydsl 추가 끝
주석 다는거 저는 괜찮은 것 같아요!

2022-09-20 05:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
> +}
`findById`를 명시해준 이유가 있을까요?

2022-09-20 05:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
다른 쿼리들은 엔티티와 직접 연관이 있어 재사용이 가능한데 `WrittenMessageResponseDto`는 재사용이 불가능해서 `JPAQueryFactory`만 가지는 별도의 클래스로 분리하자고 이야기 나왔던 것 같아요!
팀 컨밴션이긴 하지만 분리했을 때 구분된다는 장점도 있을 거 같고 
분리하지 않으면 custom에서 모두 관리하는구나로 생각할 수 있을 것 같아요

2022-09-20 05:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepository.java
> +    Optional<Rollingpaper> findById(final Long rollingpaperId);
여기도 `findById` 명시해야할까요?

2022-09-20 05:58 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
> +    }
강의에서 `BooleanBuilder`는 조건을 1개씩 쌓는 느낌으로 사용하고
함수로 1개씩 빼는 건 `BooleanExpression`를 적용할 수 있다고 알고있는데 
그때 영한님 인프런 답으로 BooleanBuilder 로 사용한 예시로 이렇게 쓰신거로 알고있는데
`BooleanExpression`로 함수를 만들었을 때 차이가 있을까요? 궁금해서 질문드립니다!

2022-09-20 05:58 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/repository/MemberRepositoryTest.java
>      @Autowired
👍

2022-09-20 06:22 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
> +    }
별 차이 없긴 합니다.
https://www.inflearn.com/questions/161280

2022-09-20 06:39 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepository.java
> +    Optional<Rollingpaper> findById(final Long rollingpaperId);
👍

2022-09-20 06:39 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepository.java
> +}
제거해도 되는데 놔뒀네요. 변경했습니다!

2022-09-20 06:47 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
일리가 있긴 한데, 이후에 요구사항 및 기능이 추가되어 querydsl을 사용하는 메서드가 추가될 가능성이 있다고 생각해요.
만약 그렇게 된다면 DTO용 별도의 클래스 + querydsl 클래스 + spring data jpa 인터페이스가 되어 오히려 구조가 복잡해질 것 같다는 생각이 들었어요. 

확실히 트레이드오프가 있다고 생각되는 부분이지만, 작업하다보니 저는 이 구조가 좀 더 깔끔한 것 같다는 생각입니다. 실제로 해당 메서드에서 사용되는 BooleanBuilder는 재사용이 가능하기도 하구요.

2022-09-20 08:52 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/rollingpaper/RollingpaperRepositoryImpl.java
> +    }
만약 파라미터로 넘겨진 값이 null이 될 수 있다면 BooleanExpression의 경우 삼항연산자로 별도로 처리해야 합니다.
BooleanBuilder의 경우는 해당 경우를 고려하지 않아도 됩니다. nullSafeBuilder 메서드로 처리해주기 때문입니다.

이후에 nullable = true인 값이 파라미터로 넘겨지는 경우를 별도로 따로 예외처리하기보단 BooleanBuilder를 사용해서 통일성있게, 그리고 이후에 불필요한 예외를 겪지 않을 수 있게 하면 좋을 듯 합니다!

2022-09-22 04:15 UTC, Seungpang approved these changes
케이 queryDSL 적용하시느라 고생하셨습니다!
queryDSL에 대해서 작성한 문서때문에 이해하기 쉬웠습니다.
queryDSL에 대해서 공부좀 해야겠네요 ㅠㅠ
aprrove하겠습니다.

2022-09-22 04:15 UTC, Seungpang commented on backend/build.gradle
> +	annotationProcessor "com.querydsl:querydsl-apt:5.0.0"
스프링 버전이 올라가면서 제가 공부할때랑 설정값이 달라졌네요!

2022-09-22 04:38 UTC, asebn1 approved these changes
고생하셨습니다!

2022-09-22 05:38 UTC, yxxnghwan approved these changes
케이 수고하셨습니다! 사소한 코멘트 적었고 쿼리dsl로 잘 마이그레이션 한 것 같아서 approve 할게요!

2022-09-22 05:38 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
해당 DTO의 소속도 정의해볼만 할 것 같네요. repository에서 조회를 위해 사용하는 dto인데 서비스 패키지에 포함되어있는 것 같아요!

2022-09-22 05:38 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
어떤 이유때문에 생긴 메서드인가요?!

2022-09-22 06:10 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
null 처리 때문입니다.

https://github.com/woowacourse-teams/2022-nae-pyeon/pull/442#discussion_r975070282

2022-09-22 06:11 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +    }
일리 있네요 나중에 회의를 해봐야될 듯 하네요

2022-09-22 06:13 UTC, merged