feat: 구글 OAuth기능을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #447
Opened 2022-09-19 05:55 UTC by asebn1

close #355 #248

2022-09-19 07:05 UTC, kth990303 requested changes
수고하셨습니다! 몇 가지 누락된 부분들 때문에 RC로 남겼습니다.

2022-09-19 07:05 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
> +    private GooglePlatformUserProvider googlePlatformUserProvider;
해당 AuthServiceTest에서는 `authService.createTokenWithKakaoOauth(tokenRequestDto)`만 테스트되고 있습니다. google createToken도 테스트 코드를 작성해보는건 어떤가요? 

AuthServiceTest 외에 AuthControllerTest도 마찬가지입니다.

2022-09-19 07:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +
카카오랑 완전히 동일한 로직인데 메서드 분리가 되면 좋을 것 같아요.

추가로, 조금 빡세긴 할 것 같지만 PlatformUserProvider 인터페이스를 만들어서 추상화하면 어떨까요?

2022-09-19 07:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/exception/GoogleAuthorizationException.java
> +        );
`errorCodes.adoc` 파일에 해당 에러코드 작성이 안돼있습니다.

2022-09-19 07:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/exception/GoogleResourceException.java
> +        );
해당 부분도 마찬가지로 `errorCodes.adoc` 파일에 작성이 안돼있습니다.

2022-09-19 07:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/controller/auth/AuthController.java
> +    }
`auth.adoc` 파일에 작성이 안돼있어요.

2022-09-19 20:18 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
> +    private GooglePlatformUserProvider googlePlatformUserProvider;
적용하겠습니다!

2022-09-19 20:28 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +
추상화 해보겠습니다~

2022-09-20 06:17 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +
생각보다 둘이 요구하는 정보들이 많이 달라서 공통로직이 꽤 묶이진 않는군요.. 확인했습니다 😄

2022-09-21 06:31 UTC, yxxnghwan approved these changes
수고하셨습니다!

2022-09-21 06:31 UTC, Seungpang approved these changes
제로 고생하셨습니다.
스네이크 케이스를 카멜케이스로 바꾸면 좋을 것 같아요
이거는 나중에 리팩토링하면 되니까
approve하겠습니다.

2022-09-21 06:31 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/support/oauth/dto/GoogleAccessTokenResponse.java
> +    private String id_token;
스네이크 케이스를 `@JsonProperty`를 사용해서 카멜케이스로 만들면 좋을 것 같습니다.

2022-09-21 06:32 UTC, merged