feat: API 커스텀 훅을 분리하고 에러 바운더리 설정을 추가
woowacourse-teams/2022-nae-pyeon pull request #454
Opened 2022-09-19 12:09 UTC by prefer2

## 구현 사항
파일 변경이 많아 중간 pr로 한 번 리뷰를 하고 작업을 이어나가기로 했습니다
### useQuery 분리
```tsx
import { useQuery } from "@tanstack/react-query";

import { QueryOptions } from "@/types/api";

type QueryKey = readonly unknown[];

export default function useCustomQuery<T>(
  queryKey: QueryKey,
  queryFn: () => Promise<any>,
  options?: QueryOptions
) {
  return useQuery<T>(queryKey, queryFn, {
    ...options,
    useErrorBoundary: !options?.onError,
  });
}
```

편한 error 처리를 위해 useCustomQuery를 만들었습니다(이름은 useQuery로 할지 다른 이름으로 할지는 더 고민해봐야 할 것 같습니다)
이 함수의 options 중 onSuccess의 타이핑이 고민인데요, 우선은 any로 설정했는데(unknown으로 하면 에러남) 혹시 더 좋은 의견이 있다면 제안해주세요!!

### api 커스텀 훅
useQuery와 관련된 모든 함수들을 커스텀 훅으로 분리하였습니다. 네이밍의 경우 useRead~의 컨벤션을 따르기로 했습니다.
options의 경우 컴포넌트에서 언제든지 추가로 넣을 수 있도록 모든 커스텀훅에서 optional로 가질 수 있게 했습니다.
기존에 컴포넌트 단의 onError를 모두 제거하였고, 커스텀훅에서 에러를 받아 에러바운더리로 넘어가도록 하였습니다.

closed #437

2022-09-19 14:32 UTC, soyi47 requested changes
도리 고생이 많습니다... 화이팅! 🥰

오프라인으로 논의한 내용
- API 커스텀 훅에서 onError, onSuccess 핸들러 로직 작성
- 커스텀 useQuery, useMutation 제거

위 내용과 함께 코멘트 달아놓은 부분들 확인해주세요!

2022-09-20 12:44 UTC, soyi47 requested changes
도리~ 너무 너무 고생했어요. 대공사 잘  진행해줘서 고맙습니다.  👍👍👍
어질어질할테니 코멘트만 남긴 부분들만 수정 부탁합니다. 😵
다음 작업은 제가 이어 받아서 진행할게요! 

1. 대문자로 시작하지 않는 타입 이름들이 있습니다. 수정 부탁해요~
2. 몇 군데서 커스텀 훅과, 커스텀 훅에서 반환한 mutate 함수가 중복되게 인자를 받고 있어요. 어디서 인자를 주면 좋을지 통일하면 좋겠어요. mutate vs useMutation을 반환하는 커스텀 훅
3. 사용하지 않는 타입, 혹은 타입으로 분리가 필요한 아이들이 있습니다.

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useCreateMemberRolliingpaper.tsx
> +      postMemberRollingpaper({ teamId, title, addresseeId }),
커스텀 훅에서 teamId를 이미 가지고 있어서, mutate 함수가 teamId를 인자로 받을 필요는 없어요!
CreateMemberRollingpaperVariable에는 title, addresseeId만 있으면 될 것 같습니다.

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
> +    ({ title }) => {
1. 타입 이름이 대문자로 시작하도록 수정해주세요~
2. 여기서도 teamId를 mutate 함수 인자로 넣어줬네요. 이렇게 사용할거면 커스텀훅에서 인자로 teamId를 안 받는 게 나을 것 같은데요. 
커스텀훅에서 teamId 받고 mutate 함수에서는 인자로 teamId 안 주기 vs 커스텀 훅에서 teamId 안 받고 mutate 인자로 teamId 주기. 둘 중 하나로 통일합시다!

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/hooks/useCreateMessage.tsx
> +    ({ content, color, anonymous, secret }) => {
여기도 마찬가지입니다.
커스텀훅에서 rollingpaperId를 이미 가지고 있는데 mutate에서 다시 인자를 받는군요..!

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/RollingpaperPage/hooks/useDeleteMessage.tsx
> +  });
1. 타입 대문자!
2. rollingpaperID 인자를 어디에서 받을까? mutate vs custom hook

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamCreationPage/hooks/useCreateTeam.tsx
> +}
타입 이름 대문자로 시작하기!

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/NicknameEditModalForm.tsx
절대경로 쓸까요?

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/hooks/useCreateInviteLink.tsx
> +  } = useMutation<PostTeamInviteTokenResponse, AxiosError, Team["id"]>(
속성 하나만 가지는 객체 데이터 타입도 따로 정의해주기로 했으니까 인자 타입을 따로 정의해주는 게 더 일관성 있을 것 같아요!

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/hooks/useCreateTeamMember.tsx
> +};
1. 여기도 mutate 인자 타입을 따로 정의해주는 게 일관성 있을 것 같아요.
2. 컴포넌트가 언마운트되고 refetchQueries가 실행되어서 문제가 있었던 걸로 기억합니당. refetch 후에 onClickClose를 실행하면 전에 있었던 에러가 해결될 것 같아요.
3. onClickCloseButton을 내려받는 건... 좀 생각해봅시다 하핳

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/hooks/useUpdateTeamNickname.tsx
> +  });
여기도 인자타입, onSuccess 내부 로직 순서 정리가 필요하겠네요.

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/index.tsx
> +import useReadTeamDetail from "./hooks/useReadTeamDetail";
절대경로를 사용할까요?!

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/types/apiResponse.ts
>  }
밑에 같은 응답 타입이 있는 것 같아요. 아마 With가 중간에 빠져서 헷갈린 것 같은데, 아래에 있는 응답 타입을 제거할까요?

2022-09-20 12:44 UTC, soyi47 commented on frontend/src/types/api.ts
> +}
일단 지금은 Options를 안 받기로 했으니 제거할까요?

2022-09-21 01:25 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
> +    ({ title }) => {
하나의 매개변수만 받는 경우에는 값만 받는걸로 수정했습니다!
저도 훅으로 빼면서 이게 혼란스럽더라고요....! 오프라인으로 토의해본 결과 커스텀 훅에서 teamId받고 mutate 함수에서는 인자로 teamId안주기로 통일하기로 했습니다

2022-09-21 01:27 UTC, prefer2 commented on frontend/src/pages/RollingpaperPage/hooks/useCreateMessage.tsx
> +    ({ content, color, anonymous, secret }) => {
여기도 대소문자가 틀려있네요 😅 이런거 잡아주는 린트는 없낭...

2022-09-22 02:31 UTC, prefer2 commented on frontend/src/pages/TeamDetailPage/hooks/useUpdateTeamNickname.tsx
> +  });
오 이건 생각 못했는데 앞으로 문제가 발생할 수 있겠네요!! 좋아요 좋아요

2022-09-22 06:43 UTC, merged