feat: 데이터베이스 이중화 기능을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #484
Opened 2022-09-22 13:05 UTC by Seungpang

### 기능 내용
일반적인 트랜잭션 로직에서는 Connection 객체를 먼저 확보하고 트랜잭션 동기화를 진행하는데

`@Transactional(readonly = true)`옵션에 따라 db를 분기하려면 트랜잭션 동기화를 먼저 마치고

해당 트랜잭션이 readOnly가 있냐 없냐에 따라 다른 Connection 객체를 가져야 하기 때문에 작업 순서를 변경해야 합니다.

그래서 트랜잭션 시작시에 Connection Proxy 객체를 리턴하고 실제 쿼리가 발생할 때 데이터 소스에서 올바른 Connection 객체를 얻도록
했습니다.

더 자세한 내용은 wiki로 작성해서 주말중에 업로드 하겠습니다!

close #435

2022-10-02 09:10 UTC, asebn1 reviewed
모르는 부분이 많아서 질문드려봅니다 ㅎㅎ

2022-10-02 09:10 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +    }
해당코드가 connection pool을 설정하는 것으로 이해해도 될까요?

2022-10-02 09:10 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +    }
key가 DatabaseType (트랜잭션 readOnly에 따른 다른 key반환)
위에서 미리 만들어놓은 커넥션 풀(source, replica)가 value, 
미리있어야 되기에 순서를 DependsOn을 해주는 것으로 이해했습니다!
 
`routingDataSource.setTargetDataSources(dataSources);` 을 통해 CUD / R 을 구분해주는데 
`routingDataSource.setDefaultTargetDataSource(sourceDataSource());` 도 필요한 코드인가요?
구분이 된다면 `routingDataSource.setDefaultTargetDataSource(replicaDataSource());` 해도 동작은 똑같이 되는건가요?

2022-10-02 09:15 UTC, asebn1 commented on backend/docker/docker-compose.yml
> +  db-source:
버전3은 무슨뜻인가요!?

2022-10-05 08:11 UTC, yxxnghwan approved these changes
안녕하세요 승팡! 어려운 작업 너무 잘해주셨네요!
감명깊었습니다! 질문 몇개 남겼어요!

2022-10-05 08:11 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +@EnableTransactionManagement
스프링 부트에선 기본설정으로 되는 것으로 알고 있는데 해당 설정파일에서 명시해주신 이유가 있을까요?!

2022-10-05 08:11 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +        dataSources.put(DatabaseType.REPLICA, replicaDataSource());
타입 명시하는 건 어떨까요?
```suggestion
        final HashMap<DatabaseType, DataSource> dataSources = new HashMap<>();

        dataSources.put(DatabaseType.SOURCE, sourceDataSource());
        dataSources.put(DatabaseType.REPLICA, replicaDataSource());
```

2022-10-05 08:11 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java
> +import org.springframework.jdbc.datasource.lookup.AbstractRoutingDataSource;
DB 동적 라우팅을 위한 클래스네요 배워갑니다!👍

2022-10-05 08:11 UTC, yxxnghwan commented on backend/src/main/resources/application.yml
> +        driver-class-name: org.h2.Driver
로컬에선 source와 replica모두 기존 인메모리 h2를 바라보고 있네요!
도커 mysql을 써서 로컬 테스트가 가능하게 해주셨는데 해당 설정파일도 추가해주시면 실행 옵션만 바꿔서 쉽게 이중화를 테스트해볼 수 있을 것 같아요!

2022-10-09 09:47 UTC, kth990303 requested changes
수고하셨습니다 😄 
application.yml에서 h2를 참조하고 있는 것 때문에 RC 남겼는데 해당 부분에서 승팡의 의견이 궁금합니다.
그 외에 추가적인 궁금증을 코멘트로 남겼는데 답변 부탁드립니다!

2022-10-09 09:47 UTC, kth990303 commented on backend/src/main/resources/application.yml
> +        driver-class-name: org.h2.Driver
알렉스의 코멘트에 동의합니다!
mysql로 바껴야될 것 같아요.

2022-10-09 09:47 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/DatabaseType.java
> +    ;
큰 상관은 없지만 `,`가 추가로 들어가있네요
변경의 유연성을 위해 남겨두신 건가요?

2022-10-09 09:47 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java
> +    protected Object determineCurrentLookupKey() {
```suggestion
    protected DatabaseType determineCurrentLookupKey() {
```

2022-10-09 09:47 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java
> +    }
스프링에서 이러한 기능까지 편리하게 제공해주는군요! 👍

2022-10-09 09:47 UTC, kth990303 commented on backend/docker/replica/my.cnf
> +relay_log_purge=ON
릴레이 로그를 삭제해주는 옵션이 맞을까요?
이 옵션을 ON으로 해준 이유가 궁금합니다!

2022-10-11 05:26 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +}
application.yml파일에서 예약된 key값을 자동으로 DataSource 빈을 자동으로 생성해주는게 맞습니다.
다만 해당 코드에서 ConfigurationProperties속성으로 yml파일의 설정값을 주입해서 직접 datasource빈을 직접 생성해준겁니다.
ex) sourceDataSource, replicaDataSource

Primary로 우선순위를 지정하는게 맞습니다. 
따라서 애플리케이션이 구동될때 DataSource 타입의 빈들이 여러개입니다.
그래서 dataSource()로 구동되게 하기 위해서 Primary를 해준겁니다.

2022-10-11 05:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/RoutingDataSource.java
> +}
정확합니다!

2022-10-11 05:27 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +    }
해당 코드는 위에 설명했다시피 yml파일의 설정 정보를 가져와서 bean을 생성해준겁니다.
connection poll과는 거리가 멀다 할 수 있습니다.

2022-10-11 05:36 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +    }
위에 있는 AbstractRoutingDataSource와 관련이 있는데요
어떠한 key 값으로 Datasource를 선택할지 결정합니다.

1. LookUpKey를 가져와 본다
2. LookUpKey에 해당하는 dataSource가 있다면, 해당 Datasource를 선택하여 가져온다
3. 만일 존재하지 않는다면, defaultDataSource를 사용한다
4. default조차도 없다면 예외가 발생한다

이러한 이유 때문에 defaultDataSource를 설정해 주는겁니다.
사실 존재하지 않을 확률이 나타난다면 CRUD 모두 가능한 sourceDataSource가 합당하고 생각합니다.

2022-10-11 05:39 UTC, Seungpang commented on backend/docker/docker-compose.yml
> +  db-source:
version 3는 Compose Version을 의미합니다.
쉽게 말하면 docker compose파일의 버전이라고 보시면됩니다.
크게 1, 2, 3이 있는데 각각 지원하는게 다릅니다
자세한 내용은 [공식문서](https://docs.docker.com/compose/compose-file/compose-versioning/) 참고해보는게 좋을 것 같네요

2022-10-11 05:40 UTC, Seungpang commented on backend/src/main/resources/application-develop.yml
> +        maximum-pool-size: ${MAX_CONNECTION_POOL_SIZE}
이 부분은 merge가 된 다음에 성능테스트를 해보면서 실험해봐야겠네요 😄

2022-10-11 05:59 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +        dataSources.put(DatabaseType.REPLICA, replicaDataSource());
setTargetDataSources(dataSources) 부분에서
해당 메서드의 매개변수가 <Obejct, Object> 타입이라 타입을 명시할 수 없습니다.. ㅠㅠ

2022-10-11 06:00 UTC, Seungpang commented on backend/src/main/resources/application.yml
> +        driver-class-name: org.h2.Driver
해당 부분을 mysql로 세팅할 경우 어느정도 학습비용이 있다고 판단해서 h2로 했지만
대부분의 의견이 mysql로 변경하는게 좋다고하니 변경하겠습니다. 한번 다같이 설정하는 시간 가지면 좋을 것 같네요!

2022-10-11 06:00 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/support/db/DatabaseType.java
> +    ;
변경의 유연성을 위해 남겨둔거인데 
지금 와서 생각해보니 추가될 일이 있을까 싶네요
삭제하도록 하겠습니다.

2022-10-11 06:04 UTC, Seungpang commented on backend/docker/replica/my.cnf
> +relay_log_purge=ON
네 필요없는 릴레이 로그는 삭제가됩니다.
만약 해당 옵션이 켜져있지 않으면 릴레이 로그가 지속적으로 쌓이게되어서
용량이 꽉 차버리는 문제가 발생할 수 있습니다.

2022-10-11 07:35 UTC, kth990303 commented on backend/src/main/resources/application.yml
> +        driver-class-name: org.h2.Driver
네 그러면 우선 approve 하겠습니다!

2022-10-11 07:36 UTC, kth990303 approved these changes
이후에 Mysql 설정하는 시간 같이 가지면 될 것 같아서 approve로 바꿔놓을게요

2022-10-11 07:49 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +@EnableTransactionManagement
기본설정인줄 이번에 알았네요 제거했습니다!

2022-10-11 07:49 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/config/DataSourceConfig.java
> +@ComponentScan(basePackages = {"com.woowacourse.naepyeon"})
AutoConfiguration의 부분에서 해결되는 부분이여서 제거했습니다.

2022-10-17 05:06 UTC, asebn1 approved these changes
고생하셨습니다!

2022-10-17 05:13 UTC, merged