feat: 엔티티 연관관계를 개선하고 복잡한 쿼리를 리팩터링한다.
woowacourse-teams/2022-nae-pyeon pull request #500
Opened 2022-10-01 08:06 UTC by kth990303

close #492 
close #436 

## 구현사항
- 492번 이슈의 솔루션 5를 이용하여 Rollingpaper 엔티티 및 테이블에 TeamParticipation 추가
  - 모임 롤링페이퍼, 개인 롤링페이퍼를 작성할 때에도 TeamParticipation이 추가된다는 단점 존재
  - TeamParticipation의 Member, Team이 null이 될 수 있도록 변경
- **기존에 존재하던 데이터들의 Rollingpaper에 TeamParticipation 데이터 추가는 아직 하지 않음.**
- 본인이 작성한 메시지 querydsl로 마이그레이션 및 리팩터링
- 컨트롤러 테스트에서 테스트격리 안되던 버그 수정

## 집중하여 리뷰받고 싶은 부분
- flyway 컬럼 추가가 제대로 됐는지
- 엔티티 리팩터링 과정이 괜찮은지
- 누락된 테스트가 있는지

## 리뷰 시 주의사항
- flyway_schema_history에 기존 데이터가 존재한다면 충돌이 일어날 수 있음. 이 경우 flyway_schema_table의 V0.4.2 이후 컬럼들을 지워주어야 함.
```sql
delete from flyway_schema_history where version = ? # 0.4.3 또는 0.4.4는 지워줘야함.
```

2022-10-05 06:41 UTC, yxxnghwan requested changes
지금 구조에선 확실히 team은 뺄 수 있을 것 같아요! teamParicipation과 작성자, 수신인에 대해선 다시 백엔드 전체가 구조고민을 해봐야할 것 같네요!

2022-10-05 06:41 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
> +
중복되는 연관관계들이 있는 것 같아요! 엔티티와 밸류에 대해서 고민해보고
특정 경우엔 id를 밸류로 취급하는 방법을 선택해서 연관관계를 단순화시킬 수 있을 것 같은데
같이 한번 고민해봐도 좋겠네요!

2022-10-05 06:41 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +
공백이 두 줄이네요!

2022-10-05 08:36 UTC, Seungpang requested changes
케이 복잡한 querydsl에 대해 코멘트 남겨봤습니다
한번 확인해주세요!

2022-10-05 08:51 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                message.rollingpaper.team.name,
```suggestion
             team.name,
```
위의 코멘트와 연결되는 부분입니다. 이렇게 위와 같이 변경하면 좋을 것 같아요!
구조가 변경된다면 querydsl 구현하실때 참고하면 좋을 것 같아요

2022-10-06 06:21 UTC, kth990303 commented
<img width="725" alt="image" src="https://user-images.githubusercontent.com/57135043/194228903-7cda3830-6bd5-4889-8538-8c95e882942b.png">
회원이 가입한 모임 목록을 조회하는 쿼리에서도 `cross join`이 발생하고 있었습니다.
해당 부분 또한 개선하겠습니다.

또한, join이 나감에도 불구하고 join이 명시적이지 않았던 쿼리들을 명시적으로 수정하겠습니다.

2022-10-06 07:56 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/rollingpaper/Rollingpaper.java
> +
모임에게 롤링페이퍼를 작성할 때 TeamParticipation을 더미데이터로 넣는 것보단 null을 넣는 것이 좋다고 생각했습니다. (정의에 어긋나는 데이터, 불필요하게 늘어나는 데이터)
근데 이렇게 하면 Team이 사라지면 모임에게 롤링페이퍼 작성 시 member, teamParticipation 모두 null이어서 팀을 찾을 수가 없더라구요. 

사실 위 부분이 굉장히 의견이 갈리는데 나중에 회의해보는게 좋을 거 같아요.

### 롤링페이퍼 필드: id, title, recipient, **team, member, teamParticipation**
현재 구조: 모임에게 롤링페이퍼 작성 시
```
team - 롤링페이퍼 대상 (팀)
member - null

teamParticipation 
1. 모임롤링페이퍼 작성용 더미 teamParticipation 생성
vs 
**2. null (모임과 null 사이의 관계는 존재하지 않으므로)**
```

### 1. Team을 제거할 경우
-`TeamParticipation: 모임-회원 중간테이블 역할`이라는 정의 자체가 깨지게 됩니다.

### 2. Team을 제거하지 않고 teamParticipation에 null을 넣을 경우
- **addressee nickname을 찾을 때 다시 복잡해짐 (모임 롤링페이퍼, 개인 롤링페이퍼 시에 teamParticipation이 null이므로 닉네임을 표시할 수가 없음.)**
- null이 많아진다는 문제점

Entity 대신 entity_id를 넣는 방법도 있을 듯하지만, 이 방법은 이후에 회의해봅시다!

2022-10-06 08:21 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                .fetch();
원래 모임롤링페이퍼 생성 시 teamParticipation이 추가되면서 `new TeamPartcipation(team, null, team.getName())` 더미데이터를 넣어줌으로써 찾아올 수 있었는데, 모임 롤링페이퍼 생성 시 teamParticipation에 null을 넣는 것으로 바꾸면서 해당 쿼리가 바뀌게 됐어요.

모임 롤링페이퍼 작성 시에 teamParticipation이 존재하지 않을 수 있어 left outer join이 필요해져서 inner join + left outer join으로 진행되게 됐습니다.

2022-10-06 08:24 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                .fetch();
근데 혹시 해당 쿼리 테스트 어떻게 하셨는지 알 수 있을까요?
dev, prod와 local 연관관계가 달라 dev, prod erd 환경에선 해당 쿼리를 날릴 수가 없을 거 같은데 cost 테스트 어떻게 하셨는지 궁금하네요...

2022-10-07 13:48 UTC, asebn1 requested changes
쿼리도 깔끔하게 짜주시고 테스트도 꼼꼼히 짜주셨네요 👍 
고생많으셨습니다
코멘트 확인해주시면 바로 approve하겠습니당

2022-10-07 13:48 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +
확실히 queryDSL 장점이 보이네요 👍

2022-10-07 13:48 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                .where(isAuthorIdEq(authorId));
where절에 null이들어가면
```java
final JPAQuery<Long> countQuery = queryFactory
                .select(message.countDistinct())
                .from(message)
```
가 실행되리라 예상되는데 올바른 방향인가요? 궁금해서 질문드립니다~

2022-10-07 13:48 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/teamparticipation/TeamParticipationRepositoryCustom.java
👍

2022-10-07 13:48 UTC, asebn1 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
>      private Member member;
Rollingpaper의 TeamParicipantion 자체에 null이 들어간다고 이해했는데, team과 member에 `nullable = false`를 제거한 이유를 알 수 있을까요? 테스트에도 `new TeamParticipation(team, null, team.getName());`가 있네요!
저는 다음과 같이 이해했습니다

**모임대상 롤링페이퍼**
- team: 값존재
- member: null
- teamParticipation: null

**멤버대상 롤링페이퍼**
- team: 값존재
- member: 값존재
- teamParticipation: 값존재

2022-10-07 14:05 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                .where(isAuthorIdEq(authorId));
authorId가 null일 경우 위와 같이 됩니다.

isAuthorIdEq(authorId), 즉 메시지를 작성하지 않은 사용자가 조회할 경우에 전체 메시지 개수를 조회하지 않을까 걱정돼서 남긴 코멘트가 맞을까요?

이 경우는 메시지가 0개로 제대로 나오게 됩니다. where절 자체가 null이 아니고 `BooleanBuilder`이 제대로 들어가기 때문입니다.
```java
@Test
@DisplayName("본인이 작성한 메시지들을 찾는다.")
void findAllByMemberIdAndPageRequest() {
    final Rollingpaper rollingpaper2 =
            new Rollingpaper("AlexAndKei2", Recipient.TEAM, team, member);
    rollingpaperRepository.save(rollingpaper2);

    final List<Message> messages = new ArrayList<>(); // 메시지 작성 안함
    final List<WrittenMessageResponseDto> expected = List.of(); // 기대값 존재하지 않음

    final Page<WrittenMessageResponseDto> writtenMessageResponseDtos =
            messageRepository.findAllByAuthorId(author.getId(), PageRequest.of(0, 5));
    final List<WrittenMessageResponseDto> actual = writtenMessageResponseDtos.getContent();
    assertAll(
            () -> assertThat(writtenMessageResponseDtos.getTotalElements()).isEqualTo(0), // 메시지 0개로 잘 나오는지
            () -> assertThat(actual)
                    .usingRecursiveComparison()
                    .isEqualTo(expected)
    );
}
```
<img width="897" alt="image" src="https://user-images.githubusercontent.com/57135043/194571609-1a1b25aa-0879-43e5-9c27-7f156410e701.png">
해당 테스트가 제대로 통과하는 것을 확인할 수 있습니다.
근데 아예 카운트 쿼리가 나가지를 않네요. 이건 좀 신기하네요

혹시 몰라서 메시지를 author가 전부 작성하게 하고, 아무것도 작성하지 않은 member의 아이디로도 조회해봤는데 의도한대로 잘 작동되는 것을 확인했습니다.

2022-10-07 14:09 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/TeamParticipation.java
>      private Member member;
제로가 이해한 상황이 맞습니다!

맨처음에는 모임대상 롤링페이퍼로 작성 시 teamParticipation에 null이 아닌 더미데이터를 넣어줬었는데, 수정하면서 null로 바뀌게 됐어요. 아마 수정 과정에서 놓친 부분인 것 같아요.

테스트 코드 및 해당 부분 수정하겠습니다

2022-10-07 14:45 UTC, asebn1 approved these changes
고생하셨습니다! 👍 👍

2022-10-07 15:28 UTC, yxxnghwan approved these changes
고생하셨어요!

2022-10-07 17:18 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/message/MessageRepositoryImpl.java
> +                .fetch();
로컬에 더미데이터 넣고 테스트 했습니다. 해당 쿼리로 테스트 했을때 문제가 없네요!
![스크린샷 2022-10-08 오전 2 18 43](https://user-images.githubusercontent.com/37570657/194614179-dd40e87e-e8e1-4f72-be6a-bd2a5012062e.png)

2022-10-07 17:19 UTC, Seungpang approved these changes
케이 구현하시느라 고생하셨습니다! 👍

2022-10-07 17:20 UTC, merged