feat: 메인페이지 UI를 개선
woowacourse-teams/2022-nae-pyeon pull request #501
Opened 2022-10-01 11:15 UTC by prefer2

## 구현 사항
- 메인페이지에서 바로 롤링페이퍼 작성이 가능하도록 버튼을 추가했습니다
- 내가 참가하는 팀, 내가 받은 롤링페이퍼는 최대 5개까지만 보여집니다
- 받은 롤링페이퍼의 리스트 경우 높이를 고정해놓았습니다
- 내가 참가한 팀에서 더보기를 눌렀을 경우의 페이지는 아직 구현하지 않아 메인페이지로 이동하도록 하였습니다
- 아직 개인롤링페이퍼의 경우 api가 나오지 않았고, 확정이 안된 느낌이라 따로 UI를 구분하지는 않았습니다
- 각각의 empty state의 경우에는 어떻게 해야할지 조금 고민이 됩니다.
- 훅 분리를 했는데 메인에서는 초기값(5개)만 가져오는 경우라 이를 네이밍에 포함해야할지 고민입니다(useReadInitialMyTeam 이런 식으로)

<img width="319" alt="스크린샷 2022-10-01 오후 7 59 05" src="https://user-images.githubusercontent.com/67692759/193406381-7606b05c-713e-4b26-8fbe-0e328ca1392e.png">

![스크린샷 2022-10-01 오후 7 59 12](https://user-images.githubusercontent.com/67692759/193406394-b5a8c8eb-b562-4751-a06c-7e9046cd7dc8.png)

#closed 499

2022-10-01 11:18 UTC, prefer2 commented
UI가 완전 바뀌어서 jest test가 통과를 안하네요... 이는 차후에 수정해보도록 하겠습니다 😅

2022-10-02 08:18 UTC, soyi47 requested changes
도리~ 예쁘게 잘 만들어줬네요. 👍👍👍
소소하게 리뷰 남겼습니다. 확인하고 코멘트 남겨주세요!

+) test는 통과하는 정도만 수정하고 머지 진행합시당!

2022-10-02 08:18 UTC, soyi47 commented on frontend/src/pages/MainPage/components/RollingpaperListItem.tsx
> +};
요 아이 MyPage의 롤링페이퍼 리스트 아이템이랑 완전 똑같을 것 같은데, 
components 하위 폴더에서 작성해서 두 페이지에서 모두 쓸 수 있게 하나의 컴포넌트로 관리하는 게 어떨까요?

2022-10-02 08:18 UTC, soyi47 commented on frontend/src/pages/MainPage/components/SectionHeader.tsx
> +};
more이 왜 string인가 했더니 더보기를 눌렀을 때 이동할 링크였네요.
moreLink 정도로 더 구체적인 이름이면 좋을 것 같아요!

2022-10-02 08:18 UTC, soyi47 commented on frontend/src/pages/MainPage/components/SectionHeader.tsx
> +  );
1. 여기 count에 0이 들어가면 falsy로 판단되어서,, StyledCount가 렌더링 되지 않아 검은색의 0으로 나타나네요.
한번 확인해봐주세요!

2. 개수 숫자의 하단 높이도 섹션 제목보다 아래쪽으로 들어가는데, 조금 더 위로 올려서 제목과 숫자의 하단 높이를 맞춰주면 어떨까요?


![image](https://user-images.githubusercontent.com/71116429/193444763-d883ca6d-63b7-459b-9179-5e3ca496d33b.png)

2022-10-03 04:36 UTC, prefer2 commented on frontend/src/pages/MainPage/components/RollingpaperListItem.tsx
> +};
반영 완료! 7bc1225

2022-10-03 04:39 UTC, prefer2 commented on frontend/src/pages/MainPage/components/SectionHeader.tsx
> +};
반영 완료! [8fa4987](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501/commits/8fa498742f9df069c0bb8123020e3621bc756ed5)

2022-10-03 04:48 UTC, prefer2 commented on frontend/src/pages/MainPage/components/SectionHeader.tsx
> +  );
1. 우선은 typeof(count) === 'number'로 확인했는데(타스덕분에 가능한 일이기는 합니다만) 혹시 더 좋은 방법 있으면 추천해주세요...!

2022-10-03 13:23 UTC, prefer2 commented
<img width="636" alt="스크린샷 2022-10-03 오후 10 21 52" src="https://user-images.githubusercontent.com/67692759/193588361-fe039619-19ff-47ca-a811-3e60f89850d3.png">


모임, 받은 롤링페이퍼 없을 때의 empty state를 추가했습니다!

2022-10-06 13:48 UTC, soyi47 approved these changes
도리~ 귀여운 Empty State UI까지 잘 만들어줬네요! 👍👍👍

이번에 남긴 리뷰는 필수 수정 요청은 아닙니다. 
읽어보고 수정 또는 유지하는 이유를 남겨주시면 확인 후 머지할게요.

위에 남겨준 코멘트에도 답변 남겼으니 같이 확인해주세요!

2022-10-06 13:48 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      </StyledTopButtonList>
StyledTopButtonList는 section이 아니어도 될까요? 같은 계층에서 section을 사용하고 있어서요!

2022-10-06 13:48 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      </StyledTopButtonList>
'롤링페이퍼 만들기'
'모임 만들기'
'모임 찾아보기'

문구가 주는 느낌을 맞춰보면 어떨까요?

2022-10-08 06:10 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +      </section>
좋은 생각인 것 같습니다. 지금은 전부 페이지단에서 해주고 있는데 앞으로 컴포넌트 단위로 서버 요청을 옮기는 방식을 생각해보면 좋을 것 같아요. 공통된 로직들이 많이 줄어들 것 같네요....!

2022-10-08 06:20 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +      </StyledTopButtonList>
<section>태그보다 <nav>태그로 묶는건 어떻게 생각하시나요?? 의미상 nav가 더 적절한 것 같아 nav로 수정해보았습니다! c4db951

2022-10-08 06:51 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +      </StyledTopButtonList>
바꿔보았는데요 뭔가 문자 길이가 달라서 아쉬운 것 같기도 하고... 어렵네요
줄바꿈을 억지로 주기 위해 split을 써서 변경해보았는데 혹시 더 좋은 방법이 있을까요...?

<img width="317" alt="스크린샷 2022-10-08 오후 3 51 34" src="https://user-images.githubusercontent.com/67692759/194694181-4f6a046c-6aeb-4985-9dea-417c6686d872.png">

[c03dcd4](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501/commits/c03dcd43ee1a688e92ed1ab0e6be4d1f60520818)

2022-10-08 15:57 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      </section>
다른 이슈에서 진행하는 방향으로 생각하시는 걸까요?

2022-10-08 16:30 UTC, soyi47 approved these changes
도리~ 고생했어요~! 👏👏👏

머지하러 들어왔는데, 질문과 아직 확인되지 않은 코멘트가 있네요..!
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501#discussion_r989088583 <- 여기 코멘트 확인 부탁해요!

답변 남겨뒀고, 컨벤션 관련해서 소소한 수정 요청있습니다.
이 부분들만 적용하고 호다닥 머지합시다~!

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      </section>
다른 이슈에서 진행하는 방향으로 생각하시는 걸까요?

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/components/RoundButtonWithDescription.tsx
> +}
컨벤션에 맞게 RoundButtonWithDescriptionProps로 이름을 변경하면 좋겠네요..!

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/components/LineButton.tsx
> +  extends React.ButtonHTMLAttributes<HTMLButtonElement> {}
interface로 잘 바꿔줬네요. 👍👍👍

컨벤션에 맞게 이름을 LineButtonProps로 바꾸는 게 어떨까요?

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/pages/MainPage/components/SectionHeader.tsx
> +
컴포넌트 Props의 타입은 ___Props를 사용하기로 했어요!

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +import RoundButton from "@/components/RoundButtonWithDescription";
RoundButton으로 import하는 이유가 있을까요? 지금까지는 정의한 이름과 동일하게 import 해온 걸로 알고 있어요!

2022-10-08 16:30 UTC, soyi47 commented on frontend/src/components/RoundButtonWithDescription.tsx
> +      </StyledDescription>
이미 StyledDescription에 `white-space: pre-wrap;`이 적용되어 있으니,
description에 들어오는 문자열을 template literal로 작성하고, 내부에 개행문자를 작성하면 split하지 않아도 줄바꿈이 적용됩니다!

```
// MainPage index.tsx
<RoundButton
  key={1}
  description={`롤링페이퍼\n만들기`}
  onClick={handleRollingpaperStartClick}
>
  📜
</RoundButton>
```

```
// RoundButtonWithDescription.tsx

...
<StyledDescription>
  {description}
</StyledDescription>
```

2022-10-08 16:31 UTC, soyi47 commented on frontend/src/pages/MainPage/index.tsx
> +      </StyledTopButtonList>
여기 코멘트에 작성해뒀습니다! https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501#discussion_r990661068

2022-10-09 11:51 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +import RoundButton from "@/components/RoundButtonWithDescription";
네이밍을 바꾸고 수정을 안했네요 🥲 수정했습니다 [85c766f](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501/commits/85c766fedb10ee8fb40a45bdfc018666db29bad5)

2022-10-09 12:03 UTC, prefer2 commented on frontend/src/components/RoundButtonWithDescription.tsx
> +      </StyledDescription>
쵝오 👍👍 [f609625](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501/commits/f60962547b06b17fd718e3f941f3c2252e6b6844)

2022-10-09 12:13 UTC, prefer2 commented
컨벤션을 잘 못지킨 부분들이 많았네요 🥲 관련된 부분 수정했습니다!
section 컴포넌트는 다음 이슈에 분리할까 하다 이번에 분리하는 것이 좋을 것 같아 분리했어요. 분리하니 보기도 좋아졌네요. 다만 기존처럼 hook 폴더에 관련 훅들을 몰아 넣는 것이 좋을지는 고민이 되네요. 의미있는 컴포넌트들은 파일로 만들고 내부에 style, component, hook을 넣어두는 것이 좋을지 지금처럼 모든 훅을 넣어두는 것이 좋을지는 앞으로 진행하면서 정리해보면 좋을 것 같네요!

2022-10-09 13:25 UTC, soyi47 requested changes
도리 고생했어요! 👍👍👍

오타와 UI가 예상과 다른 부분에 대해서만 남겼습니다~!

2022-10-09 13:25 UTC, soyi47 commented on frontend/src/components/LineButton.tsx
> +}: ButtonProps) => {
LineButtonProps ! 로 수정해주세요

2022-10-09 13:29 UTC, prefer2 commented on frontend/src/pages/MainPage/index.tsx
> +        >
아뇨 없어도 됩니다 😅

2022-10-09 13:31 UTC, prefer2 commented on frontend/src/pages/MainPage/components/MyTeamsSection.tsx
> +  overflow: scroll;
반영했습니다 [14bff3d](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/501/commits/14bff3d5dff9817aef2ddfbee235b3423e06ec79)

2022-10-09 13:42 UTC, soyi47 approved these changes
훨씬 예뻐졌네요~ 고생하셨습니다! 👏👏👏
남은 작업도 화이팅해서 예쁘게 개선해봅시다!

2022-10-09 13:43 UTC, merged