refactor: 에러 처리 구조를 개선한다.
woowacourse-teams/2022-nae-pyeon pull request #502
Opened 2022-10-03 18:18 UTC by soyi47

2022-10-04 05:59 UTC, prefer2 requested changes
소피아 고생 많았어요! 다만 지금 error page의 홈으로 이동하기 버튼 누를 시 제대로 동작을 하지 않고 있는 것 같아요. 이 부분 한 번 확인해주세요

https://user-images.githubusercontent.com/67692759/193745378-26010725-0283-43d0-895e-300f51eb7475.mov

2022-10-04 07:04 UTC, prefer2 commented on frontend/src/components/ErrorBoundary.tsx
> +    }
확인 완료! 잘 동작하네요 굿굿

2022-10-04 07:29 UTC, prefer2 commented
현재 MainPage 내부에 isError 구문이 있는데 이를 빼줘야 할 것 같습니다! 새로운 UI 구현하면서 빼주기는 했는데... 처리 순서가 좀 뒤죽박죽이 된 기분이네요
```tsx
 if (isError) {
    if (axios.isAxiosError(getMyTeamListError) && getMyTeamListError.response) {
      const customError = getMyTeamListError.response.data as CustomError;
      return <div>{customError.message}</div>;
    }
    return <div>에러</div>;
  }
```

2022-10-04 07:34 UTC, prefer2 commented on frontend/src/components/ErrorBoundary.tsx
> +      this.props.navigate("/login");
시도해보았는데 userProvider가 errorBoundary 내부에 있어서 어떻게 로그아웃을 시켜줘야할지 고민이네요. 과연 ErrorBoundary가 userProvider 내부에 있어도 괜찮은가? userProvider 자체로는 에러를 던지는 일이 없으니 괜찮을까요....?

2022-10-05 07:51 UTC, prefer2 commented
default onError 옵션에 errorHandler를 넘겨서 처리하도록 변경해보았습니다. 500대 이상의 에러와 AxiosError가 아닌 경우는 ErrorBoundary에서 처리해줄 수 있도록 했습니다. 

### 고민 -> 어떻게 로그아웃 시켜줄 것인가
UserProvider 내부에서만 logout을 할 수 있습니다. 현재 QueryClientProvider - ErrorBoundary - UserProvider 형식으로 이루어져 있어 이의 순서를 바꿔주어야하나 고민했습니다. UserProvider를 QueryClientProvider의 상위에 감싸기에는 useAutologin의 사용이 어려워집니다. 또는 이 모든 것을 App으로 옮겨 훅 사용이 가능하게 하더라도 setQueryClient사용이 불가능해져 전역적인 설정이 어렵습니다.

우선 생각나는 방법인 errorHandler에서 cookie를 지워주고, 이를 RequireLogin에서 getCookie로 확인 후 로그아웃 해주는 방식으로 진행했습니다. 저희가 생각했던 방법인 RequireLogin과 로직이 달라지는 것 같아(계속 getCookie를 해오는 상황) 더 좋은 방법이 없나 고민이 됩니다...!

MutationErrorHandler의 경우에는 어떻게 작성해주는 것이 좋을지도 고민입니다. 작성한 내용 외의 에러가 있을지는 잘 모르겠네요.  mutation의 경우 400, 401의 에러가 전부일 것 같아 두 에러에 대한 처리만 해주었습니다.

### 확인해본 결과
- 접근이 불가능한 롤링페이퍼(/teams/2/rollingpaper/3) -> 이부분 리다이렉트 해주는 teamId 찾는 방식도 더 좋은 방법이 없을지...
- 잘못된 토큰
- 토큰이 없을 때
- 500 에러

2022-10-09 13:01 UTC, soyi47 reviewed
에러 처리 개선해봤습니다~

아래 위주로 확인 부탁드립니다.

1. 구조 괜찮은지
2. 불필요한 변경 내역 없는지
3. 에러 처리 플로우가 잘 작동하는지
4. (커스텀 에러 코드와 메시지에 따라) 추가 에러 케이스 분류 필요 없는지 => API 명세 확인하며 체크 중입니다.

2022-10-09 13:35 UTC, prefer2 commented on frontend/src/components/ErrorBoundary.tsx
>      }
서버 에러를 과연 사용자가 알아야할까라는 고민이 드네요. 구글처럼 '더보기' 버튼을 통해 자세히 알려주는 것이 좋을 것도 같고...

![image](https://user-images.githubusercontent.com/67692759/194759430-4a76a8ae-cee5-4875-a22b-acc86461cf25.png)

2022-10-09 14:18 UTC, prefer2 requested changes
소피아 에러 관련 고민하느라 고생 많았어요. 에러처리 참 어렵네요...
조금 고민되는 점과 4013 에러 관련해서 동작이 제대로 안되고 있어 관련 내용 코멘트 달았습니다!

2022-10-09 14:18 UTC, prefer2 commented on frontend/src/hooks/useApiErrorHandler.tsx
> +        const teamId = requestUrlPaths.indexOf("teams") + 1;
![스크린샷 2022-10-09 오후 11 13 20](https://user-images.githubusercontent.com/67692759/194761668-44e0aa72-8557-4e46-9301-43c71f631154.png)

현재 관련 switch문이 동작하지 않고 있어요. ApiErrorResponse 타입과 실제 타입이 달라서 발생하는 문제인 것 같아요.

2022-10-09 14:18 UTC, prefer2 commented on frontend/src/hooks/useApiErrorHandler.tsx
> +        const teamId = requestUrlPaths.indexOf("teams") + 1;
적절하지 않은 id로 이동하고 있어요(2로만 이동). teamId가 아닌 teamI의 index를 구하는 과정인 것 같아요. 확인부탁드립니다.

2022-10-09 14:23 UTC, prefer2 commented
추가적으로 queryClient default option들을 어떻게 설정할까가 고민이 되네요. 지금은 `setQueryClientErrorHandler`로 에러 관련 처리만 해주고 있는데요, refetch관련 설정은 따로 해줄지 혹은 네이밍을 바꿔서 이곳에서 다 해줄지 고민해보면 좋을 것 같아요.

2022-10-09 14:26 UTC, soyi47 commented on frontend/src/App.tsx
> +  setQueryClientErrorHandler(apiErrorHandler);
useEffect는 어디 useEffect 말씀하시는 걸까요?

2022-10-09 14:32 UTC, soyi47 commented on frontend/src/components/ErrorBoundary.tsx
>      }
1. 저 페이지 직접 열어보신 건가요? 어떻게 접근하는지 몰라서 그러는데, Learn more에 어떤 정보가 있는지 알 수 있을까요?
2. 저는 다르게 준다면 페이지를 refresh하는 버튼만 추가하면 좋을 것 같아요. 도리는 어떻게 하고 싶으신가요?

2022-10-09 15:24 UTC, prefer2 commented on frontend/src/components/ErrorBoundary.tsx
>      }
1. 직접 열어본 것은 아니고 구글링해서 찾아보았습니다. Learn more를 누르면 관련 에러에 대한 코드가 나오는 것으로 알고 있습니다. 다만 저희 프로젝트에서 과연 이를 보여주는 것이 더 좋을까... 싶기는 하네요
2. 저도 refresh 버튼 정도가 좋은 것 같습니다!

2022-10-09 15:26 UTC, prefer2 commented on frontend/src/App.tsx
> +  setQueryClientErrorHandler(apiErrorHandler);
네네. 가장 먼저 처리가 되야하지 않을까 싶기도 하고 저도 이 부분을 에러를 직접 만들어서 한 번 확인해볼께요

2022-10-10 16:28 UTC, soyi47 commented on frontend/src/api/index.ts
> +        return errorStatus ? errorStatus >= 500 : true;
굿 변경했습니다~ https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/58e0aa4516f4e5131da7a212d12a3f317e23ca69

2022-10-10 16:30 UTC, soyi47 commented on frontend/src/hooks/useApiErrorHandler.tsx
> +        const teamId = requestUrlPaths.indexOf("teams") + 1;
https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/ce590f07de93b6d6575f7795ca93f44da3f188c9
1. 서버 요청의 응답으로 받는 경우는 errorCode를 string으로 사용하도록 변경했고요. 
2. 에러 핸들러에서는 number 타입으로 변경하여 사용하도록 했습니다.

2022-10-10 16:31 UTC, soyi47 commented on frontend/src/hooks/useApiErrorHandler.tsx
> +        const teamId = requestUrlPaths.indexOf("teams") + 1;
수정했습니다~ https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/7ea3adebcb7cd454c96568d8eed601ce12b92a43

2022-10-10 16:32 UTC, soyi47 commented on frontend/src/components/ErrorBoundary.tsx
>      }
생각해보니 에러 바운더리의 fallback UI에서도 새로고침은 필요한 것 같아서, ErrorPage에 새로고침 버튼을 추가해봤습니다. https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/644be53a53a9672d09a2a67c302469d30569b9a4

2022-10-10 16:33 UTC, soyi47 commented on frontend/src/components/ErrorBoundary.tsx
>      }
에러 바운더리의 fallback UI에서도 새로고침은 필요한 것 같아서, 
ErrorPage에 새로고침 버튼을 추가해봤습니다. https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/644be53a53a9672d09a2a67c302469d30569b9a4

2022-10-10 16:59 UTC, soyi47 reviewed
- 리뷰 반영하고 코멘트 남겨뒀습니다. 확인해주세요~
- 추가적으로 커스텀 에러 코드를 상수화하면서 다른 에러 케이스는 더 없는지 확인하는 작업이 필요합니다. 여기서 한번 끊고 다른 이슈로 진행해도 좋을 것 같은데 어떤가요?

### 질문에 대한 답변
> 추가적으로 queryClient default option들을 어떻게 설정할까가 고민이 되네요. 지금은 setQueryClientErrorHandler로 에러 관련 처리만 해주고 있는데요, refetch 관련 설정은 따로 해줄지 혹은 네이밍을 바꿔서 이곳에서 다 해줄지 고민해보면 좋을 것 같아요.

1. onError에 지정할 errorHandler의 경우 커스텀 훅을 통해 사용할 수 있는 기능들이 필요하기 때문에, setDefaultOptions를 사용해야 할 것 같습니다. 꼭 queryClient 생성 이후 설정해줘야 하는 상황이 아니라면, queryClient를 생성할 때 설정해주는 게 좋겠습니다. 굳이 이후에 주입해서 설정해줄 필요는 없는 것 같아요.
2. 그 전에 먼저 defaultOption 변경이 필요한지, 왜 필요한지, 어떻게 변경할지 논의가 필요하겠네요! 우선 지금은 setQueryClientErrorHandler로 충분하다고 생각하고요. 이후 변경이 필요하면 그때 변경하면 좋겠어요.

2022-10-10 17:01 UTC, soyi47 commented on frontend/src/App.tsx
> +  setQueryClientErrorHandler(apiErrorHandler);
이동했습니다~ https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502/commits/ff18890d92f2417818d932f6d331bf74d616c76a

useAutoLogin의 onError 설정 관련해서는 따로 코멘트 남겼습니다. https://github.com/woowacourse-teams/2022-nae-pyeon/pull/502#discussion_r991475071

2022-10-11 05:19 UTC, prefer2 commented on frontend/src/hooks/useAutoLogin.tsx
> +      },
useEffect로 옮겨도 이 부분은 어쩔 수 없겠네요. 특이한 경우이기 때문에 따로 onError로 선언을 해 주어도 괜찮을 것 같아요. 이 부분까지 defaultOption으로 해결하고자 한다면 useAutoLogin을 바꿔야할 것 같은데 지금 상황에서는 이 방법이 가장 좋은 것 같습니다.
- useAutoLogin이 언제 발생하는지 생각해보니 토큰 값이 존재할 때만이군요. 덕분에 auto login의 전반적인 플로우를 다시 생각해 볼 수 있었던 것 같습니다! 토큰값이 잘 못된 경우에만 발생하는 에러이니, 토큰 값만 지워줘도 괜찮은 것 같네요 👍👍

2022-10-11 05:23 UTC, prefer2 approved these changes
전반적인 에러 코드 정리와 꼼꼼한 주석덕분에 저도 실행하면서 에러들 쉽게 확인할 수 있었네요. 에러 핸들러 이름 나눈 부분 정말 좋은 것 같아요. 가독성 최고네요!
리뷰 반영된 부분들도 확인했습니다 😊 소피아 말대로 조금 더 자세한 에러 분리와 커스텀 메시지 작성은 따로 이슈를 작성해서 진행하는 것이 좋을 것 같아요. 차후에 진행하도록 합시다!
에러 처리에 대해 꾸준히 고민해 볼 수 있어서 좋은 시간이었습니다. 덕분에 다양하게 생각해 볼 수 있었던 것 같아요. 함께 고민해주고 코드에 이쁘게 반영해줘서 고마워요! 수고 많았습니당 😄

2022-10-11 05:26 UTC, merged