feat: 롤링페이퍼 생성 플로우 UI 구현
woowacourse-teams/2022-nae-pyeon pull request #514
Opened 2022-10-10 04:39 UTC by prefer2

## 구현 사항
- 전반적인 롤링페이퍼 생성 관련 플로우를 변경하였습니다
- 롤링페이퍼가 생성되면 생성된 롤링페이퍼로 이동하도록 변경했습니다. 기존에는 롤링페이퍼 페이지에서 PageTitleWithBackButton의 뒤로가기 버튼을 누르면 history(-1)이 되었지만 롤링페이퍼 링크 공유때 정상 동작하지 않기 때문에 이를 원하는 페이지로 이동하는 방식으로 변경했습니다.
- 팀 디테일 페이지에서 롤링페이퍼 추가 버튼(+)을 누르면 이미 팀이 선택된 상태로 롤링페이퍼 생성 페이지로 이동하도록 하였습니다. 팀의 아이디값은 search param을 통해 전달했습니다.

https://user-images.githubusercontent.com/67692759/194799504-9ef3471e-48fc-4534-9788-d0d1f4be7577.mov

https://user-images.githubusercontent.com/67692759/194799645-b7363d45-63f4-4002-8447-e4909e855374.mov

## 고민
- team id를 search param으로 주고 나니 전반적으로(메인에서 롤링페이퍼를 생성할때도) search param으로 선택한 값을 전달하는 것이 좋을지 고민입니다. 소피아의 생각은 어떤가요??
- 우선은 DotControler를 통해 뒤로가기는 혹은 앞으로 넘어가기는 구현하지 않았습니다. 필요하다고 생각된다면 추가하도록 하겠습니다.
- 좋은 문구가 생각이 나지 않아 가장 간단하게 작성했습니다. ui적으로나 문장 측면에서 좋은 의견이 있다면 알려주세요!

closed #509

2022-10-10 04:55 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/index.tsx
> +};
객체 형식으로 작성했는데요, 이를 각각의 state로 구현할지 지금과 같은 객체 형식으로 유지할지 고민입니다. step2도 객체형식이라 조금 보기 안좋은 것 같기도 하고... 소피아의 생각은 어떤가요??

2022-10-10 06:02 UTC, soyi47 requested changes
도리 잘 구현해주셨네요~ 훨씬 예뻐졌어요! 👏👏👏
우선 기능적으로 개선하면 좋을 부분들 그리고 질문 주신 코드 위주로만 빠르게 의견 남겨봤습니다!
확인해보시고 필요하다고 느낀 부분들 반영해주시고, 아닌 부분에 대해서는 의견 주세요~
코드 수준의 리뷰는 오늘 밤이나 새벽에 남겨보겠습니다~

#### 질문에 대하여
> team id를 search param으로 주고 나니 전반적으로(메인에서 롤링페이퍼를 생성할때도) search param으로 선택한 값을 전달하는 것이 좋을지 고민입니다. 소피아의 생각은 어떤가요??

1. 모임 상세 페이지에서 searchParam으로 teamID를 넘기는 건 필요한 일이라고 생각하고, 잘 사용했다고 생각해요. 아니면 navigate의 status를 사용하는 방법도 있긴 하겠네요. 그런데 메인 페이지에서 생성 플로우로 들어갈 때는 왜 필요하다고 느끼셨나요?? 그렇게 생각한 이유가 뭔지 궁금합니다. 저는 특별히 전달할 값이 없으면 param을 추가할 필요는 없는 것 같아요.

2. 지금 모임 상세 페이지에서 롤링페이퍼 생성 플로우로 넘어가면 모임 선택 step1이 보였다가 다음 step2로 넘어가는 게 보이는데요. 이 부분 바로 step2로 들어갈 수 있으면 좋겠어요.

> 우선은 DotControler를 통해 뒤로가기는 혹은 앞으로 넘어가기는 구현하지 않았습니다. 필요하다고 생각된다면 추가하도록 하겠습니다.

DotController의 dot을 클릭해서 앞뒤로 이동할 필요는 없지만, 페이지 좌우에 화살표 같은 버튼을 두고 이전 혹은 다음 step으로 이동할 수 있도록 하면 좋을 것 같아요. 더해서 searchParam으로 보여주는 step의 상태를 관리하면 뒤로가기 같은 기능을 지원할 수도 있겠네요. searchParam으로 step 상태를 관리하면 화살표를 구현하기 더 쉬울 수도 있고요.


#### 추가로...
- Step1, 2, 3는 모두 components 폴더에 들어가고, Dot controller 같은 아이들을 common component 로 들어가야 한다고 생각해요.

2022-10-11 13:21 UTC, soyi47 requested changes
도리~ 코드 수준 살펴보고 리뷰 드립니다~!
이전에 남긴 리뷰도 있어서 가볍게 훑어봤습니다.
확인해보시고 이전 리뷰와 함께 반영해주세요!
혹시 진행하면서 어려움 있다면 말씀해주세요. 👍

2022-10-11 13:21 UTC, soyi47 commented on frontend/src/components/PageTitleWithBackButton.tsx
>    };
뒤로가기 버튼인데 지정한 페이지로 이동한다는 게 좀 이상하게 느껴지는데요.
링크 공유에서 정상 동작하지 않는 건 뒤로 갈 페이지가 없기 때문이므로, 이 예외 케이스에 대한 처리를 추가하는 방식으로 해결해주는 게 맞다고 생각합니다.
to를 받아서 처리해주기 보다는 history가 없는 경우에는 메인으로 이동하도록 하면 어떨까요?
react-router-dom v5에서는 useHistory를 사용해서 위 방법이 가능했을 것 같은데, 지금 버전에서 가능한 방법은 찾아봐야 할 것 같아요.

2022-10-11 13:21 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/MyTeamCard.tsx
> +};
메인 페이지의 MyTeamCard와 같다면, Page/components 폴더가 아닌 src/components에서 두고 두 페이지에서 가져다 쓸 수 있도록 하는 게 어떤가요?

2022-10-11 15:21 UTC, prefer2 commented on frontend/src/components/LabeledInput.tsx
> +  labelText?: string;
Label이 없는 input을 사용하고 싶어서 옵셔널로 바꿔보았습니다. 이럴려면 네이밍도 바뀌어야할 것 같네요. 
지금 Labeled~로 시작하는 컴포넌트들이 많은데요, Label 컴포넌트를 따로 만들고 Input, Radio등의 컴포넌트와 조합해서 쓰는건 어떨까요???

2022-10-11 15:23 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/MyTeamCard.tsx
> +};
동의합니다. 이전 Main 페이지관련 PR이 머지되기 전에 작업한 내용이라 우선은 따로 컴포넌트를 만들어서 사용했습니다.

2022-10-11 15:38 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/components/RecipientBox.tsx
> +    <StyledRecipientBox type={type} onClick={onClick}>
수정했습니다 [eb0f962](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/514/commits/eb0f9622903d5d8d38c72081975c4bca213ea466)

2022-10-11 15:43 UTC, prefer2 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
> +}
1. 전반적으로 확인해보았는데 Variable로 되어있어서 우선 수정은 안하도록 하겠습니다. 만약에 컨벤션에 ...Args였으면 Variable로 바꾸는건 어떨까 싶습니다 
![스크린샷 2022-10-12 오전 12 42 56](https://user-images.githubusercontent.com/67692759/195137860-c3623734-dc97-4dde-84fd-83a2de877de1.png)

2022-10-11 15:45 UTC, prefer2 commented on frontend/src/components/PageTitleWithBackButton.tsx
>    };
백엔드에게 받았던 피드백을 반영해보았습니다. 저희가 데일리때 주로 링크로 롤링페이퍼를 주고 받게되는데요, 이때 뒤로가기 버튼을 눌렀을때 롤링페이퍼가 작성되고 있는 팀으로 이동하면 좋겠다라는 의견이 있었습니다.
저도 관련해서 찾아봤는데 오히려 v6에서 history관련을 다루는 것이 난감하더라고요 🥲 조금 더 찾아보고 소피아가 제안해준 방법이 가능할지 적용해보겠습니다.

2022-10-11 18:12 UTC, prefer2 commented
> 그런데 메인 페이지에서 생성 플로우로 들어갈 때는 왜 필요하다고 느끼셨나요?? 그렇게 생각한 이유가 뭔지 궁금합니다. 저는 특별히 전달할 값이 없으면 param을 추가할 필요는 없는 것 같아요.

아래의 소피아 답과 동일한데요, 뒤로가기나 상태로 관리하기 용이하지 않을까라는 생각이었습니다. 

> Step1, 2, 3는 모두 RollingpaperCreationPage/components 폴더에 들어가고, Dot controller 같은 아이들을 common component 로 들어가야 한다고 생각해요.

차후에 페이지 내 컴포넌트 분리 방식은 논의가 필요할 것 같습니다. DotController의 경우 아직 사용처가 롤링페이퍼 생성밖에 없어서 이곳에 넣어두었는데 common으로 뺐습니다. Step들도 RollingpaperCreationPage/components로 이동했습니다.

2022-10-11 18:18 UTC, prefer2 commented
### Step 이동 버튼 추가
![스크린샷 2022-10-12 오전 3 13 18](https://user-images.githubusercontent.com/67692759/195168050-652968c8-9aeb-4164-baf4-1bb670d0bf75.png)
![스크린샷 2022-10-12 오전 3 13 25](https://user-images.githubusercontent.com/67692759/195168070-d930d22b-ca7c-4d58-bbea-cc3dbde19ccf.png)

앞으로 가기, 뒤로 가기 버튼을 추가했습니다. 버튼들은 조건을 만족할때만 활성화됩니다.
좌우로 움직이면서 이전 값을 확인하고 싶을 것 같아 선택한 값들이 표시되도록 했습니다. 다만, 모임/개인 선택부분은 뒤로가기가 불가능한 점 팀을 변경했어도 이가 변경이 안되는 점은 수정이 필요합니다.

### 팀 디테일페이지에서 롤링페이퍼 생성 플로우
기존에는 step2를 바로 보여주려고 했습니다. 하지만 이를 구현하는데 있어서 렌더링과 ref의 적용시점의 차이가 있다는 문제가 발생했습니다. Ref값 대입이 첫번째 값 렌더링 이전에 일어납니다. pageRef.current 값을 확인해보면 다음과 같습니다.
![image](https://user-images.githubusercontent.com/67692759/195168586-cf8cb730-0222-4f46-9487-256472a6e36f.png)

기존의 플로우를 유지하고 싶었기 때문에 새로운 페이지를 만들지 않았습니다. 선택된 팀을 보여줘서 플로우를 타도록했습니다.
![스크린샷 2022-10-12 오전 3 16 52](https://user-images.githubusercontent.com/67692759/195168763-e61f5c73-3d9f-49de-a1e2-cf9cbddc5494.png)

2022-10-12 00:15 UTC, soyi47 commented on frontend/src/components/LabeledInput.tsx
> +  labelText?: string;
라벨이 없는 input을 사용하고 싶으면 네이밍을 바꾸는 것보다는, Input 컴포넌트를 따로 만드는 게 맞다고 생각합니다.
분리하고 조합해서 쓰는 방식으로 다시 정리하는 일에는 동의합니다. 우선 이번에는 옵셔널로 두고 사용하고, 분리하는 작업은 다른 이슈로 진행할 때 옵셔널 제거 빠트리지 않도록 한번 챙겨봐주세요.

2022-10-12 00:21 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useCreateTeamRollingpaper.tsx
> +}
커스텀 훅 분리하면서 바꿔두셨군요... 😅
Variable이 적절한지는 조금 더 고민해보고 싶네요. 아직 Args로 작성되어 있는 곳도 있고요. 이 부분 다시 논의해보시죠.

2022-10-12 00:25 UTC, soyi47 commented on frontend/src/components/PageTitleWithBackButton.tsx
>    };
뒤로 갈 페이지가 없을 때에 현재 url path를 확인하고, 그에 맞게 페이지를 이동시켜주는 방법도 있을 것 같아요. team이 path에 있으면 team으로 이동시켜 줄 수 있겠죠?

어쨌든 뒤로가기 버튼 동작의 예외 처리를 해주는 방식이 좋지 않을까 생각합니다. 직접 이동할 경로를 다 지정해주는 건 뒤로가기 버튼의 의미와도 맞지 않고 사용자 예상 동작과도 다르게 작성할 수도 있을 것 같아요.

2022-10-12 00:40 UTC, soyi47 requested changes
추가 논의 사항은 따로 이슈로 분리해서 진행하면 좋겠습니다.
머지하려고 했는데, 잘못 변경된 부분이 있네요.

1. App.tsx에 에러 처리 관련 코드가 지워졌습니다. develop 머지하면서 잘못된 것 같아요.
2. 좌우 이동 화살표가 들어갔는데, 여기서 예외 상황 처리가 잘 안 되어 있는 것 같아요. step2 내에서 멤버를 선택했을 때 받는 사람을 바로 고르게 되는 것도 조금 어색한 느낌이 있고요. 
편의를 위해 화살표를 제공하면서 생기는 문제인데,,, 우선 화살표 이동을 막아서 배포하고 다시 정리해볼까요?

2022-10-12 00:40 UTC, soyi47 commented on frontend/src/App.tsx
> +          <Suspense fallback={<div>Loading..</div>}>
App.tsx에서 에러 처리 관련 코드들이 변경되었네요.
merge 과정에 문제가 있었던 것 같습니다.

2022-10-12 02:13 UTC, merged