feat: 리프레시 토큰 관련 API 구현
woowacourse-teams/2022-nae-pyeon pull request #525
Opened 2022-10-11 15:54 UTC by yxxnghwan

- 리프레시 토큰 도메인 구현
- 기존 로그인 API시 리프레시 토큰도 같이 생성돼서 반환됨
- 리프레시 토큰이 3개 이상 유지중일 때 또 로그인 요청이면 오래된 거 삭제해서 3개 유지
- 리프레시 토큰으로 엑세스 토큰 갱신 요청시 리프레시 토큰의 기간이 2일 이내로 남았으면 기간을 7일로 재설정
- 도메인 규칙상 만료 기간이 도메인 클래스 내부에서 설정되는데.. 만료 데이터 삭제 테스트가 까다롭다보니 리플렉션과 mokito를 써서 테스트 짰습니다...
- 멤버에 양방향 매핑 잡아놨는데 안잡아놓으면 멤버 삭제 테스트가 모조리 터지길래 캐스케이드 옵션 때매 잡았어요

close #508

2022-10-11 17:02 UTC, kth990303 requested changes
리프레시 토큰 빠르게 구현해주셨네요 👍 
수고하셨습니다.
맨 위 코멘트 2개 때문에 RC 남겨봤고, 그 외 코멘트들은 사소한 것들이에요.
코멘트 남겨주시면 감사하겠습니다!

2022-10-11 17:02 UTC, kth990303 commented on backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
> +        assertThat(findRefreshToken).isEmpty();
`AuthControllerTest`에서 assert문으로 검증까지 해주셨군요.

다만 restdocs를 위한 document 테스트 부분이라 해당 부분을 AcceptanceTest에 작성해도 괜찮을 것 같은데 알렉스 생각은 어떤가요?

2022-10-11 21:06 UTC, asebn1 requested changes
알렉스 수고하셨습니다~
앞서 케이가 리뷰를 잘해주어서 리뷰반영되면 approve하겠습니다!

2022-10-11 21:06 UTC, asebn1 commented on backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
> +        assertThat(findRefreshToken).isEmpty();
저도 document 테스트 부분같아서 통일하는게 좋아보입니다!

2022-10-12 01:52 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +        }
동의합니다!

2022-10-12 02:02 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
> +                .get();
이것도 동의합니다!

2022-10-12 02:09 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/service/AuthServiceTest.java
> +                        .doesNotThrowAnyException(),
한줄로 줄이는게 더 간지나네요!

2022-10-12 02:12 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +                .limit((long) memberRefreshTokens.size() - (MAX_REFRESH_TOKEN_SIZE - 1))
어플리케이션 로직상에서는 3개 이상으로 저장될 일이 없어서 1로 잡아도 논리적으로는 문제가 없는데,
혹시나 DB에 직접 접근해서 리프레시 토큰을 생성하거나 하는 경우에선 무결성 문제가 생길 가능성이 있어서 2개 빼고 나머지 다 지워라 라는 로직을 짰는데요
케이 의견은 어떠신가요?

2022-10-12 02:12 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +                .collect(Collectors.toList());
변경 가능성이 적을 수록 좋긴 하죠! ㅎㅎ

2022-10-12 02:13 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
> +                .limit((long) memberRefreshTokens.size() - (MAX_REFRESH_TOKEN_SIZE - 1))
확실히 그럴 수도 있을 것 같아요.
가독성이 조금 애매하긴 한데 이후에 논의해보면 좋을거같아요

2022-10-12 02:13 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/service/AuthService.java
>      private Long createOrFindMemberId(final PlatformUserDto platformUser) {
메서드 순서 한번 손 볼게요!

2022-10-12 02:17 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/repository/refreshtoken/RefreshTokenRepositoryCustom.java
> +    long deleteExpired(final LocalDateTime deleteTime);
제 생각은 리포지토리의 관점에선 affectedRow를 리턴해주는 게 좋을 것 같아요!
사용하는 클라이언트 입장에선 그 값을 쓰는 안쓰든 선택할 수 있게요!

2022-10-12 02:17 UTC, yxxnghwan commented on backend/src/test/java/com/woowacourse/naepyeon/document/AuthControllerTest.java
> +        assertThat(findRefreshToken).isEmpty();
인정합니다! 저 검증문은 지우겠습니다!

2022-10-12 08:58 UTC, Seungpang requested changes
알렉스 구현하시느라 고생하셨습니다.
앞에서 리뷰를 잘해주셔서 코멘트 약간 남겼습니다
한번 확인해주세요!

2022-10-12 08:58 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/invitecode/InviteCodeRepositoryImpl.java
> +                .where(inviteCode.expired.before(deleteTime))
해당 삭제 조건으로 expired가 존재하는데 주기적으로 삭제한다 해도
사용자가 많아진다면 삭제할때 풀테이블 스캔때문에 db 락이 걸리지 않을까 싶습니다. 해당 부분을 Index로 잡는건 어떨까요?

2022-10-12 08:58 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/refreshtoken/RefreshTokenRepositoryImpl.java
> +                .where(refreshToken.expiredTime.before(deleteTime))
해당 부분도 마찬가지로 index를 잡는게 좋아보여요

2022-10-12 08:58 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/repository/refreshtoken/RefreshTokenRepositoryTest.java
> +class RefreshTokenRepositoryTest {
꼼꼼한 테스트 추가 👍

2022-10-13 01:54 UTC, asebn1 approved these changes
고생하셨습니다!

2022-10-13 02:09 UTC, merged