feat: 메세지 좋아요 기능을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #527
Opened 2022-10-11 19:37 UTC by asebn1

close #515 

1. MessageService 테스트에서 여러 테스트를 넣다보니 repository 테스트와 결국 중복되는 것 같아 service 테스트에 집중했습니다
2. `existsByMemberIdAndMessageId` 의 경우 https://jojoldu.tistory.com/516 를 참고하여 쿼리성능을 개선했습니다

2022-10-11 23:07 UTC, Seungpang requested changes
제로 구현하시느라 고생하셨습니다.
몇가지 실수들이 보여서 그 부분만 반영해주시면
바로 approve 하겠습니다

2022-10-11 23:07 UTC, Seungpang commented on backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryImpl.java
> +                .where(messageLike.memberId.eq(memberId).and(messageLike.messageId.eq(messageId)))
해당 조건에 memberId, messageId가 사용되는데 이 두개를 인덱스 잡아야하지 않을까요?
해당 테이블에 데이터가 많이 쌓이면 금방 문제가 될거같아요

2022-10-11 23:07 UTC, Seungpang commented on backend/src/test/java/com/woowacourse/naepyeon/acceptance/MessageAcceptanceTest.java
> +    void cancelLikeMessageWithRollingpaper() {
꼼꼼한 테스트 작성 👍

2022-10-12 01:34 UTC, yxxnghwan approved these changes
고생하셨습니다!

2022-10-12 01:34 UTC, yxxnghwan commented on backend/src/docs/asciidoc/errorCodes.adoc
>  |===
예외케이스 추가 👍

2022-10-12 01:34 UTC, yxxnghwan commented on backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryImpl.java
> +    }
exists 성능 최적화 👍

2022-10-12 01:36 UTC, kth990303 approved these changes
수고하셨습니다.
실시간 코드리뷰 해서 잘 반영됐을 거 같아 approve 합니다!

2022-10-12 01:36 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/domain/message/MessageLike.java
> +        @Index(name = "message_rollingpaper_index", columnList = "member_id, message_id")
인덱스명을 수정하셔야될 것 같아요

2022-10-12 01:36 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryImpl.java
> +        Integer fetchOne = queryFactory
```suggestion
        final Integer fetchOne = queryFactory
```

2022-10-12 01:36 UTC, kth990303 commented on backend/src/main/java/com/woowacourse/naepyeon/repository/messagelike/MessageLikeRepositoryImpl.java
> +    }
👍

2022-10-12 01:55 UTC, Seungpang approved these changes

2022-10-12 01:57 UTC, merged