fix: [FE] UserProfile에서 이름 수정 후 엔터를 눌렀을 때 새로고침 되는 버그를 해결한다.
woowacourse-teams/2022-nae-pyeon pull request #569
Opened 2022-10-15 09:07 UTC by soyi47

## 작업 내용
### 핵심 개선사항
- 기존의 `handleEditSaveButtonClick`을 form의 submit handler로 주도록 변경했습니다. 이때 핸들러 이름을 `handleUserProfileEditFormSubmit`으로 변경했습니다.

### 추가 UI 관련 개선
- UserProfile 영역의 레이아웃을 정리했습니다. 불필요하게 감싸고 있는 div 태그를 정리하고, flex로 내부 컴포넌트의 정렬을 더 알아보기 쉽게 수정했습니다.
- 사용자 이름을 보여주는 영역, 사용자 이름을 수정하기 위한 Input의 크기를 키웠습니다. 사용자 이름 최대 길이가 길어지면서, 이름을 길게 작성하는 경우 UI가 어색해졌더라고요. 긴 사용자 이름에도 대응할 수 있도록, 해당 영역들의 가로 길이를 키웠고, 그 과정에서 수정 버튼을 아래로 보내봤습니다.

## 논의하고 싶은 부분
- 사용자 이름 변경을 테스트해보다가 UI가 어색해져서 같이 수정해봤는데요. 도리는 다른 의견일 수 있을 것 같아요. 확인해보고 의견주세요!

2022-10-16 04:36 UTC, prefer2 requested changes
연필 아이콘보다 훨씬 알아보기 좋고 이름이 길어져도 이쁜 UI가 되었네요 👍👍👍

왜인지는 모르겠지만 margin이 앞에만 들어가 있더라고요 뒤쪽에도 같이 넣어주거나 아애 빼주는건 어떨까요??

<img width="522" alt="스크린샷 2022-10-16 오후 1 32 03" src="https://user-images.githubusercontent.com/67692759/196018220-9ff2fda2-f54a-4f88-9241-a87558772864.png">

모바일에서는 괜찮은데 데스크탑에서는 이름 수정 부분이 너무 긴 것 같아요(대부분의 사용자들이 이름을 10자 이내로 작성하는 것을 생각해보면) max-length를 지정해주는건 어떤가요??

![스크린샷 2022-10-16 오후 1 35 30](https://user-images.githubusercontent.com/67692759/196018344-9087bc96-639a-485f-ad93-619d7005de2d.png)

2022-10-16 04:36 UTC, prefer2 commented on frontend/src/pages/MyPage/components/UserProfile.tsx
>  import Pencil from "@/assets/icons/bx-pencil.svg";
사용하지 않는 import문은 제거해줍시다!

2022-10-16 04:36 UTC, prefer2 commented on frontend/src/pages/MyPage/hooks/useUpdateUserProfile.tsx
> +  return useMutation<null, AxiosError, UpdateUserProfileVariable>(
저는 이거 계속 까먹게 되던데 굿굿

2022-10-18 15:55 UTC, soyi47 commented on frontend/src/pages/MyPage/components/UserProfile.tsx
>  import Pencil from "@/assets/icons/bx-pencil.svg";
사용하고 있는 것... 같아요!

2022-10-18 15:57 UTC, soyi47 reviewed
도리~ 제안해주신 부분들 수정했습니다!
확인부탁드려요~

2022-10-18 15:57 UTC, soyi47 commented on frontend/src/pages/MyPage/components/UserProfile.tsx
> +  margin: 24px 10px;
margin 값이 상하, 좌우로 일정하도록 변경했습니다.

2022-10-18 15:57 UTC, soyi47 commented on frontend/src/pages/MyPage/components/UserProfile.tsx
> +  }
input 너비를 반응형으로 줬습니다!

600px 이하에서는 100%
600px ~ 960px 구간에는 70%
960px 이상에서는 50%로 지정했습니다~

2022-10-18 16:13 UTC, prefer2 approved these changes

2022-10-18 16:13 UTC, merged