feat: refresh token 도입
woowacourse-teams/2022-nae-pyeon pull request #570
Opened 2022-10-15 11:59 UTC by prefer2

## 구현 사항
- 로그인 시 cookie에 refresh token을 저장합니다.
- 로그아웃 시 refresh token 삭제 요청을 보냅니다. cookie에 있는 refresh token을 삭제합니다.

### AccessToken 재요청
- 401 에러의 3011(올바르지 않은 토큰), 3012(토큰의 유효기간이 만료) 에러의 경우 accessToken을 제요청합니다. `retry: 0`으로 변경하고 확인하는 것을 추천합니다(default option에 대해서는 논의가 안되었다고 생각되어 수정하지는 않았습니다.) refreshToken이 존재하지 않는 경우에는 로그아웃, 존재하는 경우에는 이를 사용하여 재요청합니다. 이후 accessToken이 전달될 시 refetch를 합니다.
- 3013(토큰의 secret key가 변조됐습니다)는 해킹의 우려가 있는 경우라 판단되어 로그아웃하도록 했습니다.

### 고민
- 현재 queryClient의 stale 값들을 `refetch`하고 있습니다. `retry`를 하고 싶었으나, 적절한 방법을 찾지 못했습니다.
- 원하던 방법은 error시 retry 멈추기 -> AccessToken 재요청 -> retry 다시 시도 였습니다. retry 관련 옵션들을 찾아보았으나 적절한 방법을 찾지 못했네요 🥲 `GET`요청 전에 accessToken이 만료된 경우에는 정상 동작하지만, `POST`나 `DELETE` 동작은 없었던 일처럼 처리됩니다. 다른 때에는 괜찮을 것 같은데 메시지 작성중에 accessToken이 만료되고 완료를 누를 시 메시지가 사라지게 되어 이 부분이 고민입니다. ([참고한 retry관련 공식문서](https://tanstack.com/query/v4/docs/guides/query-retries))
- useCreateLogout의 위치를 상단의 hook 폴더에 위치하도록 했습니다. 적절한 위치를 찾지 못해 가장 상단에 넣어두었습니다. context 폴더 내에 따로 hook 폴더를 만드는 것이 좋을지 지금의 위치가 괜찮을지 고민입니다.

closed #562

2022-10-15 17:43 UTC, soyi47 requested changes
우선 소소한 코멘트 남깁니다. 
궁금한 부분들에 대해서는 아래에 정리해뒀어요. 
확인해보시고 수정할 부분 있으면 말씀해주세요~

context 관련해서는 일단 1차 리뷰 한번 마무리하고 다시 자세히 볼게요.
고생하셨어요! 👍

> 3013(토큰의 secret key가 변조됐습니다)는 해킹의 우려가 있는 경우라 판단되어 로그아웃하도록 했습니다.
잘 챙겨주셨네요! 👍

> 현재 queryClient의 stale 값들을 refetch하고 있습니다. retry를 하고 싶었으나, 적절한 방법을 찾지 못했습니다. 원하던 방법은 error시 retry 멈추기 -> AccessToken 재요청 -> retry 다시 시도 였습니다. retry 관련 옵션들을 찾아보았으나 적절한 방법을 찾지 못했네요 🥲 GET요청 전에 accessToken이 만료된 경우에는 정상 동작하지만, POST나 DELETE 동작은 없었던 일처럼 처리됩니다. 

1. 갱신된 accessToken이 돌아오면 stale 상태들을 refetch하고 있네요. 왜 refetch가 아닌 retry를 하고 싶었나요? 
retry는 '요청이 실패한 경우'에 에러 처리로 바로 넘어가기 전에 몇 번이나 더 시도해볼지에 대한 설정이라고 알고 있어요.
retry가 끝나고 이미 accessToken 재요청이라는 에러 처리 단계로 넘어갔으니 다시 retry 하는 일은 불가능할거라 생각합니다.

2. 그럼에도,,, 도리가 왜 refetch가 아닌 retry를 하려고 했을까? 생각해보면... 
아마 새로운 토큰이 돌아왔을 때, 기존에 토큰 만료 응답이 돌아왔던 요청을 다시 시도해서, 그 사이에 토큰이 갱신되는 걸 사용자는 알아채지 못 하는 정도로, 사용자의 동작 흐름을 유지하고 싶었던 것 같아요.

토큰 만료 에러 처리에서 호출하고 있는 renewalToken(mutate)가 onSucess에서 보냈던 요청을 재요청하는 방식을 고민해봐야할 것 같아요.
1. renewalToken(mutate)의 인자로 성공 핸들 로직 받고, onSuccess에서 호출하기
2. renewalToken(mutate)의 인자로 refetch할 쿼리의 key값들을 받고, 그 함수들만 refetch하기
당장은 요 방법들이 생각납니다. 

도리 의견 공유해주세요~

2022-10-15 17:43 UTC, soyi47 commented on frontend/src/context/UserContext.tsx
> +interface loginProps {
대문자가 되어야겠네요.

2022-10-15 17:43 UTC, soyi47 commented on frontend/src/hooks/useCreateRenewalToken.tsx
> +    postRenewalTokenVariable
`...Request`의 경우 하나만 필요한 경우 따로 정의를 안 하는 것으로 알고 있는데요. 저는 Variable도 동일한 방식이 좋을 것 같아요.
도리 생각은 어떤가요?

2022-10-15 17:43 UTC, soyi47 commented on frontend/src/hooks/useCreateRenewalToken.tsx
> +  const { mutate: renewalToken } = useMutation<
return useMutation으로 변경해주세요~

2022-10-15 17:43 UTC, soyi47 commented on frontend/src/pages/GoogleRedirectPage/index.tsx
> +interface googleOauthLoginVariable {
대문자로 시작해야겠네요..!

2022-10-17 03:51 UTC, prefer2 commented
> renewalToken(mutate)의 인자로 성공 핸들 로직 받고, onSuccess에서 호출하기

이 방법도 고민이었는데요, customError에 어떤 에러였는지를 실어서 보내고 이를 다시 호출하기 정도만 생각이 나더라고요
```tsx
 // 여기다 onSuccess 로직을 실어서 보내자
 // requestApi(() =>
 //   appClient.[requestMethod](requestUrl, requestData)
 // );
 renewalToken(refreshToken);
```
제가 간단하게 생각한 방식은 다음과 같아요. 주석처리된 부분을 함수로 만들어서 renewalToken에게 전달하기 입니다.

> renewalToken(mutate)의 인자로 refetch할 쿼리의 key값들을 받고, 그 함수들만 refetch하기
당장은 요 방법들이 생각납니다.

2번 방법은 `queryClient.refetchQueries({ stale: true });`로 이미 실행하고 있다고 생각해요! get을 제외한 post, update, delete에 대한 처리를 1번에서 해준다면 get에 대한건 refetch를 사용해주면 된다고 생각했습니다

2022-10-18 07:52 UTC, soyi47 commented on frontend/src/util/cookie.ts
> +  )}; max-age=${maxAge}; path=/`;
👍

2022-10-18 07:53 UTC, soyi47 commented on frontend/src/hooks/useCreateLogout.tsx
> +};
useMutation을 바로 반환할까요?

2022-10-18 07:53 UTC, soyi47 commented on frontend/src/hooks/useCreateRenewalToken.tsx
> +  return useMutation<PostRenewalTokenResponse, AxiosError, string>(
👍

2022-10-18 07:54 UTC, soyi47 commented on frontend/src/context/UserContext.tsx
> +    logoutRefreshToken(refreshToken);
logoutRefreshToken이라는 표현이 좀 어색한 것 같아요. 🤔

2022-10-18 07:55 UTC, soyi47 commented on frontend/src/api/member.ts
> +  );
굿~ 👍 
msw 모킹을 추가해주면 어떨까요?

2022-10-18 15:05 UTC, prefer2 commented on frontend/src/context/UserContext.tsx
> +    logoutRefreshToken(refreshToken);
`deleteRefreshToken`으로 변경했습니다! [73b9e94](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/570/commits/73b9e9484572973599075a78e1a702a163bb2d9e)

2022-10-18 15:45 UTC, prefer2 commented on frontend/src/hooks/useCreateRenewalToken.tsx
> +          queryClient.refetchQueries({ stale: true });
와우 맞네요! 추가해주었습니다 [67fa23f](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/570/commits/67fa23f3795238df93601160ba6e49486c0affd8)

2022-10-18 18:13 UTC, prefer2 commented
## 주요 변경 사항
- postMutate, putMutate, deleteMutate를 만들어 renewal token의 onSuccess에서 실패한 요청을 재시도할 수 있도록 하였습니다. 우선은 한 파일에서 진행하였으며 괜찮은 방법이라 여겨지면 따로 파일분리를 하도록 하겠습니다.
- `useCreateRenewalToken`의 `postRenewalTokenVariables`부분이 기존의 컨벤션과 맞지 않아 고민입니다. post에는 refreshToken 값만 쓰이고, useCreateRenewalToken을 선언할 시에는 mutateFunc을 알 수가 없어 일어나는 일입니다. 이에 대한 소피아의 의견이 궁금합니다
- 메시지 작성, 메시지 수정, 메시지 삭제에 대한 테스트를 해보았습니다. 현재 롤링페이퍼 메시지 부분이 수정 -> refetch로 수정된 부분 가져오기라 모든 onSuccess에서 refetchQueries를 하도록 하였습니다. 이 부분은 차후에 구조가 바뀐다면 불필요한 요청이 일어나지 않을 수 있도록 변경할 수 있을 것 같습니다.

2022-10-19 03:18 UTC, prefer2 commented on frontend/src/types/apiResponse.ts
>  }
충돌을 해결하면서 꼬인 것 같네요! 수정했습니다. [29a7dae](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/570/commits/29a7dae69b5a20a2b38888c594d5d33534f40e99)

2022-10-19 03:19 UTC, prefer2 commented on frontend/src/util/cookie.ts
> +}
굿굿 [a86ba4f](https://github.com/woowacourse-teams/2022-nae-pyeon/pull/570/commits/a86ba4f30655721c1d444daa368d95749d6edb68)

2022-10-19 06:16 UTC, prefer2 commented
- onSuccess에서 refetch를 해야하는데 이를 잊고 있었네요. 리액트 쿼리의 캐싱에 의해 refetch되고 있는거였는데 헷갈렸네요 🥲
- onSuccess 로직을 분리해서 전달해 줄 수 없는 관계로 get, post, update, delete에 상관 없이 reload를 하도록 변경하였습니다.
- 백엔드와 협의하에 refresh token관련 에러 코드를 추가했습니다. `3018번`으로 이 에러를 응답 받을 시 로그아웃이 됩니다

2022-10-19 09:56 UTC, soyi47 approved these changes
Refresch Token 적용 고생하셨습니다! 👍👍👍

2022-10-19 09:57 UTC, merged