feature: 롤링페이퍼 정렬/필터링 기능을 구현한다.
woowacourse-teams/2022-nae-pyeon pull request #571
Opened 2022-10-15 17:09 UTC by soyi47

## 작업 내용
- 모임 롤링페이퍼 조회 로직을 수정했습니다. 요청 url의 searchParams에 order와 filter를 추가했습니다.
- 모임 상세 페이지에서, order와 filter 상태를 추가하고 상태가 업데이트 되면 모임 롤링페이퍼 조회 요청을 refetch 하도록 했습니다.

### 수정 후
#### 모바일
<img src="https://user-images.githubusercontent.com/71116429/195998988-74a89513-2129-4b16-b2b7-d440f9f2732f.png" width="300px" />

#### 데스크탑
<img src="https://user-images.githubusercontent.com/71116429/195999011-f4a0b914-e7b3-43ad-9407-4139ae2d77ff.png" width="600px" />

## 논의할 부분
- 로직을 먼저 정리하는 과정에서 기본 select, option 태그로 구현해봤습니다. 이후에 Select, Dropdown을 추가로 직접 구현할까 생각도 했는데요. **제 생각에는 기본 select, option 태그의 UI도 깔끔하고 괜찮아서 커스텀 컴포넌트를 따로 만들지는 않았어요.** 
저는 지금도 충분히 괜찮다고 생각합니다. **스타일을 더 주는 게 필요하다고 생각하는지, 준다면 어떤 스타일이 괜찮은지** 도리 의견 궁금합니다~

2022-10-16 05:08 UTC, prefer2 requested changes
url의 searchParams에 order와 filter를 추가해서 정렬기능 구현 잘 해주셨네요! 
정렬이 되니 진짜 서비스같고 보기 좋네요 👍👍👍

refetch 관련해서만 리뷰 남겼습니다

저도 생각보다 select가 이뻐서 따로 스타일 구현은 안해도 괜찮은 것 같아요(폰트의 힘을 느꼈습니다)

다만 이 select의 위치가 좀 고민이 되네요. + 버튼 옆으로 가자니 모바일에서 공간이 부족하기도 하고, + 버튼이 헷갈리는 것 같고. 이 부분은 다른 레퍼런스들을 조금 더 찾아봐야 할 것 같네요...

아애 롤링페이퍼 만들기와 select를 제목 아래로 내려야하나 생각이 들기도 하고요 🤔

<img width="336" alt="스크린샷 2022-10-16 오후 2 07 14" src="https://user-images.githubusercontent.com/67692759/196019113-02ba3ed8-14f5-46a9-9a4d-1fe354431f2d.png">

2022-10-18 17:40 UTC, soyi47 commented
리뷰 모두 반영했습니다. 
롤링페이퍼 만들기 버튼 UI 개선 포함하여 작업했습니다.

<img src="https://user-images.githubusercontent.com/71116429/196504749-41d01404-f9a0-4f0c-88d3-1ad10ab03fd8.png" width="300px" />

2022-10-18 17:41 UTC, soyi47 commented on frontend/src/api/team.ts
> +    console.log(params, params.toString());
삭제 완료~ https://github.com/woowacourse-teams/2022-nae-pyeon/pull/571/commits/dd92f3bf93d4cafd611efbf5a0b3db27c3186840

2022-10-18 17:41 UTC, soyi47 commented on frontend/src/pages/TeamDetailPage/components/RollingpaperList.tsx
> +  }, [order, filter]);
적용해봤습니다~ https://github.com/woowacourse-teams/2022-nae-pyeon/pull/571/commits/8feb772e2df55e6457dcbc2e42071b77fb0e1306

2022-10-18 17:46 UTC, prefer2 approved these changes
이전의 버튼보다 UI가 이뻐졌네요! 보다 분명하게 알려주는 것 같아서 만족입니다!
수정사항 확인해서 머지할께요~~

2022-10-18 17:47 UTC, merged