refactor: 롤링페이퍼 생성 페이지를 개선한다
woowacourse-teams/2022-nae-pyeon pull request #589
Opened 2022-10-19 10:29 UTC by prefer2

## 구현 사항
- ref를 사용하지 않고 width로 이동을 구현했습니다. scrollBy를 사용했습니다. 과정에서 저희가 사용하는 화면 크기를 상수화하면 좋겠다는 생각이 들었습니다.
- 기존에 모임상세 페이지에서 어떤 모임을 선택했는지를 보여주었는데요, 바로 모임/개인을 선택할 수 있도록 변경했습니다.
- 로더에 layout을 지정하여 step2가 미리 보이는 일을 방지했습니다.
- dotController에서 progressBar로 변경하였습니다.
- 비즈니스 로직은 훅으로 분리하였습니다.

![스크린샷 2022-10-19 오후 10 04 52](https://user-images.githubusercontent.com/67692759/196698857-f6d264de-f0ea-40bd-8e1b-7c1c2b46ae6d.png)

closed #564

2022-10-19 16:05 UTC, soyi47 requested changes
도리~ 고생하셨습니다~ 👍👍👍

컴포넌트 네이밍이나 로직 분리 위주로 남겼어요.
롤링페이퍼 만들기 과정에 불필요한 상태가 보여서 그 부분도 코멘트 남겼습니다.
확인 부탁드려요~!

2022-10-19 16:06 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/components/Step2.tsx
> +    setStep((prev) => prev + 0.5);
위 코멘트 확인해주십쇼 https://github.com/woowacourse-teams/2022-nae-pyeon/pull/589#discussion_r999662034

2022-10-20 01:47 UTC, prefer2 commented on frontend/src/components/ProgressBar.tsx
> +}
좋아요. 저도 이 부분 작성하면서 객체 타입으로 작성하는게 과연 옳은가... 라는 생각을 했는데 인라인으로 쓰는거 좋네요(재사용 안하는 타입이니) 아래 코멘트와 함께 수정했습니다. 0e087ff

2022-10-20 02:58 UTC, prefer2 commented
리뷰 감사합니다🥰 네이밍의 중요성을 느낄 수 있는 PR이었던 것 같네요.
제안해주신 방향으로 전반적으로 로직 수정해보았습니다. 덕분에 정리가 좀 된 것 같네요!!!!

2022-10-20 04:53 UTC, soyi47 requested changes
요것들만 수정해주시죠..!

2022-10-20 04:53 UTC, soyi47 commented on frontend/src/pages/RollingpaperCreationPage/hooks/useSteps.tsx
> +}
타입 이름이 이제 Step이 아니네요! RollingpaperCreateForm!

2022-10-20 04:53 UTC, soyi47 commented on frontend/src/components/ProgressBar.tsx
> +const StyledProgressBarBackGround = styled.div`
Background는 하나의 단어니까 수정이 필요하겠네요!

2022-10-20 05:15 UTC, merged