refactor: 서버 요청 커스텀 훅 파일을 정리
woowacourse-teams/2022-nae-pyeon pull request #630
Opened 2022-10-27 04:45 UTC by prefer2

## 작업 내용
- Api 관련 custom hook hooks/api 폴더로 도메인 별로 이동
- 불필요한 react import문 제거
- refresh token관련 type 지정

### 고민
- useReadMyTeams를 재사용 할 것인가
    - 기존에는 무한 스크롤을 위한 useInfiniteQuery - getMyTeams와 useQuery - getMyTeams가 나뉘어져 있음
    - useInfiniteQuery를 재사용 하는 것이 좋을지 따로 선언해주는 것이 좋을지 고민
    - 재사용 하는 방식으로 변경
- useCreateRenewalToken
    - mutateFunc를 넘겨야 해서 기존의 컨벤션과 동일하게 useMutation의 variable 자리에 request type을 넣기 어려움
    - onSuccess 값을 초기 선언시에 넘겨 줄 수 없음
    - 우선은 컨벤션에 맞지 않지만 Variable값을 따로 선언하는 방식을 선택

closed #629

2022-10-27 06:59 UTC, soyi47 requested changes
도리 고생했어요~ 👏👏👏
오프라인으로 논의한 방식대로 파일 정리하여 push 해뒀습니다. 한번 확인 부탁해요!

### 작업 내용
- api 폴더에 도메인 단위의 파일로 커스텀 훅을 묶어 정리했고
- onSuccess의 매개변수 이름이 variable로 작성된 부분들은 variables로 변경했습니다.

### 고민에 대한 답변
1. useReadMyTeams를 재사용할 것인가 -> 현재 재사용하는 방식으로 변경
추가 로드가 필요할 때 fetchNextPage를 호출하는 방식이므로 useQuery 대신 useInfiniteQuery만으로 작성해도 충분하다고 생각합니다. 
단 infiniteQuery를 사용한다는 걸 api 커스텀 훅 이름에 추가해주면 좋을 것 같아요.
우선 저는 `useReadMyTeamsWithInfiniteLoad`나 `useReadMyTeamsWithPagination` 정도가 떠오릅니다.

2. useCreateRenewalToken
variables 타입과 apiRequest 타입이 일치하지 않아 논의했던 부분이네요. 작업하신대로 Variables라는 이름으로 타입을 정의해두어도 괜찮은 것 같아요.
RefreshToken 관련해서는 구현에서부터 더 나은 방향이 없는지 고민하기로 했으니, 더 수정될 수 있을 것 같아 타이핑은 이렇게 두어도 될 것 같아요.

이번 PR에서 추가 작업 필요한 부분 있을까요? 의견 주세요!

2022-10-27 11:48 UTC, prefer2 commented
도메인별로 파일로 분리 잘 해주셨네요!! 수고 많았어요 소피아 👍👍👍

### 추가로 정리해보면 좋을 사항
- useReadMyTeams에 대한 네이밍 변경 제안해주신 점들 좋네요! 저도 보면서 이건 useQuery를 사용한게 아닌데 똑같은 네이밍이 괜찮을까 신경쓰였는데 좋은 것 같아요. 저는 두 네이밍중에 `useReadMyTeamsWithPagination`이 좋네요!
- 파일내의 훅 순서가 일정하지 않은데요 순서를 맞춰주는건 어떨까요?? CRUD순서도 좋을 것 같고, 기존 api 함수와 동일하게 GET, POST, PUT, DELETE 순서도 좋습니다!

2022-10-27 11:49 UTC, prefer2 commented on frontend/src/hooks/api/team.ts
> +const useCreateTeamMember = (onClickCloseButton: () => void) => {
여기도 다른 곳처럼 { onSuccess } 형태로 받아서 type 지정까지 해주는 방식으로 변경해야 할 것 같아요!

2022-10-28 05:33 UTC, prefer2 commented
작업 이어받아 변경사항들 모두 처리했습니다!

2022-10-28 11:51 UTC, soyi47 approved these changes
확인했습니다! 머지하겠습니다~ 고생했어요! 🤗🤗🤗

2022-10-28 11:51 UTC, merged